package pluginmanifest_test

import (
	"bytes"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/qompack/qompack/internal/core"
	"github.com/qompack/qompack/internal/pluginmanifest"
)

// goldenRoot is testdata/golden/, relative to this package. The goldens mirror the bundle's own
// directory structure, so testdata/golden/plugin/hooks/hooks.json is the golden for
// plugin/hooks/hooks.json.
const goldenRoot = "../../testdata/golden"

// TestManifest_GoldenBytes freezes the exact bytes of all ten generated files. Together with the
// `plugin-validate` CI job and `git diff --exit-code -- plugin/`, this is what makes silent
// drift in the undocumented host contract (G9.3) impossible: a change to any key name, timeout,
// or command string fails here first, in a diff a reviewer can read.
func TestManifest_GoldenBytes(t *testing.T) {
	files, err := pluginmanifest.Default(core.Version).Files()
	require.NoError(t, err)
	require.Len(t, files, 10)

	for rel, want := range files {
		t.Run(rel, func(t *testing.T) {
			got, err := os.ReadFile(filepath.Join(goldenRoot, filepath.FromSlash(rel)))
			require.NoError(t, err, "golden missing for %s", rel)
			// Normalize CRLF: the golden is stored LF but a Windows checkout may materialize CRLF.
			got = bytes.ReplaceAll(got, []byte("\r\n"), []byte("\n"))
			require.Equal(t, string(want), string(got), "generated bytes drifted from the golden for %s", rel)
		})
	}
}

// TestBundle_OnDiskMatchesGenerator is the in-test half of the `plugin-validate` CI job: the
// committed plugin/ tree must be exactly what the generator produces.
func TestBundle_OnDiskMatchesGenerator(t *testing.T) {
	repoRoot := "../.."
	if _, err := os.Stat(filepath.Join(repoRoot, "plugin")); os.IsNotExist(err) {
		t.Skip("plugin/ bundle not materialized in this tree")
	}
	diffs := pluginmanifest.Validate(repoRoot, pluginmanifest.Default(core.Version))
	for _, d := range diffs {
		t.Errorf("plugin bundle drift: %s (%s)", d.Path, d.Reason)
	}
}
