// Package pluginmanifest is the single typed source for the installable plugin bundle.
//
// Qompack.md §7.5 gives one logical manifest; Claude Code's physical layout splits it across
// plugin.json, hooks/hooks.json, .mcp.json and commands/*.md (§3.4). Generating all four from
// one Go value is what makes it impossible for them to drift apart, and `devtool plugin-validate`
// diffs the generated bytes against the committed tree in CI so drift can never land silently.
//
// The exact key names here (`matcher`, `${CLAUDE_PLUGIN_ROOT}`, the hooks.json nesting) are
// partly undocumented host contract and are expected to change (G9.3). When they do, this file
// is the only place that changes.
package pluginmanifest

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

// pluginDir is the bundle root, relative to the repository root.
const pluginDir = "plugin"

// binaryRef is how every generated file refers to the platform binary. The host expands
// ${CLAUDE_PLUGIN_ROOT} to the installed plugin directory.
const binaryRef = "${CLAUDE_PLUGIN_ROOT}/bin/qompack"

// Manifest is the whole bundle as one typed value.
type Manifest struct {
	Plugin   PluginJSON
	Hooks    HooksJSON
	MCP      MCPJSON
	Commands []CommandDoc
}

// PluginJSON is plugin/.claude-plugin/plugin.json (§3.4).
type PluginJSON struct {
	Name        string   `json:"name"`
	Version     string   `json:"version"`
	Description string   `json:"description"`
	Author      Author   `json:"author"`
	Homepage    string   `json:"homepage"`
	Keywords    []string `json:"keywords"`
}

// Author is the plugin author block.
type Author struct {
	Name string `json:"name"`
}

// HooksJSON is plugin/hooks/hooks.json: hook event name to its matcher groups.
type HooksJSON struct {
	Hooks map[string][]HookGroup `json:"hooks"`
}

// HookGroup is one matcher group. Matcher is omitted for hooks that do not match on tool name.
type HookGroup struct {
	Matcher string      `json:"matcher,omitempty"`
	Hooks   []HookEntry `json:"hooks"`
}

// HookEntry is a single command invocation with its host-enforced timeout in seconds.
type HookEntry struct {
	Type    string `json:"type"`
	Command string `json:"command"`
	Timeout int    `json:"timeout"`
}

// MCPJSON is plugin/.mcp.json.
type MCPJSON struct {
	MCPServers map[string]MCPServer `json:"mcpServers"`
}

// MCPServer is one MCP server declaration.
type MCPServer struct {
	Command string   `json:"command"`
	Args    []string `json:"args"`
}

// CommandDoc is one plugin/commands/<name>.md file. SP-14 owns the prose beyond this skeleton.
type CommandDoc struct {
	Name         string
	Description  string
	ArgumentHint string
	Subcommand   string
	AllowedTools string
}

// hookSpec is the internal description of one hooks.json entry.
type hookSpec struct {
	event   string
	matcher string
	args    string
	timeout int
}

// hookSpecs is the §3.4 hook table. All six §7.3 hooks are covered; Stop and SubagentStop are
// separate entries because the host delivers them as distinct events.
var hookSpecs = []hookSpec{
	{event: "PostToolUse", matcher: "*", args: "observe tool", timeout: 5},
	{event: "UserPromptSubmit", args: "observe prompt", timeout: 5},
	{event: "SessionStart", args: "session-start", timeout: 15},
	{event: "PreCompact", args: "checkpoint", timeout: 20},
	{event: "Stop", args: "observe stop", timeout: 5},
	{event: "SubagentStop", args: "observe stop --subagent", timeout: 10},
	{event: "SessionEnd", args: "flush", timeout: 20},
}

// commandSpecs is the §7.5 command list: exactly seven, in the order §7.5 states them.
var commandSpecs = []CommandDoc{
	{
		Name:         "status",
		Description:  "Qompack status — mode, contracts, store, latency, last decision",
		ArgumentHint: "[--json]",
		Subcommand:   "status",
	},
	{
		Name:         "recall",
		Description:  "Search stored tool output and file versions by content",
		ArgumentHint: "<query> [--k N]",
		Subcommand:   "recall",
	},
	{
		Name:         "pin",
		Description:  "Pin an invariant so it is never summarized away",
		ArgumentHint: "<text>",
		Subcommand:   "pin",
	},
	{
		Name:         "checkpoint",
		Description:  "Write an immutable checkpoint now",
		ArgumentHint: "[--reason <text>]",
		Subcommand:   "checkpoint",
	},
	{
		Name:         "why",
		Description:  "Explain a recorded decision and the evidence behind it",
		ArgumentHint: "<decision-id>",
		Subcommand:   "why",
	},
	{
		Name:         "dropped",
		Description:  "Report what the last compaction dropped and how to get it back",
		ArgumentHint: "[--json]",
		Subcommand:   "dropped",
	},
	{
		Name:         "eval",
		Description:  "Run the replay harness and report the score against the baseline",
		ArgumentHint: "[--corpus <dir>]",
		Subcommand:   "eval",
	},
}

// Default returns the manifest for the given version. Callers pass core.Version; this package
// takes it as a parameter rather than importing core so the generator stays trivially testable
// against a fixed version string.
func Default(version string) Manifest {
	hooks := make(map[string][]HookGroup, len(hookSpecs))
	for _, h := range hookSpecs {
		hooks[h.event] = []HookGroup{{
			Matcher: h.matcher,
			Hooks: []HookEntry{{
				Type:    "command",
				Command: binaryRef + " " + h.args,
				Timeout: h.timeout,
			}},
		}}
	}

	cmds := make([]CommandDoc, len(commandSpecs))
	copy(cmds, commandSpecs)
	for i := range cmds {
		cmds[i].AllowedTools = fmt.Sprintf("Bash(qompack %s:*)", cmds[i].Subcommand)
	}

	return Manifest{
		Plugin: PluginJSON{
			Name:        "qompack",
			Version:     version,
			Description: "Cache-aware, retrieval-backed context compaction",
			Author:      Author{Name: "Qompack"},
			Homepage:    "https://github.com/qompack/qompack",
			Keywords:    []string{"compaction", "context", "memory", "cache"},
		},
		Hooks: HooksJSON{Hooks: hooks},
		MCP: MCPJSON{MCPServers: map[string]MCPServer{
			"qompack": {Command: binaryRef, Args: []string{"mcp"}},
		}},
		Commands: cmds,
	}
}

// marshal renders v with two-space indentation and a trailing newline. Both are load-bearing:
// `git diff --exit-code -- plugin/` is a CI gate, so the bytes must be stable and must match what
// a human editor would leave behind.
func marshal(v any) ([]byte, error) {
	var buf bytes.Buffer
	enc := json.NewEncoder(&buf)
	enc.SetIndent("", "  ")
	enc.SetEscapeHTML(false)
	if err := enc.Encode(v); err != nil {
		return nil, err
	}
	return buf.Bytes(), nil
}

// renderCommand builds one plugin/commands/<name>.md file.
func renderCommand(c CommandDoc) []byte {
	var b strings.Builder
	b.WriteString("---\n")
	fmt.Fprintf(&b, "description: %s\n", c.Description)
	fmt.Fprintf(&b, "argument-hint: %q\n", c.ArgumentHint)
	fmt.Fprintf(&b, "allowed-tools: %s\n", c.AllowedTools)
	b.WriteString("---\n\n")
	b.WriteString("Run the Qompack " + c.Subcommand + " command and report its output verbatim to the user.\n\n")
	fmt.Fprintf(&b, "!`qompack %s $ARGUMENTS`\n", c.Subcommand)
	return []byte(b.String())
}

// Files returns every generated file as repo-relative path to exact bytes.
func (m Manifest) Files() (map[string][]byte, error) {
	out := make(map[string][]byte, len(m.Commands)+3)

	pj, err := marshal(m.Plugin)
	if err != nil {
		return nil, fmt.Errorf("plugin.json: %w", err)
	}
	out[filepath.ToSlash(filepath.Join(pluginDir, ".claude-plugin", "plugin.json"))] = pj

	hj, err := marshal(m.Hooks)
	if err != nil {
		return nil, fmt.Errorf("hooks.json: %w", err)
	}
	out[filepath.ToSlash(filepath.Join(pluginDir, "hooks", "hooks.json"))] = hj

	mj, err := marshal(m.MCP)
	if err != nil {
		return nil, fmt.Errorf("mcp.json: %w", err)
	}
	out[filepath.ToSlash(filepath.Join(pluginDir, ".mcp.json"))] = mj

	for _, c := range m.Commands {
		p := filepath.ToSlash(filepath.Join(pluginDir, "commands", c.Name+".md"))
		out[p] = renderCommand(c)
	}
	return out, nil
}

// Write materializes the bundle under dir, which is the repository root (or a temp dir when
// validating). Directories are created as needed.
func Write(dir string, m Manifest) error {
	files, err := m.Files()
	if err != nil {
		return err
	}
	for rel, b := range files {
		p := filepath.Join(dir, filepath.FromSlash(rel))
		if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
			return err
		}
		// #nosec G306 -- the bundle is non-secret generated manifest content that the host must
		// be able to read after install; 0o600 would make an installed plugin unreadable.
		if err := os.WriteFile(p, b, 0o644); err != nil {
			return err
		}
	}
	return nil
}

// Diff is one discrepancy between the generated bundle and the tree on disk.
type Diff struct {
	Path   string
	Reason string
	Want   []byte
	Got    []byte
}

// Validate compares the generated bundle against the tree rooted at dir. It reports missing
// files, differing files, and extra files under plugin/ that the generator does not produce.
// plugin/bin/** is exempt: it is populated at package time by SP-17, not by this generator.
func Validate(dir string, m Manifest) []Diff {
	files, err := m.Files()
	if err != nil {
		return []Diff{{Path: pluginDir, Reason: "generate: " + err.Error()}}
	}

	var diffs []Diff
	for rel, want := range files {
		got, err := os.ReadFile(filepath.Join(dir, filepath.FromSlash(rel)))
		if err != nil {
			diffs = append(diffs, Diff{Path: rel, Reason: "missing", Want: want})
			continue
		}
		if !bytes.Equal(want, normalizeEOL(got)) {
			diffs = append(diffs, Diff{Path: rel, Reason: "content differs", Want: want, Got: got})
		}
	}

	for _, rel := range walkBundle(dir) {
		if _, ok := files[rel]; !ok {
			diffs = append(diffs, Diff{Path: rel, Reason: "not produced by the generator"})
		}
	}

	sort.Slice(diffs, func(i, j int) bool { return diffs[i].Path < diffs[j].Path })
	return diffs
}

// normalizeEOL collapses CRLF to LF so a Windows checkout does not report spurious diffs. The
// generator always emits LF and .gitattributes keeps it that way in the object database.
func normalizeEOL(b []byte) []byte { return bytes.ReplaceAll(b, []byte("\r\n"), []byte("\n")) }

// walkBundle lists every file under <dir>/plugin, excluding plugin/bin/**, as repo-relative
// forward-slash paths.
func walkBundle(dir string) []string {
	root := filepath.Join(dir, pluginDir)
	binPrefix := pluginDir + "/bin/"

	var out []string
	_ = filepath.WalkDir(root, func(p string, d os.DirEntry, err error) error {
		if err != nil || d.IsDir() {
			return nil //nolint:nilerr // a missing bundle is reported as "missing" per file above
		}
		rel, relErr := filepath.Rel(dir, p)
		if relErr != nil {
			return nil
		}
		slash := filepath.ToSlash(rel)
		if strings.HasPrefix(slash, binPrefix) {
			return nil
		}
		out = append(out, slash)
		return nil
	})
	sort.Strings(out)
	return out
}
