package dag

import (
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"testing"
	"time"

	"github.com/qompack/qompack/internal/config"
	"github.com/qompack/qompack/internal/core"
	"github.com/qompack/qompack/internal/logging"
	"github.com/qompack/qompack/internal/testutil"
	"github.com/stretchr/testify/require"
)

// This file publishes the contract fixtures SP-08, SP-09 and SP-12 assert against under Rule W-2,
// and asserts this package still reproduces them. It is both generator and check: with -update it
// rewrites them, without it compares.
//
// The fixtures live under testdata/golden/contracts/dag/ rather than testdata/golden/dag/, so
// testutil.Golden cannot place them — that helper derives its directory from the calling package's
// own name. The path is spelled relative to this package, exactly as fixture_test.go already spells
// the frozen want/ directory next door.

// contractDir is testdata/golden/contracts/dag/, relative to internal/dag.
const contractDir = "../../testdata/golden/contracts/dag"

// goldenClockMillis is the instant every generated fixture is stamped at. A fixed clock is what
// makes these files byte-reproducible: tombstone and generation records carry a timestamp, and a
// wall clock would rewrite the golden on every run. §4's rule that every package observing time
// takes a core.Clock exists precisely so this is possible.
const goldenClockMillis = 1730000000000

// updateGolden reports whether -update was passed.
//
// The flag is looked up before being registered because testutil registers one of its own as soon
// as anything in this test binary imports it, and two packages calling flag.Bool with the same name
// panic during init. Looking it up first turns that collision into what both sides actually wanted:
// a single -update flag driving every golden in the binary.
var updateGolden = registerContractUpdateFlag()

// registerContractUpdateFlag returns a reader for -update, registering the flag only if nothing
// else already has.
func registerContractUpdateFlag() func() bool {
	const name = "update"
	if f := flag.Lookup(name); f != nil {
		return func() bool { return f.Value.String() == "true" }
	}
	p := flag.Bool(name, false, "rewrite golden files under testdata/golden/ instead of comparing against them")
	return func() bool { return *p }
}

// contractGoldenPerm matches testutil's: these are committed source files, not runtime store files.
const contractGoldenPerm = 0o644

// assertContractGolden compares got against testdata/golden/contracts/dag/<name>, or rewrites it
// under -update.
//
// Both sides are normalized to LF first. .gitattributes leaves .json and .jsonl subject to
// eol=lf, but a Windows checkout can still hand a tool CRLF bytes, and a contract fixture that
// failed on the primary development platform for a reason unrelated to the code under test would
// be worse than no fixture at all.
func assertContractGolden(t *testing.T, name string, got []byte) {
	t.Helper()
	path := filepath.Join(contractDir, name)

	if updateGolden() {
		require.NoError(t, os.WriteFile(path, got, contractGoldenPerm))
		t.Logf("updated %s (%d bytes)", path, len(got))
		return
	}

	want, err := os.ReadFile(path)
	require.NoError(t, err, "contract fixture missing: %s (regenerate with -update)", path)
	require.Equal(t, stripCR(string(want)), stripCR(string(got)),
		"%s drifted; if the change is intended, regenerate with -update and say why in the commit", name)
}

// stripCR removes carriage returns so a CRLF checkout compares equal to the LF bytes on disk.
func stripCR(s string) string {
	out := make([]byte, 0, len(s))
	for i := 0; i < len(s); i++ {
		if s[i] != '\r' {
			out = append(out, s[i])
		}
	}
	return string(out)
}

// The graph-basic fixture's identifiers, named once so the generator and every expectation below
// agree by construction rather than by careful retyping.
const (
	gbTool1            core.ToolUseID  = "toolu_01ABCdef"
	gbTool2            core.ToolUseID  = "toolu_02GHIjkl"
	gbPath                             = "src/auth.ts"
	gbSymbol                           = "refreshToken"
	gbDecision         core.DecisionID = "dec_9f86d081884c"
	gbElimination                      = "elim_2f1c"
	gbNodeCount                        = 12
	gbEdgeCount                        = 10
	gbGoldenGeneration                 = 1
)

// buildGraphBasic constructs the fixture graph: twelve nodes covering all nine kinds, ten edges
// covering all eight kinds, and one tombstone.
//
// It is hand-built rather than driven through the builders, deliberately. A fixture generated by
// BuildToolUse would silently redefine itself whenever that function's edge set changed, which is
// the opposite of what a frozen contract is for: SP-08, SP-09 and SP-12 assert against these bytes,
// so a change here has to show up as a golden diff somebody has to explain.
func buildGraphBasic(t *testing.T) *graph {
	t.Helper()
	g := newGraph(t.TempDir(), config.Defaults(), logging.Nop())
	g.SetClock(testutil.NewFakeClock(time.UnixMilli(goldenClockMillis).UTC()))

	ts := core.UnixMilli(goldenClockMillis)
	add := func(id NodeID, kind NodeKind, turn core.TurnIndex, pos int, ref string, tokens core.Tokens) {
		t.Helper()
		require.NoError(t, g.AddNode(Node{
			ID: id, Kind: kind, Turn: turn, TS: ts, Pos: pos, Ref: ref, Tokens: tokens,
		}))
	}

	add(UserPromptNode(1), KindUserPrompt, 1, 100, "add token refresh", 40)
	add(AssistantNode(1), KindAssistant, 1, 200, "", 0)
	add(ToolUseNode(gbTool1), KindToolUse, 1, 300, "Read", 0)
	add(FileNode(gbPath), KindFile, 1, 350, gbPath, 0)
	add(SymbolNode(gbPath, gbSymbol), KindSymbol, 1, 360, gbSymbol, 0)
	add(ToolResultNode(gbTool1), KindToolResult, 1, 400, string(gbTool1), 512)
	add(AssistantNode(2), KindAssistant, 2, 500, "", 0)
	add(ToolUseNode(gbTool2), KindToolUse, 2, 600, "Edit", 0)
	add(ToolResultNode(gbTool2), KindToolResult, 2, 700, string(gbTool2), 128)
	add(DecisionNode(gbDecision), KindDecision, 2, 800, "use a refresh token", 24)
	add(EliminationNode(gbElimination), KindElimination, 2, 900, gbPath, 0)
	add(SegmentNode(1), KindSegment, 1, 100, "1-2", 1204)

	edge := func(from, to NodeID, kind EdgeKind, turn core.TurnIndex) {
		t.Helper()
		require.NoError(t, g.AddEdge(Edge{From: from, To: to, Kind: kind, Weight: 1, Turn: turn}))
	}

	edge(UserPromptNode(1), AssistantNode(1), EdgeConsumes, 1)
	edge(AssistantNode(1), ToolUseNode(gbTool1), EdgeControlOnly, 1)
	edge(ToolUseNode(gbTool1), ToolResultNode(gbTool1), EdgeProduces, 1)
	edge(FileNode(gbPath), ToolUseNode(gbTool1), EdgeSharedFile, 1)
	edge(SymbolNode(gbPath, gbSymbol), ToolUseNode(gbTool1), EdgeSharedSymbol, 1)
	edge(ToolResultNode(gbTool1), AssistantNode(2), EdgeConsumes, 2)
	edge(AssistantNode(2), ToolUseNode(gbTool2), EdgeSequence, 2)
	edge(ToolUseNode(gbTool2), ToolResultNode(gbTool2), EdgeProduces, 2)
	edge(ToolUseNode(gbTool1), ToolUseNode(gbTool2), EdgeSupersedes, 2)
	edge(ToolResultNode(gbTool2), DecisionNode(gbDecision), EdgeExplains, 2)

	require.NoError(t, g.Tombstone([]NodeID{EliminationNode(gbElimination)}))
	return g
}

// TestGraphBasicFixtureCoversEveryKind is the fixture's own sanity check: a contract fixture that
// silently stopped covering a kind would still pass its byte comparison forever.
func TestGraphBasicFixtureCoversEveryKind(t *testing.T) {
	g := buildGraphBasic(t)

	nodeKinds := make(map[NodeKind]bool)
	for _, n := range g.nodes {
		nodeKinds[n.Kind] = true
	}
	edgeKindsSeen := make(map[EdgeKind]bool)
	for _, e := range g.edges {
		edgeKindsSeen[e.Kind] = true
	}

	for k := KindToolUse; k <= KindSegment; k++ {
		require.True(t, nodeKinds[k], "graph-basic must contain a %s node", k)
	}
	for k := EdgeSequence; k <= EdgeControlOnly; k++ {
		require.True(t, edgeKindsSeen[k], "graph-basic must contain a %s edge", k)
	}
	require.Len(t, g.nodes, gbNodeCount)
	require.Len(t, g.edges, gbEdgeCount)
	require.Len(t, g.dead, 1, "graph-basic carries exactly one tombstone")
}

// TestGraphBasicGolden publishes graph-basic.jsonl and proves Flush still reproduces it byte for
// byte. The generation header is written here rather than by Flush because only Compact emits one
// at runtime; everything after the first line is exactly what Flush appended.
func TestGraphBasicGolden(t *testing.T) {
	g := buildGraphBasic(t)
	require.NoError(t, g.Flush(context.Background()))

	appended, err := os.ReadFile(g.logPath)
	require.NoError(t, err)

	header, err := encodeGeneration(gbGoldenGeneration, core.UnixMilli(goldenClockMillis), gbNodeCount, gbEdgeCount)
	require.NoError(t, err)

	full := make([]byte, 0, len(header)+1+len(appended))
	full = append(full, header...)
	full = append(full, '\n')
	full = append(full, appended...)
	assertContractGolden(t, "graph-basic.jsonl", full)
}

// crossingRow is one row of crossing.json: a candidate cut point and segment_coupling at it.
type crossingRow struct {
	Pos      int `json:"pos"`
	Crossing int `json:"crossing"`
}

// TestCrossingEdgesGolden publishes crossing.json — segment_coupling(p) at twelve positions across
// the fixture, including 0, 1, every node position, and one past the end.
func TestCrossingEdgesGolden(t *testing.T) {
	g := buildGraphBasic(t)

	positions := []int{0, 1, 100, 200, 300, 350, 360, 400, 500, 600, 700, 901}
	rows := make([]crossingRow, 0, len(positions))
	for _, pos := range positions {
		rows = append(rows, crossingRow{Pos: pos, Crossing: g.CrossingEdges(pos)})
	}

	got, err := json.MarshalIndent(rows, "", "  ")
	require.NoError(t, err)
	assertContractGolden(t, "crossing.json", append(got, '\n'))

	// Two hand-checkable anchors, so a regenerated golden cannot drift into being self-consistent
	// nonsense: nothing precedes position 0, and nothing straddles a cut past every endpoint.
	require.Equal(t, 0, g.CrossingEdges(0), "nothing can lie before the start of the prefix")
	require.Equal(t, 0, g.CrossingEdges(901), "a cut past every endpoint separates nothing")
}

// sliceGoldenRow is one recorded slice: the options that produced it, and the result.
type sliceGoldenRow struct {
	Thin     bool              `json:"thin"`
	Decay    float32           `json:"decay"`
	Criteria []NodeID          `json:"criteria"`
	Order    []NodeID          `json:"order"`
	Scores   map[NodeID]string `json:"scores"`
}

// TestSliceGoldenBackward publishes slice-backward.json for both Thin settings.
//
// Scores are recorded to five decimal places as strings rather than as raw float32s. A float32
// renders through encoding/json at full precision — 0.7224999666213989 — which is unreadable and
// gratuitously sensitive to the last bit of an intermediate product. Five places is far more
// precision than any consumer ranks on, and it is stable across platforms.
func TestSliceGoldenBackward(t *testing.T) {
	g := buildGraphBasic(t)
	criteria := []NodeID{DecisionNode(gbDecision)}

	rows := make([]sliceGoldenRow, 0, 2)
	for _, thin := range []bool{true, false} {
		sl, err := g.BackwardSlice(criteria, SliceOptions{Thin: thin, Decay: DefaultDecay})
		require.NoError(t, err)

		scores := make(map[NodeID]string, len(sl.Scores))
		for id, s := range sl.Scores {
			scores[id] = fmt.Sprintf("%.5f", s)
		}
		rows = append(rows, sliceGoldenRow{
			Thin: thin, Decay: DefaultDecay, Criteria: criteria, Order: sl.Order, Scores: scores,
		})
	}

	got, err := json.MarshalIndent(rows, "", "  ")
	require.NoError(t, err)
	assertContractGolden(t, "slice-backward.json", append(got, '\n'))

	// The properties the fixture exists to pin, asserted directly so a regenerated golden cannot
	// quietly record a thin slice that reaches more than the full one.
	thinRow, fullRow := rows[0], rows[1]
	require.LessOrEqual(t, len(thinRow.Scores), len(fullRow.Scores),
		"a thin slice can never reach more nodes than the full slice of the same criteria")
	require.Equal(t, "1.00000", thinRow.Scores[DecisionNode(gbDecision)],
		"a criterion always scores exactly 1")
	require.Equal(t, DecisionNode(gbDecision), thinRow.Order[0],
		"the criterion is the highest-scoring node in its own slice")
}
