package tokens_test

import (
	"bytes"
	"context"
	"math"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/qompack/qompack/internal/config"
	"github.com/qompack/qompack/internal/core"
	"github.com/qompack/qompack/internal/obs"
	"github.com/qompack/qompack/internal/tokens"
)

// mediaDir is testdata/corpora/media, relative to this package's own directory. The fixtures are
// regenerated by `go run ./tools/devtool gen-fixtures`.
const mediaDir = "../../testdata/corpora/media"

// readFixture reads one generated media fixture, failing loudly when it is missing rather than
// letting a nil payload silently make an assertion vacuous.
func readFixture(t *testing.T, name string) []byte {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(mediaDir, name))
	require.NoError(t, err, "media fixture missing: run `go run ./tools/devtool gen-fixtures`")
	require.NotEmpty(t, b)
	return b
}

// newExact builds an exact estimator with in-memory-only calibration and no chunk-cache file,
// which is what most of these tests want: the estimator's arithmetic, with no persistence noise.
func newExact(t *testing.T) tokens.Estimator {
	t.Helper()
	return tokens.NewExact(config.Defaults(), "", "")
}

// TestClassify_All exercises one sample per class with an EMPTY path, which is the shape store
// content arrives in: without an extension to switch on, Classify must reach its magic-byte and
// sniff rules. The PNG case is the single rule SP-06 adds to SP-01's Classify.
func TestClassify_All(t *testing.T) {
	cases := []struct {
		name string
		tool string
		body []byte
		want tokens.Class
	}{
		{"png magic", "", readFixture(t, "tiny.png"), tokens.ClassImage},
		{"jpeg magic", "", readFixture(t, "tiny.jpg"), tokens.ClassImage},
		{"gif magic", "", readFixture(t, "tiny.gif"), tokens.ClassImage},
		{"webp magic", "", readFixture(t, "tiny.webp"), tokens.ClassImage},
		{"pdf magic", "", []byte("%PDF-1.7 trailing content"), tokens.ClassPDF},
		{"nul heavy blob", "", []byte{'a', 0x00, 'b', 0x00, 'c'}, tokens.ClassBinary},
		{"json", "", []byte(`{"a":1}`), tokens.ClassJSON},
		{"diff", "", []byte("diff --git a/x.go b/x.go\n--- a/x.go\n"), tokens.ClassDiff},
		{"go source", "", []byte("package main\n\nfunc main() {\n\tprintln(\"hi\")\n}\n"), tokens.ClassCode},
		{"plain prose", "", []byte("Just a sentence of ordinary prose without code shape.\n"), tokens.ClassProse},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			require.Equal(t, tc.want, tokens.Classify(tc.tool, "", tc.body))
		})
	}
}

// TestClassify_ImageMagicPrecedesPDFCheck pins the ONE rule SP-06 inserts into SP-01's Classify:
// image magic bytes are recognised before the %PDF check, so a PNG with no path still classifies
// as an image rather than falling through to the binary sniff.
func TestClassify_ImageMagicPrecedesPDFCheck(t *testing.T) {
	png := readFixture(t, "tiny.png")
	require.Equal(t, tokens.ClassImage, tokens.Classify("", "", png),
		"a PNG arriving with no path must classify as an image, not binary")

	// The inserted rule must not shadow the PDF magic check that follows it.
	require.Equal(t, tokens.ClassPDF, tokens.Classify("", "", []byte("%PDF-1.4 x")))
}

// TestUnits_Deterministic asserts the unit scanner is a pure function of its bytes: the same input
// always yields the same count, on every platform and every call.
func TestUnits_Deterministic(t *testing.T) {
	src := []byte("func (e *exact) Estimate(b []byte, c Class) core.Tokens {\n" +
		"\traw := 0.0\n\tif raw == 0 {\n\t\traw = float64(units(b))\n\t}\n\treturn core.Tokens(raw)\n}\n")

	first := tokens.Units(src)
	require.Equal(t, first, tokens.Units(src), "units must be deterministic across calls")
	require.Greater(t, first, 0)

	// A fixed golden: the scanner's arithmetic is a wire-visible property (it feeds the persisted
	// chunk-token cache), so it is pinned rather than merely self-consistent.
	require.Equal(t, 65, first)
}

// TestUnits_MonotoneUnderAppend is the property the whole estimator rests on: appending bytes can
// never lower the unit count. SP-01's TestEstimate_MonotoneInLength drives this with RANDOM bytes,
// so the scanner has to stay monotone across malformed UTF-8 boundaries too.
func TestUnits_MonotoneUnderAppend(t *testing.T) {
	// A two-byte rune split across the boundary is the case a naive utf8.DecodeRune scanner gets
	// wrong: the lone lead byte decodes as RuneError (>= 0x0800, so "2 units") while the completed
	// rune is U+00E9 (< 0x0800, so "1 unit") — a decrease.
	cases := [][2][]byte{
		{{0xC3}, {0xC3, 0xA9}},                         // é
		{{0xE4, 0xB8}, {0xE4, 0xB8, 0xAD}},             // 中
		{{0xF0, 0x9F, 0x98}, {0xF0, 0x9F, 0x98, 0x80}}, // 😀
	}
	for _, c := range cases {
		require.LessOrEqual(t, tokens.Units(c[0]), tokens.Units(c[1]),
			"completing a multi-byte rune must never lower the unit count: %x -> %x", c[0], c[1])
	}
}

// TestEstimate_ProseVsCode replaces SP-01's byte-ratio assertion: the unit scanner, not a
// characters-per-token divisor, is what prices content now. Code still prices above prose (its
// unit weight is higher), and both stay in a sane band relative to the raw byte length.
func TestEstimate_ProseVsCode(t *testing.T) {
	est := newExact(t)
	payload := bytes.Repeat([]byte("a"), 4000)

	prose := est.Estimate(payload, tokens.ClassProse)
	code := est.Estimate(payload, tokens.ClassCode)

	require.Greater(t, code, prose, "code must price above prose for the same bytes")
	for name, got := range map[string]core.Tokens{"prose": prose, "code": code} {
		require.GreaterOrEqual(t, int(got), len(payload)/5, "%s estimate is implausibly low", name)
		require.LessOrEqual(t, int(got), len(payload)/2, "%s estimate is implausibly high", name)
	}
}

// TestEstimateRoot_CacheHit asserts a root whose chunks were all measured through NoteChunk is
// priced from the cache, with no byte re-scan and no miss counted.
func TestEstimateRoot_CacheHit(t *testing.T) {
	reg := obs.New(core.SystemClock())
	est := tokens.NewExactWithObs(config.Defaults(), "", "", nil, reg)
	sink := chunkSink(t, est)

	var refs []core.ChunkRef
	var want core.Tokens
	for i := 0; i < 8; i++ {
		body := bytes.Repeat([]byte("chunk body "), 40+i)
		h := core.HashBytes("tokens.test", body)
		want += sink.NoteChunk(h, tokens.ClassProse, body)
		refs = append(refs, core.ChunkRef{Hash: h, Len: len(body)})
	}

	require.Equal(t, want, est.EstimateRoot(context.Background(), refs, tokens.ClassProse),
		"EstimateRoot over cached chunks must equal the sum of the NoteChunk returns")
	require.Zero(t, reg.Counter("tokens.chunk_miss").Value())
}

// TestEstimateRoot_CacheMiss pins the miss path as byte-for-byte SP-01's baseline formula, which
// is what keeps SP-01's own TestEstimateRoot_SumsChunks green on an empty cache.
func TestEstimateRoot_CacheMiss(t *testing.T) {
	reg := obs.New(core.SystemClock())
	est := tokens.NewExactWithObs(config.Defaults(), "", "", nil, reg)

	var refs []core.ChunkRef
	for i := 0; i < 8; i++ {
		refs = append(refs, core.ChunkRef{Hash: core.HashBytes("tokens.miss", []byte{byte(i)}), Len: 4096})
	}

	// 8 * ceil(4096 / codeCharsPerToken 3.6) == 8 * 1138 == 9104
	require.Equal(t, core.Tokens(9104), est.EstimateRoot(context.Background(), refs, tokens.ClassCode))
	require.Equal(t, int64(8), reg.Counter("tokens.chunk_miss").Value())
}

// TestEstimateRoot_ClassIndependentCache proves the memo key is core.Hash ALONE, as SP-01 §10
// requires: a chunk measured under one class is reused under another, with the class weight
// applied at read time rather than baked into the cached value.
func TestEstimateRoot_ClassIndependentCache(t *testing.T) {
	reg := obs.New(core.SystemClock())
	est := tokens.NewExactWithObs(config.Defaults(), "", "", nil, reg)
	sink := chunkSink(t, est)

	body := bytes.Repeat([]byte("shared chunk body "), 32)
	h := core.HashBytes("tokens.classindep", body)
	sink.NoteChunk(h, tokens.ClassProse, body)

	got := est.EstimateRoot(context.Background(), []core.ChunkRef{{Hash: h, Len: len(body)}}, tokens.ClassCode)
	want := core.Tokens(math.Round(float64(tokens.Units(body)) * tokens.UnitWeight(tokens.ClassCode)))

	require.Equal(t, want, got, "a cached chunk must reprice under a different class")
	require.Zero(t, reg.Counter("tokens.chunk_miss").Value(), "the cached chunk must not count as a miss")
}

// TestEstimateRoot_SP01BaselineStillPasses restates SP-01's TestEstimateRoot_SumsChunks against
// the exact estimator, so a regression in the miss path is caught here with an explicit reason.
func TestEstimateRoot_SP01BaselineStillPasses(t *testing.T) {
	est := newExact(t)
	chunks := []core.ChunkRef{
		{Hash: core.HashBytes("test", []byte("chunk-1")), Len: 1000},
		{Hash: core.HashBytes("test", []byte("chunk-2")), Len: 1000},
		{Hash: core.HashBytes("test", []byte("chunk-3")), Len: 1000},
	}
	require.Equal(t, core.Tokens(750), est.EstimateRoot(context.Background(), chunks, tokens.ClassProse),
		"3 * ceil(1000/4.0): the cache-miss path is SP-01's baseline formula unchanged")
}

func BenchmarkEstimateRoot_64Cached(b *testing.B) {
	est := tokens.NewExact(config.Defaults(), "", "")
	sink := chunkSink(b, est)

	refs := make([]core.ChunkRef, 64)
	for i := range refs {
		body := bytes.Repeat([]byte("benchmark chunk body "), 20+i%7)
		h := core.HashBytes("tokens.bench", append([]byte{byte(i)}, body...))
		sink.NoteChunk(h, tokens.ClassCode, body)
		refs[i] = core.ChunkRef{Hash: h, Len: len(body)}
	}

	ctx := context.Background()
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_ = est.EstimateRoot(ctx, refs, tokens.ClassCode)
	}
}

func BenchmarkUnits_100KB(b *testing.B) {
	const want = 100 << 10
	line := []byte("func f(x int) int { return x*2 } // a line of ordinary source\n")
	payload := bytes.Repeat(line, want/len(line)+1)[:want]

	b.ReportAllocs()
	b.SetBytes(int64(len(payload)))
	b.ResetTimer()
	for i := 0; i < b.N; i++ {
		_ = tokens.Units(payload)
	}
}
