package cli

import (
	"context"
	"io/fs"
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/require"

	"github.com/qompack/qompack/internal/config"
	"github.com/qompack/qompack/internal/paths"
	"github.com/qompack/qompack/internal/store"
)

// v020StoreFixture is a store the public v0.2.0 release (tag v0.2.0, 71c46a2) wrote through its own
// hooks and daemon: a session with two prompts, a Read and a Bash tool use, a compaction and a
// SessionEnd, generated by plans/sdd/V6-closeout/w13-restore/runs/gen_store.py against a binary built
// from the tag. Only the directories a backup carries are kept (not logs/, metrics/, run/, tmp/).
// v0.2.0 writes no capture sidecars, no checkpoint and no draft: its build has no records/captures
// tree and no checkpoint writer.
const v020StoreFixture = "testdata/crossversion/v0.2.0/qompack-store"

// copyStoreFixture copies a committed store fixture into a fresh project's .qompack.
func copyStoreFixture(t *testing.T, src string) string {
	t.Helper()
	root := filepath.Join(t.TempDir(), "proj")
	dot := paths.Of(root).Dot
	require.NoError(t, filepath.WalkDir(src, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, rerr := filepath.Rel(src, p)
		if rerr != nil {
			return rerr
		}
		dst := filepath.Join(dot, rel)
		if d.IsDir() {
			return os.MkdirAll(paths.Long(dst), 0o700)
		}
		b, rerr := os.ReadFile(p)
		if rerr != nil {
			return rerr
		}
		return os.WriteFile(paths.Long(dst), b, 0o600)
	}))
	return root
}

// TestCrossVersion_AStoreTheV020ReleaseWroteReadsClean is the cross-version row the live lane could
// not run against the release that matters (D3: its "previous build" was dev build 301a8e9). A
// project a v0.2.0 user upgrades carries exactly this store, and the candidate must read it the way
// it reads its own: fsck clean, a backup that creates, verifies and restores with its integrity
// checks passing, and a startup publication audit with no gap (the daemon's LOUD line).
func TestCrossVersion_AStoreTheV020ReleaseWroteReadsClean(t *testing.T) {
	isolateUserGlobal(t)
	root := copyStoreFixture(t, v020StoreFixture)

	code, doc, errw := fsckJSON(t, root)
	checks, _ := doc["checks"].([]any)
	for _, c := range checks {
		row, _ := c.(map[string]any)
		require.Equal(t, true, row["ok"], "row %v on a v0.2.0 store: %s", row["id"], fsckDetail(row))
	}
	require.Equal(t, ExitOK, code, "stderr=%s", errw)

	s, err := store.OpenReadOnly(root, config.Defaults(), store.Deps{})
	require.NoError(t, err)
	auditor, ok := s.(store.PublicationAuditor)
	require.True(t, ok)
	audit, err := auditor.AuditPublication(context.Background(), store.DefaultPublicationScanCap())
	require.NoError(t, s.Close())
	require.NoError(t, err)
	require.False(t, audit.HasGaps(), "the startup accounting finds no publication gap: %+v", audit)
	require.False(t, audit.Incomplete, "and is complete: %+v", audit)

	for _, verb := range []string{"create", "verify"} {
		code, out, stderr := fsckDispatch(t, "backup", verb, "--project", root, "--id", "from-v020", "--json")
		require.Equal(t, ExitOK, code, "backup %s: %s %s", verb, out, stderr)
	}
	code, out, stderr := fsckDispatch(t, "backup", "restore", "--project", root, "--id", "from-v020",
		"--destination", filepath.Join(t.TempDir(), "recovered"), "--json")
	require.Equal(t, ExitOK, code, "restore of a v0.2.0 store's backup: %s %s", out, stderr)
}
