branch="marketplace/$TAG"
git switch -C "$branch" origin/develop
mkdir -p .claude-plugin
cp dist/generated/marketplace.json .claude-plugin/marketplace.json
if git diff --quiet -- .claude-plugin/marketplace.json && \
   git ls-files --error-unmatch .claude-plugin/marketplace.json >/dev/null 2>&1; then
  echo "develop already pins $TAG"
  exit 0
fi
git add .claude-plugin/marketplace.json
git -c user.name='github-actions[bot]' \
    -c user.email='41898282+github-actions[bot]@users.noreply.github.com' \
    commit -m "chore(marketplace): pin the $TAG release archives" \
    -m "Generated by devtool marketplace from the sha256 of each published zip, re-verified against the release's checksums.txt."
# An earlier run of this job may have pushed the branch already. Replace it only if it
# still points where this checkout saw it (empty: it must not exist yet).
expect="$(git rev-parse -q --verify "refs/remotes/origin/$branch" || true)"
git push --force-with-lease="refs/heads/$branch:$expect" origin "$branch"
open="$(gh pr list --head "$branch" --base develop --state open --json number --jq '.[0].number // empty')"
if [ -n "$open" ]; then
  echo "pull request #$open already proposes $branch; the push above updated it"
  exit 0
fi
gh pr create --base develop --head "$branch" \
  --title "chore(marketplace): pin the $TAG release archives" \
  --body "Pins the six per-target archive entries of .claude-plugin/marketplace.json to the $TAG release zips (sha256 re-verified against the release's checksums.txt, and equal to the uploaded marketplace.json). Merging it is what makes \`/plugin marketplace add AidanHT/qompack\` offer $TAG."
