package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/qompack/qompack/internal/commands"
	"github.com/qompack/qompack/internal/core"
	"github.com/qompack/qompack/internal/pluginmanifest"
)

// commandDocPath is the generated slash-command reference, relative to the repository root.
//
// It is generated from commands.Specs() for the same reason docs/mcp-tools.md is generated from
// mcp.ToolDefs: the help a user reads, the description installed into plugin/commands/*.md and the
// flags the binary actually accepts are one interface described in three places. A hand-written
// page is the one of the three nothing checks, so it becomes the wrong one.
//
// SP-14 owns this file; SP-18 links to it rather than restating it.
const commandDocPath = "docs/commands.md"

// taskGenCommandDocs renders docs/commands.md from commands.Specs(). With --check it diffs instead
// of writing, which is what the CI `docs` job runs.
func taskGenCommandDocs(args []string) error {
	fs := flag.NewFlagSet("gen-command-docs", flag.ContinueOnError)
	check := fs.Bool("check", false, "diff docs/commands.md against commands.Specs() instead of writing it")
	if err := fs.Parse(args); err != nil {
		return errors.Join(errUsage, err)
	}

	want, err := renderCommandDoc()
	if err != nil {
		return fmt.Errorf("gen-command-docs: %w", err)
	}

	p := filepath.Join(root, filepath.FromSlash(commandDocPath))

	if *check {
		got, readErr := os.ReadFile(p)
		if readErr != nil {
			return fmt.Errorf("gen-command-docs --check: %s is missing; run `devtool gen-command-docs`",
				commandDocPath)
		}
		if !bytes.Equal(want, normalizeNewlines(got)) {
			return fmt.Errorf("gen-command-docs --check: %s is stale; run `devtool gen-command-docs`",
				commandDocPath)
		}
		fmt.Printf("gen-command-docs: %s is up to date\n", commandDocPath)
		return nil
	}

	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(p, want, 0o644); err != nil { // #nosec G306 -- generated public documentation
		return err
	}
	fmt.Printf("gen-command-docs: wrote %s\n", commandDocPath)
	return nil
}

// renderCommandDoc builds the whole page.
//
// It cross-checks the two tables as it goes: every spec must correspond to an installed manifest
// entry with the same description, and vice versa. A generator that rendered whichever table it
// happened to read would document a surface the plugin does not install, which is worse than
// having no page — the page would be believed.
func renderCommandDoc() ([]byte, error) {
	installed := make(map[string]pluginmanifest.CommandDoc)
	for _, c := range pluginmanifest.Default(core.Version).Commands {
		installed[c.Name] = c
	}
	return renderCommandDocFrom(commands.Specs(), installed)
}

// renderCommandDocFrom is renderCommandDoc with both tables supplied, so the cross-check between
// them can be exercised with tables that disagree. Nothing in production calls it with anything
// but the real two.
func renderCommandDocFrom(specs []commands.Spec, installed map[string]pluginmanifest.CommandDoc) ([]byte, error) {
	if len(specs) != len(installed) {
		return nil, fmt.Errorf("%d command spec(s) but %d installed command(s)", len(specs), len(installed))
	}

	var b strings.Builder
	b.WriteString("# Slash commands\n\n")
	b.WriteString("<!-- Generated by `go run ./tools/devtool gen-command-docs`. Do not edit. -->\n\n")
	b.WriteString("Qompack installs six slash commands. Each one shells out to the `qompack`\n")
	b.WriteString("binary, so `/qompack:status` and `qompack status` are the same code and cannot\n")
	b.WriteString("drift apart.\n\n")
	b.WriteString("There is no checkpoint command. Qompack writes a checkpoint automatically before\n")
	b.WriteString("every compaction, and periodically during a session; a manual checkpoint is\n")
	b.WriteString("not offered yet ([cannot-do.md](cannot-do.md#no-manual-checkpoint-command)).\n\n")
	b.WriteString("Every command accepts `--json`, which emits a versioned envelope instead of text,\n")
	b.WriteString("and `--help`. Exit codes follow 00-ARCHITECTURE.md §2.3: `0` success, `2` a\n")
	b.WriteString("malformed invocation, `1` anything else.\n\n")
	b.WriteString("**A non-zero exit reaches you as the host's own error line.** A slash command runs\n")
	b.WriteString("`qompack` through Claude Code's `!` shell expansion. When it exits non-zero, Claude\n")
	b.WriteString("Code does not pass the command's output to the model: it shows only its own\n")
	b.WriteString("``Shell command failed for pattern \"!`qompack …`\": [stderr] …`` line, with stdout\n")
	b.WriteString("and stderr together under that label, and the turn ends without an answer\n")
	b.WriteString("(observed on Claude Code 2.1.280). `/qompack:eval` in a project with no evaluation\n")
	b.WriteString("artifacts, and `/qompack:recall` with no query, look like that. Run the same\n")
	b.WriteString("`qompack` command in a terminal to see its full message and exit code.\n\n")

	b.WriteString("| Command | Subcommand | Arguments | Description |\n")
	b.WriteString("|---|---|---|---|\n")
	for _, s := range specs {
		b.WriteString(fmt.Sprintf("| `/qompack:%s` | `qompack %s` | %s | %s |\n",
			s.Name, s.Subcommand, codeOrDash(s.ArgumentHint), s.Summary))
	}
	b.WriteString("\n")

	for _, s := range specs {
		doc, ok := installed[s.Name]
		if !ok {
			return nil, fmt.Errorf("command %q is not installed by the manifest", s.Name)
		}
		if doc.Description != s.Summary {
			return nil, fmt.Errorf("command %q: help says %q, the manifest installs %q",
				s.Name, s.Summary, doc.Description)
		}

		b.WriteString(fmt.Sprintf("## `/qompack:%s`\n\n", s.Name))
		b.WriteString(s.Summary + "\n\n")
		b.WriteString("```\n")
		var help strings.Builder
		if err := s.WriteHelp(&help); err != nil {
			return nil, fmt.Errorf("rendering help for %q: %w", s.Name, err)
		}
		b.WriteString(help.String())
		b.WriteString("```\n\n")
		b.WriteString(fmt.Sprintf("Allowed tools: `%s`\n\n", doc.AllowedTools))
	}

	return normalizeNewlines([]byte(b.String())), nil
}

// codeOrDash renders an argument hint as inline code, or an em dash when there is none.
func codeOrDash(s string) string {
	if s == "" {
		return "—"
	}
	return "`" + s + "`"
}
