package main

import (
	"fmt"
	"strings"
)

// renderNotices builds THIRD_PARTY_NOTICES.md. It is a pure function over already-collected
// inputs so the page's shape can be asserted without a module cache, a network or a toolchain.
//
// The page answers two different questions and says which is which. What is REDISTRIBUTED is
// reproduced in full, because that is what the licences require. What is merely DEPENDED ON at
// build or test time is listed with its identifier and an explicit statement that it is not in the
// binary — the honest version of a notices file names its own boundary rather than leaving a
// reader to assume every entry in go.mod ships.
func renderNotices(projectLicense string, shipped []licenseModule, tooling []toolingRow) string {
	var b strings.Builder

	b.WriteString("# Third-party notices\n\n")
	b.WriteString("Generated by `go run ./tools/devtool licenses --write`. Do not edit by hand:\n")
	b.WriteString("`devtool licenses --check` regenerates this page in memory and fails on any drift,\n")
	b.WriteString("and `devtool release-check` runs that check before a release.\n\n")
	b.WriteString("The modules in §2 are the ones `go list -deps ./cmd/qompack` reaches on at least one of\n")
	b.WriteString("the six release targets, intersected with the allow-list `devtool lint --only=bindeps`\n")
	b.WriteString("enforces (00-ARCHITECTURE.md §2.5). Their licence texts are reproduced in full because\n")
	b.WriteString("the released binary is a derived work that carries their code. §3 lists the remaining\n")
	b.WriteString("direct dependencies, which are build-time or test-time only and reach no released byte.\n\n")

	b.WriteString("## 1. Qompack\n\n")
	b.WriteString("Qompack itself is MIT-licensed. The full text, as it appears in `LICENSE`:\n\n")
	writeIndented(&b, projectLicense)

	b.WriteString("\n## 2. Redistributed dependencies\n\n")
	if len(shipped) == 0 {
		b.WriteString("None: the binary links no third-party module.\n")
	} else {
		b.WriteString("| module | version | licence |\n| --- | --- | --- |\n")
		for _, m := range shipped {
			fmt.Fprintf(&b, "| `%s` | `%s` | %s |\n", m.Path, m.Version, m.ID)
		}
		b.WriteString("\n")
		for _, m := range shipped {
			fmt.Fprintf(&b, "### %s %s\n\n", m.Path, m.Version)
			fmt.Fprintf(&b, "Licence: %s\n\n", m.ID)
			for _, t := range m.Texts {
				fmt.Fprintf(&b, "Reproduced from `%s`:\n\n", t.Rel)
				writeIndented(&b, t.Body)
			}
		}
	}

	b.WriteString("## 3. Build- and test-time dependencies, not redistributed\n\n")
	b.WriteString("These are direct requirements of `go.mod` that no released binary links. The claim is\n")
	b.WriteString("checked, not asserted: `devtool lint --only=bindeps` runs `go list -deps ./cmd/qompack`\n")
	b.WriteString("on all six release targets and fails on any module outside §2's allow-list.\n\n")
	b.WriteString("| module | version | licence | status |\n| --- | --- | --- | --- |\n")
	for _, r := range tooling {
		fmt.Fprintf(&b, "| `%s` | `%s` | %s | %s |\n", r.Path, r.Version, r.ID, r.Note)
	}
	b.WriteString("\nThe Go standard library ships with the Go toolchain and is not redistributed by this\n")
	b.WriteString("repository; it is covered by the Go project's own BSD-3-Clause licence.\n")

	return b.String()
}

// writeIndented emits a licence body as an indented block, then a blank line.
//
// Four-space indentation rather than a fenced block: a licence text can itself contain a line of
// backticks, and a fence that a licence body closed early would spill the rest of the text into
// the document as Markdown. Indentation has no terminator to collide with.
func writeIndented(b *strings.Builder, body string) {
	for _, line := range strings.Split(strings.TrimRight(body, "\n"), "\n") {
		if strings.TrimSpace(line) == "" {
			b.WriteString("\n")
			continue
		}
		b.WriteString("    " + strings.TrimRight(line, " \t") + "\n")
	}
	b.WriteString("\n")
}
