// Phase 4 live lane. Launch right after the candidate is frozen, replacing ONLY __CANDIDATE__ (the
// frozen commit) and __BUNDLE__ (the frozen windows/amd64 bundle directory, holding BUNDLE.json).
// Before launch: merge closeout/w7-livelane into the candidate (the lane uses homeguard.py and
// live_driver.py beside this file) and create worktree ../qompack-cx-live (branch closeout/live)
// at the candidate. Parts run strictly one after another; a failed real-home guard stops the lane.
export const meta = {
  name: 'v6-closeout-live-uat',
  description: 'Phase 4: agent-run UAT-01..12, C4.1-C4.11, C1.6/C1.7 and C5.6 on the frozen candidate, sequential real sessions, then an evidence audit',
  phases: [
    { title: 'Install', detail: 'C4.1 isolated-profile + local-scope marketplace install, UAT-01, C4.8 upgrade/uninstall/reinstall, C4.6/UAT-12 privacy and lifecycle' },
    { title: 'Sessions', detail: 'UAT-02..06: C4.2 capture, C4.3 compaction round trip, C4.9 degraded paths' },
    { title: 'Retrieval', detail: 'UAT-07..11: C4.4 every MCP tool, C4.5 slash commands, C4.7 kill switches' },
    { title: 'Recovery', detail: 'C1.6 startup accounting + fsck, C1.7 backup/verify/restore rehearsal, C5.6 resource summary, C4.11 platforms' },
    { title: 'Audit', detail: 'independent read-only audit of every Result block and coverage row against its evidence' },
  ],
}

const ROOT = 'C:/Users/Quant/Documents/Programming/Projects'
const WT = `${ROOT}/qompack-cx-live`
const CAND = '__CANDIDATE__'
const BUNDLE = '__BUNDLE__'
if (CAND.startsWith('__') || BUNDLE.startsWith('__')) throw new Error('live-uat.js: replace __CANDIDATE__ and __BUNDLE__ before launch')

const LIVE = 'plans/sdd/V6-closeout/live'
const TOOLS = 'plans/sdd/V6-closeout/coordinator'
const SCRATCH = 'C:/Users/Quant/AppData/Local/Temp/claude/qompack-live'

const COMMON = (key, part, budget) => `You are the V6 close-out LIVE lane for Qompack (a Go Claude Code plugin: seven hooks -> resident per-project daemon -> content-addressed store under <project>/.qompack/, an MCP retrieval server "qompack mcp" with eight tools, seven /qompack: slash commands). You run REAL headless Claude Code sessions on the owner's own Windows machine to prove the plugin works as installed. Owner decision D3: these runs are AGENT-EXECUTED on the real installed host, never human UAT; every record says so.

WORKTREE: ${WT} (branch closeout/live at the frozen candidate ${CAND}). The Bash tool resets cwd: prefix commands with \`cd ${WT} &&\`. Frozen bundle (do not rebuild it): ${BUNDLE}; its CLI is ${BUNDLE}/bin/qompack.exe — use that binary for every qompack command, never a build from source. Scratch root for this part: ${SCRATCH}/${key}/ (outside every git repository; one disposable project per scenario beneath it). Coordinator ledger (read, do not edit): ${ROOT}/qompack-v6/plans/V6-CLOSEOUT-CHECKLIST.md (owner decisions D1-D32). Read docs/uat.md, docs/install.md, docs/backup.md, docs/commands.md, docs/mcp-tools.md, docs/user-guide.md, docs/release.md §4 and docs/troubleshooting.md first. Tooling (committed; if either file is missing, stop and return blocked): ${TOOLS}/homeguard.py (real-home guard: snap / check / clean, self-test homeguard_test.py) and ${TOOLS}/live_driver.py (stream-json session driver: one user message per turn after the previous result; per-turn "before" argv for degraded steps; writes stream.jsonl, stderr.txt, meta.json with daemon RSS/CPU and .qompack/ byte samples, hooks.json with host-seen hook arrival deltas; "secrets_file" scrubs planted secrets from every output; \`live_driver.py scan-staged <repo> <secrets.json>\` is the pre-commit secret gate; self-test live_driver_test.py). Run both self-tests once before your first session. References: plans/sdd/V6-closeout/eval/runs/marketplace-rehearsal.md (the local-marketplace flow and what it leaves behind) and tools/devtool/liveeval_host.go (marketplaceInstall, stopTrialDaemon, readTranscript).

YOUR PART (${key}): ${part}

HOST FACTS (Claude Code 2.1.280; checked against its own --help and the committed C5.4 smoke/pilot streams):
- Session command: \`claude -p --input-format stream-json --output-format stream-json --verbose --include-hook-events --model claude-haiku-4-5-20251001 --max-turns <n> --setting-sources project,local --permission-mode dontAsk --allowedTools <comma list>\` plus \`--plugin-dir <bundle>\` where the part says so; env ENABLE_CLAUDEAI_MCP_SERVERS=false. --max-turns is not listed by --help but 2.1.280 accepted it in every smoke/pilot run. Never pass --bare (it skips hooks) or --no-session-persistence (the transcript is evidence). With -p, "Settings files that fail validation are silently ignored": prove any project settings you write took effect before relying on them.
- Tool names: plugin MCP tools are mcp__plugin_qompack_qompack__<tool> and the server is "plugin:qompack:qompack"; the slash commands are /qompack:checkpoint, dropped, eval, pin, recall, status, why (read both from the stream's system/init event: tools, mcp_servers, slash_commands, plugins). In dontAsk mode a tool not in --allowedTools is denied, so list the MCP tools and the commands' Bash(qompack <cmd>:*) rules explicitly. Each command body runs \`qompack <cmd>\` through Bash: whether the host resolves \`qompack\` on PATH is part of what C4.5 observes — record it, do not pre-fix PATH on the first attempt.
- Hook events arrive as system/hook_started and system/hook_response (hook_name like "SessionStart:compact", outcome, exit_code); they carry NO duration field, so the only host-side latency is the stream arrival delta in live_driver.py's hooks.json — approximate, and it can UNDER-read when the host batches output (the SessionStart:startup pair arrives before the init event, after the hook ran). Pairs marked "measured": false (before init, or within 5 ms) are reported as not measured, never as ~0 ms. SessionEnd trouble shows only on stderr ("SessionEnd hook [...] failed: Hook cancelled").
- Compaction: a user turn whose content is "/compact" compacts headlessly and yields a result; automatic compaction is forced with env CLAUDE_CODE_AUTO_COMPACT_WINDOW=100000 and CLAUDE_AUTOCOMPACT_PCT_OVERRIDE=30 (smoke3; --autocompact <tokens> is the documented flag for the window, 100k minimum, unrehearsed). A PreCompact hook rejection is only visible on a "/compact" turn. Resume and fork: --resume <session-id> [--fork-session] (each is a new session for the budget).
- Plugin CLI (no model call): \`claude plugin marketplace add <dir> --scope user|project|local\`, \`claude plugin marketplace update <name>\`, \`claude plugin marketplace remove <name>\` (no --scope removes it from every scope), \`claude plugin marketplace list --json\`, \`claude plugin install <plugin>@<mkt> -s user|project|local [-y] [--json]\`, \`claude plugin update <plugin>@<mkt> -s <scope> [-y] [--json]\`, \`claude plugin uninstall <plugin>@<mkt> -s <scope> [-y] [--keep-data] [--json]\` (without --keep-data it removes ~/.claude/plugins/data/<id>/), \`claude plugin list --json\`, \`claude plugin details <plugin>\` (component inventory), \`claude plugin validate <dir> --strict --json\`. 2.1.280 accepts --json on install/update/uninstall, which docs/install.md §3 says it does not (written on 2.1.263): record that as a documentation finding. \`marketplace add --scope local\` still rewrites the global plugins/known_marketplaces.json until \`marketplace remove\`, and remove leaves plugins/cache/<mkt>/qompack/<version>/ marked .orphaned_at: delete that directory only when your run created it and every version in it is one of your bundles (compare BUNDLE.json), per commit 09a5222.
- Authentication: a disposable CLAUDE_CONFIG_DIR has no login and credentials must never be copied, so plugin CLI steps may use an isolated CLAUDE_CONFIG_DIR=<scratch>/profile, but model sessions run on the operator's real profile with the plugin either --plugin-dir or installed at --scope local inside the disposable project. Real sessions also write the host's own ~/.claude/projects/<slug>/<id>.jsonl transcript and ~/.claude.json; read only your own sessions' transcripts (by session id), commit only extracted facts without message bodies (transcript-facts.json, as liveeval does), never the raw transcript.
- ~/.qompack is resolved from the home directory (USERPROFILE), so real sessions write the real ~/.qompack: logs/ and, per D10, staged daemon copies bin/<sha256>/qompack.exe. QOMPACK_HOME only moves calibration.json. Set QOMPACK_HOME=<scratch>/qhome on every session and CLI step except where a row's preconditions forbid QOMPACK_* variables (UAT-01). homeguard.py lists ~/.qompack by name: record what your run added, never delete anything that existed at snap time, and remove a staged copy only after install.md §6's uninstall step and only if homeguard reports it as gained and its sha256 equals a bundle binary you used.

HARD RULES (owner directives):
- Real-home guard: \`python ${TOOLS}/homeguard.py snap ${SCRATCH}/${key}/guard.json\` before your first session or plugin command; after EVERY session and every plugin CLI step run \`homeguard.py clean\` then \`homeguard.py check\` on that file and append the check output to ${LIVE}/guard/${key}.txt (commit it; never commit guard.json, it lists the operator's plugins). During a local-scope install the marketplace/installed-plugin JSON legitimately differ until uninstall + marketplace remove; outside that window, and at the end of the part, check must pass. A failure you cannot trace to your own run's still-open install window means STOP: restore only what your run changed, report guard_ok false. NEVER install at user scope in the real profile, never edit ~/.claude/settings.json, never open credential files (.credentials.json or similar).
- Session budget for this part: at most ${budget} real sessions (a session = one claude process that talks to the model), counting failed ones, resumes and forks. Append one line per session to ${LIVE}/sessions.tsv (part, n, scenario, evidence dir, model, exit, wall_s). Model claude-haiku-4-5-20251001; use claude-sonnet-5 only when a step genuinely needs it, and say why.
- Daemons: terminate only a daemon your scenario started, identified by its project path in <project>/.qompack/run/daemon.lock AND process image qompack.exe; prefer the idle exit (QOMPACK_RUNTIME__DAEMON__IDLEEXITSECONDS=30 where the row's preconditions allow a non-default). Never kill a process you did not start. No load generators; no \`go test ./...\`.
- No git push/tag/merge/rebase/reset; commit only in ${WT}. Conventional commits (\`docs(uat): ...\`, \`test(live): ...\`), lowercase scope, subject <=64 chars, body lines <=100, NO attribution trailers (no Co-Authored-By, Claude-Session, "Generated with").
- Evidence under ${LIVE}/ (uat/UAT-NN/, c4/C4.N/, recovery/C1.N/, resources/C5.6/): driver outputs, command outputs with exit codes, .qompack/ listings, status/doctor/fsck/self-test outputs, guard results. Keep failures exactly like passes. Scrub only the scratch prefix (live_driver.py's "scrub": "${SCRATCH}") AND planted secrets, mechanically: build every planted credential-shaped string at run time from split parts and write the list ONLY to ${SCRATCH}/${key}/secrets.json (never into a committed file or a command transcript you commit); pass "secrets_file" to live_driver.py on EVERY session of a scenario that plants secrets, so its outputs carry @@SEC_PLANTED_<n>@@ instead; copy any other output (CLI responses, greps, listings, store files) into ${LIVE}/ only through a filter that applies the same replacement; record each secret's sha256 in the evidence. HARD STEP before every commit while a secrets.json exists: \`git add\` the evidence, then \`python ${TOOLS}/live_driver.py scan-staged ${WT} ${SCRATCH}/${key}/secrets.json\`; on exit 1 unstage the named files (\`git restore --staged <path>\`), scrub them and scan again; commit only on exit 0 (the repo is public, push protection blocks credential shapes, and history cannot be rewritten). Raw copies stay in scratch.
- Fill each scenario's Result block in docs/uat.md from what you observed: Result pass|fail|skipped — <reason>; Snapshot: \`qompack version\` output, bundle BUNDLE.json sha256, commit ${CAND}, Windows 11 build, Claude Code 2.1.280; Date 2026-..-.. (America/Toronto); Executed by: "Claude Code workflow subagent (Opus 5.5), agent-executed on the owner's real host per owner decision D3 — not human UAT"; Evidence path; Rollback verified per the doc's rule. Read each expected-result block field by field. A result that differs from the doc is a FINDING: record it, never edit the expectation to match. If a product defect blocks a step, record the step, stop that scenario, report the defect with evidence (the coordinator routes fixes).
- Do not change product code or tests. Documentation edits are limited to Result blocks and to recording observed strings the doc marks "to be confirmed at execution".
- Subagents cannot write report.md files: return your full report as your result (per scenario and checklist item: result, sessions used, evidence path, findings with evidence; guard results; open issues); the coordinator commits it.`

const RESULT = { type: 'object', properties: {
  status: { type: 'string', enum: ['done', 'partial', 'blocked'] }, head: { type: 'string' },
  commits: { type: 'array', items: { type: 'string' } }, sessions_used: { type: 'number' },
  scenarios: { type: 'array', items: { type: 'object', properties: {
    id: { type: 'string' }, result: { type: 'string' }, evidence: { type: 'string' }, findings: { type: 'array', items: { type: 'string' } },
  }, required: ['id', 'result', 'evidence', 'findings'] } },
  summary: { type: 'string' }, defects: { type: 'array', items: { type: 'string' } },
  guard: { type: 'string' }, guard_ok: { type: 'boolean' }, open_issues: { type: 'array', items: { type: 'string' } },
}, required: ['status', 'head', 'commits', 'sessions_used', 'scenarios', 'summary', 'defects', 'guard', 'guard_ok', 'open_issues'] }

const PARTS = [
  { key: 'install', phase: 'Install', budget: 8, part: `Scenario ids to return: C4.1, UAT-01, C4.8, C4.6, UAT-12.
(1) C4.1, no session, evidence ${LIVE}/c4/C4.1/: build a disposable local marketplace around a copy of the frozen bundle (marketplaceInstall's marketplace.json shape; name qompack-live), then with CLAUDE_CONFIG_DIR=${SCRATCH}/install/profile (a fresh, isolated profile): marketplace add (scope user inside that profile), install qompack@qompack-live -s user --json, plugin list --json, marketplace list --json, plugin details qompack, and validate --strict --json on the installed cache copy. Record the hooks, MCP server and seven commands the host lists; guard check after (the real home must be untouched). Delete the isolated profile afterwards.
(2) UAT-01 (1 session), evidence ${LIVE}/uat/UAT-01/: in a fresh disposable project, the real-profile LOCAL-scope marketplace flow (marketplace add --scope local, install -s local), then one short session with no QOMPACK_* variables whose init event proves hooks (hook_started for SessionStart/UserPromptSubmit/Stop at least), the connected qompack MCP server with its eight tools and the seven commands were discovered from the installed copy; then UAT-01 steps 2-8 with the bundle CLI. Uninstall -s local, marketplace remove, orphan cleanup, guard check.
(3) C4.8 + C4.6 + UAT-12 (at most 5 sessions), evidence ${LIVE}/c4/C4.8/, ${LIVE}/c4/C4.6/, ${LIVE}/uat/UAT-12/: the previous build is local develop 301a8e9 (the pre-close-out V6 integration; no tag carries the bundle tool): \`git -C ${WT} worktree add --detach ${SCRATCH}/install/prev 301a8e9\`, then \`go run ./tools/devtool bundle --target windows/amd64 --version 0.2.99-prev --out ${SCRATCH}/install/old\` there. 301a8e9 has NO \`qompack backup\` command (it arrived in 4a12eff), so every backup/verify/restore uses the frozen bundle's CLI against the store the old build wrote, with that store's daemon stopped. In one disposable project: record initial absence (UAT-12 step 1); plant two credential-shaped fake secrets in a project file plus a file to be deny-ruled, a file larger than runtime.mcp.maxResponseBytes (262144) and a binary file; install the OLD bundle through the local marketplace at -s local; session A reads all of them (captures them); stop the daemon; frozen-CLI backup create + verify (the non-vacuous baseline); add a PROJECT-scope .claude/settings.json deny rule Read(<that file>) (never the user's settings) and prove the host itself now refuses a direct Read; upgrade per install.md §5 (point the marketplace at the frozen bundle, marketplace update, plugin update qompack@qompack-live -s local); session B: the denied file through Read, recall, expand, re_read, /qompack:recall and the bundle CLI (\`qompack recall\`/\`expand\` if present), an out-of-project path through re_read and expand, expand on the oversized capture with and without full:true, expand on the binary capture, with every response size recorded (UAT-12 steps 2-7); read the day log for version-block and retired-meaning warnings; stop the daemon; restore the baseline into a fresh destination, fsck it (certified) and keep the source's later writes; uninstall (-s local, no --keep-data), confirm .qompack/ survives, reinstall the frozen bundle, session C proves the project work is preserved (recall finds session A's capture) and fsck is clean; final uninstall, marketplace remove, orphan cleanup, staged-copy cleanup per the host-facts rule, \`git -C ${WT} worktree remove ${SCRATCH}/install/prev\`. C4.6: grep every durable Qompack surface (the project .qompack/ including checkpoints and captures, the run's ~/.qompack/logs files, every rehydration payload and MCP response in the streams) for each planted secret and for its sha256-matching fragments; any hit is a fail. The host's own transcript is the host's surface: record whether the secret is there, but it is not a Qompack surface.` },
  { key: 'sessions', phase: 'Sessions', budget: 12, part: `Scenario ids to return: UAT-02, UAT-03, UAT-04, UAT-05, UAT-06, C4.2, C4.3, C4.9. Every session uses --plugin-dir ${BUNDLE}; one disposable project per scenario; evidence ${LIVE}/uat/UAT-NN/ and ${LIVE}/c4/C4.9/.
C4.2 (in UAT-02, 1-2 sessions): every hook event captured — SessionStart, UserPromptSubmit, PostToolUse, Stop, SubagentStop (have the model run one subagent task; take the subagent tool's name from the init event and allow it), PreCompact, SessionEnd — from hooks.json and the store; the .qompack/ index counts (captures, prompts, sessions) match the counts in the host transcript; \`qompack status\`, \`doctor --json\` and \`fsck --json\` clean.
C4.3 (UAT-03/04/05, about 5 sessions): the real compaction round trip — PreCompact writes the checkpoint, SessionStart:compact injects the rehydration block with additionalContext under the host's 10,000-character cap (D5: ~9,500 including the wrapper, overflow named with pointers), and the model recovers a pre-compaction fact it cannot re-read; both a "/compact" turn and a forced automatic compaction; no PreCompact output rejection (C1.12) and no "Hook cancelled" for SessionEnd on stderr (C1.15/D13). UAT-03's daemon-gone-and-back step and UAT-04's failed-compaction step per the doc.
UAT-06 (3 sessions): compact, --resume, --resume --fork-session, and a correction; no superseded intent promoted.
C4.9 (2-3 sessions, evidence ${LIVE}/c4/C4.9/): use live_driver.py "before" steps to (a) end the scenario's own daemon mid-session (lock path + qompack.exe image checked by the step itself), (b) present an artifact with an unknown schema version as troubleshooting.md describes, (c) make a referenced object unavailable in a disposable copy; each time the host session must continue (next turn succeeds, hooks exit 0 or degrade as documented, fsck/status explain it).` },
  { key: 'retrieval', phase: 'Retrieval', budget: 12, part: `Scenario ids to return: UAT-07, UAT-08, UAT-09, UAT-10, UAT-11, C4.4, C4.5, C4.7. Every session uses --plugin-dir ${BUNDLE}; one disposable project per scenario; evidence ${LIVE}/uat/UAT-NN/, ${LIVE}/c4/C4.4/, ${LIVE}/c4/C4.5/, ${LIVE}/c4/C4.7/.
C4.4: the real model calls each MCP tool — recall, expand, re_read, already_tried, record_eliminated, timeline, why, dropped — and gets correct results AND correct errors (bad handle, unknown path, malformed query); write ${LIVE}/c4/C4.4/tool-matrix.md (tool, success call, error call, stream line refs, verdict against docs/mcp-tools.md).
C4.5 (1-2 sessions): run all seven /qompack: commands in a real session and compare each output with docs/commands.md (${LIVE}/c4/C4.5/commands-vs-docs.md); record whether \`qompack\` resolved on the command's PATH (host facts).
C4.7 (2 sessions): recording off (runtime.mode "off") and reinjection off (runtime.migration.reinjection.sessionStartCompact false), each set alone in the PROJECT config (.qompack/config.json per docs/config-reference.md), each proved independent of the other in a real session (off: hooks exit 0, nothing recorded, no daemon; reinjection off: compaction still checkpoints and tool events are still recorded, no injected span).
UAT-10's usage categories and UAT-11 (admission off, as shipped) per the doc.` },
  { key: 'recovery', phase: 'Recovery', budget: 4, part: `Scenario ids to return: C1.6, C1.7, C5.6, C4.11. Every session uses --plugin-dir ${BUNDLE}.
C1.6 (1 session, evidence ${LIVE}/recovery/C1.6/): seed a disposable project with one real session, let its daemon exit, then inject the two publication gaps the fault suite pins, following test/fault/publication_test.go (object_written_index_line_absent: drop one roots.jsonl line whose object exists) and test/fault/v6_fsck_test.go (v6UnpublishToolCapture: return a published observe.tool capture to stage one); fingerprint objects/ and every sidecar; restart the daemon the way TestV6_StartupAccountingReportsUnpublishedCaptureViaStatus does (a bare session-start through the bundle CLI); record \`status --json\` (publication counters, loud_tail naming "unindexed"/"unpublished"), LOUD.log and \`fsck --project <root> --json\` (must exit non-zero and name both); re-fingerprint. State honestly: automatic startup accounting and fsck detection exist or not, and whether anything was automatically RECOVERED (docs/backup.md says it discovers and does not reconstruct; an unchanged fingerprint means no automatic recovery).
C1.7 (2 sessions, evidence ${LIVE}/recovery/C1.7/): the operator path through the shipped CLI on the packaged bundle, per docs/backup.md. Seed a project (session 1), let the daemon exit, backup create --id before + verify. Pre-new-write rollback: restore "before" into fresh destination D1 before any new write; fsck D1; reader proof. Post-new-write rollback: session 2 writes more; daemon exits; restore "before" into fresh D2; show D2 holds the backup frontier and not the later writes, the source keeps them (fsck source), and restore into an existing destination and backup against a live daemon are both refused (start the daemon with a hook entry point for the second, then let it exit). Record every JSON response and exit code.
C5.6 (no session, evidence ${LIVE}/resources/C5.6/summary.md): aggregate from every part's evidence (meta.json and hooks.json under ${LIVE}/): store growth per session (store_bytes_before/after), daemon working set / peak working set / CPU seconds, host-seen hook latency per hook event (n, median, p95, max), plus the sessions.tsv totals. Report numbers only; propose no budget.
C4.11 (no session, evidence ${LIVE}/c4/C4.11/): windows/amd64 is the host this lane ran on. Linux: only if \`docker exec qompack-v6-linux-verification true\` already succeeds (never start Docker) AND a Linux \`claude\` is present in that container, run the no-model half there (validate --strict, isolated-profile marketplace add/install, plugin list --json) with the frozen linux/amd64 bundle if the coordinator built one; real Linux sessions need a login the container does not have, so record them unknown with that reason. macOS and windows/arm64: unknown (no runner).` },
]

const results = []
for (const p of PARTS) {
  const r = await agent(COMMON(p.key, p.part, p.budget), { label: `live:${p.key}`, phase: p.phase, schema: RESULT, effort: 'high' })
  results.push({ key: p.key, budget: p.budget, r })
  if (!r || r.guard_ok === false) break
}

const AUDIT = { type: 'object', properties: {
  verdict: { type: 'string', enum: ['sound', 'needs-fixes', 'unsound'] },
  coverage: { type: 'array', items: { type: 'object', properties: {
    item: { type: 'string' }, status: { type: 'string', enum: ['evidenced', 'partial', 'missing', 'failed'] }, evidence: { type: 'string' },
  }, required: ['item', 'status', 'evidence'] } },
  findings: { type: 'array', items: { type: 'object', properties: {
    severity: { type: 'string', enum: ['blocker', 'major', 'minor', 'nit'] }, location: { type: 'string' },
    issue: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' },
  }, required: ['severity', 'location', 'issue', 'evidence', 'fix'] } },
}, required: ['verdict', 'coverage', 'findings'] }

const audit = await agent(`You are an independent, adversarial auditor of the Qompack V6 live UAT lane. Worktree ${WT}, branch closeout/live, candidate ${CAND}, bundle ${BUNDLE}. READ-ONLY: never edit, commit, run claude sessions, touch ~/.claude or ~/.qompack, or kill processes. The live parts returned: ${JSON.stringify(results.map((x) => ({ key: x.key, budget: x.budget, status: x.r && x.r.status, sessions_used: x.r && x.r.sessions_used, scenarios: x.r && x.r.scenarios, defects: x.r && x.r.defects, guard: x.r && x.r.guard, guard_ok: x.r && x.r.guard_ok })))}.
Coverage: for each of C4.1, C4.2, C4.3, C4.4, C4.5, C4.6, C4.7, C4.8, C4.9, C4.10, C4.11, C1.6, C1.7, C5.6 (wording in ${ROOT}/qompack-v6/plans/V6-CLOSEOUT-CHECKLIST.md) name the evidence under ${LIVE}/ that proves it and mark it evidenced, partial, missing or failed; a part that never ran leaves its items missing.
For every UAT-01..12 Result block in docs/uat.md: does the cited evidence exist and show what the block claims, field by field against the scenario's expected-result block? Is every deviation recorded as a finding rather than papered over, and no expectation edited? Is "Executed by" honest (agent-executed per D3, not human UAT)? C1.6: is "automatic recovery" stated honestly? Budgets: count claude processes (meta.json files, sessions.tsv) per part against its budget. Guard: does ${LIVE}/guard/*.txt show a passing check after every session and at each part's end? Secrets: search committed evidence for credential shapes, planted secrets (only @@SEC_PLANTED_n@@ may appear), raw transcripts, guard.json, credential files. Commit hygiene: \`git -C ${WT} log ${CAND}..HEAD\` has conventional subjects and no attribution trailers. Return the coverage table and findings with file:line and evidence.`,
  { label: 'audit:live', phase: 'Audit', schema: AUDIT, effort: 'high' })

return { results, audit }
