export const meta = {
  name: 'v6-closeout-prep7',
  description: 'Alongside wave 7: finish the Phase 4 live-lane script (no real sessions) and make the docs match the integrated code; each reviewed',
  phases: [
    { title: 'Prepare', detail: 'live-lane script; docs-vs-code consistency' },
    { title: 'Review', detail: 'independent review' },
    { title: 'Fix', detail: 'resolve non-nit findings' },
  ],
}
const ROOT = 'C:/Users/Quant/Documents/Programming/Projects'
const V6 = `${ROOT}/qompack-v6`
const SCRATCH = 'C:/Users/Quant/AppData/Local/Temp/claude/C--Users-Quant-Documents-Programming-Projects-qompack/9c57653d-e5ff-4791-8ab4-ad49457994c1/scratchpad/w7'
const RULES = `Hard rules (owner directives): never weaken a check; commits are conventional \`type(scope): subject\` (lowercase scope, subject <=64 chars, body lines <=100) with NO attribution trailers (no Co-Authored-By, Claude-Session, "Generated with"); never push, tag, merge, rebase or reset branches, change git config/hooks, or SendMessage anyone; never kill a process you did not start; never read or modify the real ~/.qompack or ~/.claude (settings, installed_plugins.json, known_marketplaces.json, credentials); NO real Claude Code sessions (no \`claude -p\`, nothing that talks to the model) — \`claude --help\`, \`claude <sub> --help\`, \`claude --version\` and \`claude plugin validate <dir>\` are allowed. CPU: the owner uses this laptop; keep test runs focused, never ./..., no load generators. Scratch files under ${SCRATCH}/<your-seat>/. Subagents cannot write report.md: return your full report as your result. Owner decisions D1-D32 are in ${V6}/plans/V6-CLOSEOUT-CHECKLIST.md (read it; do not edit it).`
const SEATS = [
  { key: 'livelane', effort: 'high', reviewEffort: 'high', wt: `${ROOT}/qompack-cx-w7-livelane`, task: `SEAT livelane. Worktree ${ROOT}/qompack-cx-w7-livelane (branch closeout/w7-livelane, cut from verify/v6; the Bash tool resets cwd, so prefix commands with \`cd ${ROOT}/qompack-cx-w7-livelane &&\`; commit only plans/sdd/V6-closeout/coordinator/live-uat.js and files you add beside it). Integrated candidate code to read: ${ROOT}/qompack-cx-int (closeout/integration; read-only for you).
Finish the DRAFT Phase 4 live-lane workflow plans/sdd/V6-closeout/coordinator/live-uat.js (in your worktree) so that the coordinator can launch it right after the candidate is frozen, replacing only __CANDIDATE__ and __BUNDLE__. It must cover, with an evidence path per item: checklist C4.1-C4.11 (install through the real marketplace flow into an isolated profile, hooks/MCP/commands discovered; real headless sessions and index counts; real compaction round trip; every MCP tool used by the real model; slash commands vs docs/commands.md; privacy with planted secrets and deny-ruled/out-of-project reads refused by every retrieval form; kill switches; upgrade/uninstall/reinstall with backup -> restore -> fsck certified; degraded paths; UAT-01..12 results written into docs/uat.md; Linux installed host only if feasible, macOS and windows/arm64 recorded unknown), C1.6 (automatic startup accounting and fsck detection of publication gaps on the packaged bundle; state honestly whether automatic recovery exists) and C1.7 (operator backup/verify/restore through the shipped CLI, pre- and post-new-write rollback rehearsed on the packaged bundle), and C5.6 (store growth per session, daemon RSS/CPU, hook latency seen by the host).
Check every host fact the draft relies on against the installed CLI's own help (Claude Code 2.1.280; flags for -p/stream-json/hook events/setting sources/permission mode/plugin marketplace add/install with --scope local/uninstall, how headless forced compaction is triggered) and against docs/uat.md and docs/install.md at the integrated head; fix anything wrong. The real-home guard (homeguard.py snap/check, fingerprinting ~/.claude/settings.json, plugins/installed_plugins.json and plugins/known_marketplaces.json byte-identically, never reading credentials) must exist as a committed file the lane uses — create it beside live-uat.js if missing, with a unit self-test on a fake home you run. Replace __BUDGET__ with explicit per-part session budgets (small; Haiku by default) and keep the parts strictly sequential. Keep the final read-only audit stage. Do not over-engineer: reuse what the draft has.
Return: what changed and why, each host fact verified (command + the relevant help line), the coverage map (checklist item -> part/scenario -> evidence path), and anything the coordinator must decide.` },
  { key: 'docs', effort: 'medium', reviewEffort: 'medium', wt: `${ROOT}/qompack-cx-w7-docs`, task: `SEAT docs. Worktree ${ROOT}/qompack-cx-w7-docs (branch closeout/w7-docs at closeout/integration 898bb8b, every wave through 6 merged). The Bash tool resets cwd: prefix commands with \`cd ${ROOT}/qompack-cx-w7-docs &&\`.
Make the user-facing docs match the integrated code (checklist C6.1's code half; evidence numbers from the final gates, UAT results and benchmarks come later and are NOT your job — leave those placeholders as they are). Check README.md and docs/*.md (install, user-guide, commands, mcp-tools, config-reference, security, backup, cannot-do, upstream-issues, architecture, release) against the code: commands and flags that exist, MCP tool names/params/errors, config keys and defaults, hook events and timeouts in the shipped plugin manifest/hooks, owner decisions D1-D32 as shipped (e.g. rollover enabled by default, home directory refused, session-start borrow, Windows staged daemon copy, async SessionEnd, soft drain budget, one GC pass per store, NTFS premise), the version (v0.3.0 per D1) and platform support claims. Generated docs (config-reference, commands, mcp-tools) are changed only through their generators (\`go run ./tools/devtool gen-config-docs\` etc.) and must pass \`--check\`. Run \`go test ./test/docs/...\` and the runpatterns/docmarkers lint (\`go run ./tools/devtool lint --only=docmarkers,runpatterns\`). Wave 7 is concurrently editing docs/troubleshooting.md (a new Windows Defender section), docs/release.md (a code-signing open item) and docs/architecture.md (the EnsureLayout sentence in "Backup and restore"): do not edit those passages. Fix real inconsistencies with small precise edits in focused commits (\`docs(<area>): ...\`); list anything that looks like a product defect rather than a doc error as an open issue instead of changing code.
Return: each inconsistency found (doc location, what the code does, evidence file:line), what you changed, commands run with results, and open issues.` },
]
const RESULT = { type: 'object', properties: {
  status: { type: 'string', enum: ['done', 'partial', 'blocked'] }, head: { type: 'string' },
  commits: { type: 'array', items: { type: 'string' } }, summary: { type: 'string' },
  tests: { type: 'array', items: { type: 'object', properties: { command: { type: 'string' }, result: { type: 'string' } }, required: ['command', 'result'] } },
  open_issues: { type: 'array', items: { type: 'string' } }, needs_owner: { type: 'array', items: { type: 'string' } },
}, required: ['status', 'head', 'commits', 'summary', 'tests', 'open_issues', 'needs_owner'] }
const FINDINGS = { type: 'object', properties: {
  verdict: { type: 'string', enum: ['sound', 'needs-fixes', 'unsound'] },
  findings: { type: 'array', items: { type: 'object', properties: {
    severity: { type: 'string', enum: ['blocker', 'major', 'minor', 'nit'] }, location: { type: 'string' },
    issue: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' },
  }, required: ['severity', 'location', 'issue', 'evidence', 'fix'] } },
}, required: ['verdict', 'findings'] }
return await pipeline(
  SEATS,
  (s) => agent(`${RULES}\n\n${s.task}`, { label: `prep:${s.key}`, phase: 'Prepare', schema: RESULT, effort: s.effort }),
  async (res, s) => {
    if (!res) return { key: s.key, res: null }
    const review = await agent(`${RULES}\n\nYou are an independent READ-ONLY reviewer (do not edit, commit, stash or reset) of seat "${s.key}" in ${s.wt}. Its task was:\n---\n${s.task}\n---\nIts result: ${JSON.stringify(res)}\nReview its commits (\`git -C ${s.wt} log -${Math.max(1, (res.commits || []).length)} --stat\` and the diffs). For livelane: would the script, launched as is after the freeze, run real sessions safely (real-home guard, isolated profile, disposable projects, session budgets, no process kills beyond its own) and produce evidence for every listed checklist item; are the host facts right per the CLI help? For docs: is every change true to the code (verify against the code), were generated docs changed only via generators, and was anything claimed that the evidence does not yet support? Return findings (severity, location, issue, evidence, fix); verdict "sound" with an empty list if none.`, { label: `review:${s.key}`, phase: 'Review', schema: FINDINGS, effort: s.reviewEffort })
    const actionable = (review ? review.findings : []).filter((f) => f.severity !== 'nit')
    if (!actionable.length) return { key: s.key, res, review, final: res }
    const final = await agent(`${RULES}\n\n${s.task}\n\nYou are the FIX seat for "${s.key}" (the first seat finished). Reviewer findings:\n${JSON.stringify(actionable, null, 1)}\nVerify each; fix the correct ones in focused commits; rebut wrong ones with evidence. Return the final state with a "Review resolution" section in your summary.`, { label: `fix:${s.key}`, phase: 'Fix', schema: RESULT, effort: s.effort })
    return { key: s.key, res, review, final }
  },
)
