const RERUN = `THIS IS A RE-RUN (decision D47). Candidate 3 (d5598eb4) failed the rows below; waves 13-14 fixed the defects (plans/sdd/V6-closeout/live/report.md has candidate 3's results and findings; plans/sdd/V6-closeout/w13-*/report.md and w14-*/report.md say what changed; the ledger's D45/D46 rows list what is fixed and what was re-scoped). Re-run ONLY the rows named in your part, on this candidate and bundle, exactly as docs/uat.md and the checklist state them (UAT-02 step 6 and UAT-12 steps 3-4 were revised under D46: read the current text). Write evidence under ${LIVE}/rerun-c4/<row>/ (never overwrite candidate 3's evidence). In docs/uat.md replace each re-run row's Result block with this candidate's result, keeping one history line "Candidate 3 (d5598eb4): <its verdict> — <one-line reason>, evidence plans/sdd/V6-closeout/live/uat/UAT-NN/". Judge every row against its CURRENT expectation; a defect that is still present, or a new one, is a finding with evidence, never excused.`

const PARTS = [
  { key: 'install', phase: 'Install', budget: 4, part: `${RERUN}
Scenario ids to return: UAT-01, C4.8, UAT-12.
(1) UAT-01 (1 session): as in the first run (real-profile LOCAL-scope marketplace install in a fresh disposable project, no QOMPACK_* variables, one short session that makes at least one qompack MCP call), then UAT-01 steps 2-8 with the bundle CLI. Candidate 3 failed fsck (MCP self-record at turn 0) and showed status "2 of 9 FAILING" and doctor/fsck disagreeing: record fsck --json, status, doctor --json exit codes and bodies. Uninstall -s local, marketplace remove, orphan cleanup, guard check.
(2) C4.8 + UAT-12 (at most 3 sessions): the upgrade and restore path. The previous PUBLIC release is the v0.2.0 tag: if \`go run ./tools/devtool bundle\` exists at v0.2.0 build the old bundle from a detached worktree of v0.2.0 (\`git -C ${WT} worktree add --detach ${SCRATCH}/install/prev v0.2.0\`); if v0.2.0 cannot produce a bundle, use 301a8e9 as the first run did and say why. Old build writes a store in a disposable project (1-2 sessions with MCP calls and a /compact), stop its daemon, backup create + verify with the frozen CLI, upgrade to the frozen bundle, one session, then backup restore into a fresh destination and fsck --seal-check the recovery and the source; then uninstall/reinstall survival. UAT-12's bound checks (expand/re_read full:true against runtime.mcp.maxResponseBytes, deny, out-of-project refusal) on the current expectation. Guard check after every session and plugin CLI step.` },
  { key: 'sessions', phase: 'Sessions', budget: 9, part: `${RERUN}
Scenario ids to return: UAT-02, UAT-03, UAT-04, UAT-05, UAT-06, C4.2, C4.3, C4.9. Every session uses --plugin-dir ${BUNDLE}; one disposable project per scenario; use the DEFAULT idle exit unless a step needs the daemon gone, and then say so in the Result block.
C4.2/UAT-02 (1 session): every hook event captured and the index counts match the host; \`qompack status\`, \`doctor --json\` and \`fsck --json\` clean after a session with an MCP call (candidate 3: fsck exit 1).
UAT-03 (1 session): the checkpoint round trip across a daemon idle exit and restart, then fsck and a backup create/verify/restore of that store (candidate 3: index.segments named an unwritten 0002 after a clean idle exit, restore integrity FAILED).
UAT-04 (1-2 sessions): a first prompt longer than 8 KiB (use about 17,000 characters, as before) followed by manual and automatic compactions: the injected block must carry the original whole, or name it as a whole-record overflow with an expand pointer — never a mid-record cut — and no spurious intent_mismatch in LOUD.log.
UAT-05 (1-2 sessions): an explicit user correction after the original requirement, a /qompack:pin made while the daemon runs, then /compact: the block must carry the correction after the original (current authority visible) and the pin; fsck must not report a stale pins view.
UAT-06 (3 sessions): compact, --resume, --resume --fork-session with a correction: the fork keeps the parent's original intent and the corrections are carried.
C4.9 (1 session): repeat (c)-style restore after an MCP call and idle (candidate 3: restore failed on a GC'd MCP root): backup create/verify/restore must pass, fsck agreeing.
If the budget runs short, skip UAT-06's fork session last-but-one and C4.9 last, recording each skip.` },
  { key: 'retrieval', phase: 'Retrieval', budget: 7, part: `${RERUN}
Scenario ids to return: UAT-07, UAT-08, UAT-09, UAT-11, C4.4, C4.5. Every session uses --plugin-dir ${BUNDLE}; fresh disposable projects.
UAT-08 (2 sessions): record_eliminated and already_tried BEFORE any compaction (candidate 3: 'elimination ledger not present'); session scope stored with the calling session and not visible to a later different session; the elimination reaching the next checkpoint's eliminated/decisions and /qompack:why answering it.
UAT-09 (2 sessions): step 2 in-session staleness after the model edits a dependency (already_tried must flip to stale in the same session), steps 3-5 as the doc says (step 5's no-ledger project answers state unavailable with degraded true where the doc says so).
UAT-11 (1 session): step 5-6 with an ordinary >300 KB Read in the first turn: the SessionStart probe must still be found and SessionStart:compact must inject the rehydration block (candidate 3: session degraded to passive).
UAT-07 (1 session, may share with C4.4): recall \`path:src/*.go\`-style globs and \`tool:Read\` host names now match.
C4.4 (1 session): the eight tools' success and error calls again, including timeline turn ranges in a live session and from > to refused; status banner in a healthy session (C4.5: no FAILING contract rows) — record \`qompack status\` in that session.` },
  { key: 'recovery', phase: 'Recovery', budget: 2, part: `${RERUN}
Scenario ids to return: C1.7.
C1.7 (2 sessions, evidence ${LIVE}/rerun-c4/C1.7/): the operator backup/verify/restore path on a REALISTIC store: session 1 makes MCP calls and a /compact (a checkpoint exists), the daemon exits by idle exit (default settings, or state the override), then backup create --id before + verify; pre-new-write restore into D1 + fsck; session 2 writes more; post-new-write restore into D2 + fsck --seal-check; source keeps its later writes; the two refusals as documented. Candidate 3 rehearsed only a Read-only, checkpoint-free store. Record every JSON response and exit code, and C5.6-style store growth for these two sessions.` },
]
