export const meta = {
  name: 'v6-closeout-resume-w3w4',
  description: 'Resume the four paused V6 close-out workstreams (startroute, paths, syncs, e2eflakes): merge integration, finish, review, fix, verify',
  phases: [
    { title: 'Implement', detail: 'resume four stopped workstreams in their own worktrees, after merging closeout/integration 6aff949' },
    { title: 'Review', detail: 'independent adversarial review of INT..HEAD' },
    { title: 'Fix', detail: 'resolve confirmed findings' },
    { title: 'Verify', detail: 'check that the fix seat resolved every non-nit finding' },
  ],
}

const ROOT = 'C:/Users/Quant/Documents/Programming/Projects'
const INT = '6aff949'
const DIGEST = 'C:/Users/Quant/AppData/Local/Temp/claude/C--Users-Quant-Documents-Programming-Projects-qompack/9c57653d-e5ff-4791-8ab4-ad49457994c1/scratchpad/resume'

const COMMON = (w) => `You are one of four parallel workstreams closing out the Qompack V6 verification (Qompack is a Go Claude Code plugin: hooks -> resident daemon -> content-addressed store under .qompack/, an MCP retrieval server, slash commands). Coordinator ledger (read it; do NOT edit it): ${ROOT}/qompack-v6/plans/V6-CLOSEOUT-CHECKLIST.md (owner decisions D1-D16 and coordinator defaults are there). Earlier workstream reports are committed under plans/sdd/V6-closeout/<ws>/report.md (wave 1: ingest, e2e, config, hostperm, rollover, perfstore, perfobs, eval, linux, packaging, rehydrate-cap; wave 2b: w2-*; wave 3: w3-e2ereds, w3-eval3) — read the ones relevant to your task.

YOUR WORKTREE: ${ROOT}/qompack-cx-${w.dir} on branch closeout/${w.dir}. The Bash tool resets cwd between calls: prefix every command with \`cd ${ROOT}/qompack-cx-${w.dir} &&\` or use absolute paths. Never edit other worktrees. Never push, tag, rebase or reset other branches, change git config/hooks, or SendMessage anyone. Your own scratch files go under ${DIGEST}/${w.ws}-work/ (create it); never delete anything else in that scratchpad.

Hard rules (owner directives, non-negotiable):
- Never weaken a check: no t.Skip, no //nolint, no //nomagic:allow added to silence something, no lowered threshold/budget, no golden regenerated to match broken output, no deleted or loosened assertion, no widened timeout that hides a defect. Criterion changes only with a written rationale in your returned report.
- Root cause first; failing regression test first; then fix.
- Commits: conventional \`type(scope): subject\` (lowercase scope, subject <=64 chars, no trailing period), body lines <=100 chars, \`Refs: V6-VERIFY, ${w.cid}\` footer on feat/fix, NO attribution trailers (no Co-Authored-By, Signed-off-by, "Generated with", robot emoji) — the commit-msg hook rejects them. Small focused commits. Evidence logs may be committed under plans/sdd/V6-closeout/${w.dir}/runs/.
- \`go run ./tools/devtool fmt\`/\`fmt-check\`, \`go vet\` on touched packages; \`go test ./test/docs\` and gen-*-docs --check when docs/generated inputs change. Use \`go run ./tools/devtool lint --only=<checks>\` with the specific checks you need: the stubskips sub-check runs a whole-tree go test, which is forbidden here.
- Tests: FOCUSED runs plus each touched package once in full; never ./... or devtool test/test-race (three other workstreams run tests on this machine and in the Linux container at the same time, so the machine is loaded: re-run any wall-clock failure alone before believing it, and say so). Never let a pipe mask go test's exit code.
- Every \`go test -run\` pattern you quote in your report must match a real test name exactly (the runpatterns lint checks committed reports).
- Processes: never kill a process you did not start. If you must stop your own processes, match on YOUR worktree path or your own scratch subdirectory, never on the shared scratchpad root.
- Linux: container \`qompack-v6-linux-verification\`; the committed script plans/sdd/V6-closeout/linux/linux-nonroot-gate.sh runs an exact commit non-root with -race (see its header; use --prefix cx-${w.dir}; if you pass --repo or --out use Windows-style C:/ paths, a POSIX /c/ path is refused); never reuse or delete other /work dirs.
- Real Claude Code sessions are NOT allowed.
- The harness refuses report files from subagents: do NOT write report.md. Return the full report (root causes with evidence, what changed, exact commands + results, criterion changes, open items, owner decisions) in your returned summary; the coordinator commits it.`

const RESUME = (w) => `RESUMING — read this first. This workstream was started 2026-09-25 and STOPPED mid-implementation when the owner paused the whole close-out overnight (not a failure: the earlier seat was killed before it finished). Its work is preserved in your worktree and has NOT been reviewed: commits ${w.oldBase}..${w.oldHead} on your branch plus uncommitted/untracked files. A chronological digest of the earlier seat's tool calls and narration is at ${DIGEST}/${w.ws}.txt — read at least its last third to learn what it had found and where it stopped.
Before anything else:
1. \`git log --oneline ${w.oldBase}..HEAD\`, \`git status\`, \`git diff\`, \`git stash list\` (never drop a stash you did not create).
2. Bring your branch up to the current integration head: \`git merge --no-ff ${INT}\` (closeout/integration; since your base it adds ${w.since}). If git refuses because of local edits, \`git stash\` them, merge, then \`git stash pop\`. Merge subject: \`chore(v6): merge closeout/integration ${INT}\`, no attribution trailers. Resolve conflicts deliberately; build and vet after.
3. Treat the earlier commits and edits as a colleague's unreviewed draft: keep, revise or revert each one deliberately (prefer new commits over rewriting).
4. Evidence from the killed runs is partial and is not evidence: re-run everything you rely on, at your final HEAD.
5. Finish the whole task below. Your review base is now ${INT}: the reviewer will diff ${INT}..HEAD.
${w.note}`

const WS = []

WS.push({ ws: 'startroute', dir: 'w3-startroute', cid: 'C1.16/D11', oldBase: '54a4334', oldHead: 'd9393a0',
  since: 'the w3-e2ereds and w3-eval3 merges and 20af0e6 (a daemon test fix)',
  note: 'When stopped, the earlier seat had all seven commits in and was running HEAD-level checks. It found TestDrain_AReplayedFlushIsEndedOnItsOwnNotUnderThePassBudget (internal/daemon/flush_async_test.go) failing 10/10 alone on Linux at d9393a0 and was re-running it at the base. That row fails at the base 54a4334 too (w3-paths runs/linux/cx-w3-paths-drain-replayed-flush-base-54a4334-*), so it is not yours: integration commit 20af0e6 fixed the test (the pass budget is now spent by a cancel instead of a 200 ms timeout). After the merge, re-run it on Linux with -count=10 at your HEAD, and confirm your drain.go session.start replay guard does not interact with it. test/fault was about to get a full run (it drives daemon-down faults that spool and replay session.start): do that.',
  task: `TASK — SessionStart route follow-ups. Read plans/sdd/V6-closeout/w2-lifetime/report.md and w2-hookout/report.md first.
(1) Owner decision D11 (2026-09-25): an unreadable checkpoint store or a failed rehydration build must ALSO answer a compact SessionStart with the explicit "rehydration deferred" note (the note w2-lifetime added for lateness/stopping/no-answer; internal/daemon/session_start_compact.go and the hook client), never silence. TestService_CheckpointErrorEmitsNothing pins today's silence: change it with a criterion-change rationale citing D11, add rows for each failure class (unreadable store, corrupt/fatal checkpoint, build error, panic), and keep the note far under the host cap (HostChars). Degraded-passive mode still injects nothing. Decide and document how dropped() reports these (never "delivered").
(2) Routed product defect (w2-hookout report, "A session.start that was spooled and replayed later mints a §12.1 probe that was never delivered"): drainDispatch routes a stale spooled session.start through dispatchOp -> handleSessionStart, which mints a sentinel token nobody receives, and two prompts later the project is degraded to passive recording ("hook.additional_context_delivered … sentinel not found after two chances"). Deterministic repro: plans/sdd/V6-closeout/w2-hookout/runs/diag-spooled-sessionstart-probe-windows.log with source runs/zz_diag_hookout_test.go.txt. Fix at the source (a replayed session.start must do its durable bookkeeping but never mint a probe or produce host-facing output, and must never count as a missed delivery), regression test first (turn the diagnostic into a real test), and check every other op the drain replays for the same class of "host-facing side effect on replay" bug.
(3) Evaluate the SessionStart cold-start wait (w2-hookout: session-start stops waiting for a daemon it just spawned after about 1.75 s — EnsureRunning's 1.5 s poll plus the client's 250 ms connect floor — against the 10 s reply budget). Measure what a first SessionStart loses when the daemon is not up in time (startup vs resume vs compact sources) and whether the Windows staged-copy first spawn (w2-lifetime: up to ~3 s under co-load) now makes that routine. Change it only if a real loss exists; any new bound goes to the owner (return it under needs_owner).
Scope: internal/daemon (session_start_compact.go, handlers.go SessionStart route, drain.go drainDispatch/dispatchOp only for the replay guard), internal/cli hook client, internal/rehydrate only if needed, tests, docs. Coordinate: the syncs workstream edits internal/observer and internal/store publication code; the paths workstream edits internal/paths and go.mod.` })

WS.push({ ws: 'paths', dir: 'w3-paths', cid: 'C3.5/C3.7', oldBase: '54a4334', oldHead: 'dd24a58',
  since: 'the w3-e2ereds and w3-eval3 merges and 20af0e6 (a daemon test fix)',
  note: 'When stopped, the earlier seat had seven commits in (WriteAtomic own-root fix, x/sys v0.44.0, GC overshoot priced on GC\'s own clock) and was running final evidence: its Linux final-pkgs run at dd24a58 was killed part-way (runs/linux/cx-w3-paths-final-pkgs-dd24a58-*: partial, not evidence), it was reading a test/integration failure in runs/19-windows-writeatomic-callers.log (find out whether it is yours: re-run the failing row alone at the base and at your HEAD), and runs/21-windows-final-store-daemon.log may be incomplete. The TestDrain_AReplayedFlushIsEndedOnItsOwnNotUnderThePassBudget Linux red it recorded at dd24a58 and at the base is the pre-existing test fixed by integration commit 20af0e6; re-confirm after the merge.',
  task: `TASK — three hygiene defects that affect the final gates.
(1) internal/paths: paths.WriteAtomic finds its temp directory by walking up to the nearest ancestor that contains a .qompack, so on a machine whose home holds ~/.qompack (the user-global config layer, calibration, fallback log, and — since C1.17 — the Windows staged daemon copies under ~/.qompack/bin) writes into a bare temp dir go to <home>\\.qompack\\tmp and fail ("rename C:\\Users\\...\\.qompack\\tmp\\wa-...: The system cannot find the path specified"); 2 internal/cli and 6 internal/ipc rows failed that way (plans/sdd/V6-closeout/w2-lifetime/runs/21 and its report). This machine WILL have ~/.qompack after the live UAT runs, so the final whole-tree gate would go red for a reason unrelated to the product. Decide the correct contract (the temp dir must be on the same volume and inside the store that owns the target; a walk must never escape a project root into an unrelated user-global .qompack, and the user-global layer must use its own root explicitly) and fix it at the source with regression tests that create a fake home .qompack above a temp project. Check every caller of WriteAtomic (and any other ancestor walk for .qompack, e.g. project-root resolution) for the same escape, and confirm real product paths (project store, user-global config) still write where they must. Never create or touch the real ~/.qompack in tests.
(2) govulncheck lists GO-2026-5024 in golang.org/x/sys/windows v0.33.0 (fixed in v0.44.0); the Windows binary imports the package but does not call the affected symbol. Upgrade golang.org/x/sys to the fixed version (and only what it requires), then run \`go run ./tools/devtool licenses --check\`, the pinned govulncheck (\`go run -modfile=tools/pinned/go.mod golang.org/x/vuln/cmd/govulncheck ./...\`), build-all, bindeps lint, and the internal/paths, internal/store and internal/daemon packages on Windows and Linux (script). Update THIRD_PARTY_NOTICES.md if the tooling requires it.
(3) internal/store TestGC_DeadlineOvershootIsBoundedByTheCheckInterval fails ALONE in the Linux container (non-root, -race) with its own "host could not be measured" message, on both b070bbe and w2-lint's branch (plans/sdd/V6-closeout/w2-lint/report.md). Find out whether the test's host-measurement precondition is wrong for a -race GOMAXPROCS=4 container (a test defect, fix without weakening what it proves) or whether GC really overshoots (a product defect). Evidence both ways.
Scope: internal/paths and its callers, go.mod/go.sum, THIRD_PARTY_NOTICES.md, internal/store gc tests. Coordinate: startroute edits internal/daemon and internal/cli; syncs edits internal/observer and internal/store publication code; e2eflakes edits test/e2e.` })

WS.push({ ws: 'syncs', dir: 'w4-syncs', cid: 'C2.3/SP08-D1', oldBase: '31255da', oldHead: '3d1c6b1',
  since: 'only the w3-eval3 merge (eval files)',
  note: 'When stopped, the earlier seat had five commits in (pass counter seam, dropped passes, leased benchmark) and was writing the UNTRACKED internal/observer/publication_sweep_test.go: a crash sweep that cuts the publication steps after the record, because it measured that the existing ctx-countdown sweeps reach only the first 8 of 14 checks. Decide deliberately whether to finish and keep it (it is the "crash-injection test between each remaining step" the task asks for) or replace it. It was also about to export the pre-change tree for the A/B baseline and the base pass count: build the base from 31255da (identical to ' + INT + ' outside eval files) with `git archive 31255da | tar -x -C <your scratch dir>`, never a second git worktree. Its full runs of the two touched packages were killed: redo them at your final HEAD.',
  task: `TASK — carried defect SP08-D1 (OnToolUse over a 256 KB tool result breaches budget B-C, l0_process p99 < 50 ms; dominated by the store's per-capture durability work). Read plans/CARRIED-DEFECTS.tsv (SP08-D1), plans/sdd/V6-closeout/perfobs/report.md, plans/sdd/V6-closeout/perfstore/report.md and plans/sdd/V6-closeout/w3-e2ereds/report.md first.
w3-e2ereds found that the leased PostToolUse path syncs ONE publication root about FOUR times per capture: onToolUse runs syncObservation before publishRecord; completeIntentLocked runs SyncPublication before and after the index write; and finishObservation (added by 22ff16c, "recover original publication before deriving replay") runs a full SyncPublication again on the same root before the capture link, which re-reads and verifies every chunk, then fsyncs every object, roots/tool_use and the index directory.
(1) Establish, from the code, the docs (00-ARCHITECTURE.md §0.2/§0.2.1, docs/architecture.md durability sections, Qompack.md §8) and the crash tests, exactly which of those passes each durability/crash property depends on (what must be durable before the ACK, before the tool_use line becomes visible, before the capture link, before the file-version record). Write that down in your report as a table.
(2) Remove only passes that are provably redundant on the FRESH-publish path (for example finishObservation's SyncPublication when publishObservation already synced the same root in the same call), keeping them on the replay/recovery path where the original publication must be re-proven. No durability or crash-consistency property may weaken: every existing crash/fault/publication test (internal/store, internal/observer, internal/daemon, test/fault, test/integration append-only and crash-recovery rows) must stay green unchanged, and add a test that pins the new pass count per fresh capture (a counter seam, not timing) plus a crash-injection test between each remaining step if one is missing.
(3) Measure the effect with load-independent evidence (fsync/syscall counts via a counting seam or strace on Linux, allocs/op, B/op) and paired interleaved A/B timing of BenchmarkOnToolUse_TestOutput256KB and its AllNovel/one-changed-line variants (-count >= 10 per side, ABBA, both Windows and Linux via the script). Absolute timings on this loaded host are NOT budget evidence (the quiet C5.2 run is the coordinator's); report them only as paired ratios with a sign test. Do not change any budget constant or CARRIED-DEFECTS status.
Scope: internal/observer (tooluse.go, finishObservation), internal/store (publication/intent completion), their tests and benchmarks, docs/architecture.md durability text if it names the passes. Coordinate: e2eflakes edits test/e2e and possibly the daemon's rehydrate-state writer; paths edits internal/paths and go.mod; startroute edits internal/daemon.` })

WS.push({ ws: 'e2eflakes', dir: 'w4-e2eflakes', cid: 'C3.2', oldBase: '31255da', oldHead: '0de7707',
  since: 'only the w3-eval3 merge (eval files)',
  note: 'When stopped, the earlier seat had one commit (0de7707, rehydrate state waited for and read shared, item (b)) and UNCOMMITTED edits in test/e2e/faultinject_test.go and test/e2e/shutdown_spawn_inflight_test.go: its in-progress work on item (a), a settled()/"gone" definition in the e2eLockHolders helper. It was also about to inject a TEMPORARY delay into product code for an ordering diagnostic: confirm `git diff` shows no product-code edit left behind, and never commit a diagnostic product edit. Items (c), (d) and the final whole-package runs had not been done.',
  task: `TASK — the Windows test/e2e rows that fail only under load, so that the final whole-tree Windows gate is trustworthy. Read plans/sdd/V6-closeout/w3-e2ereds/report.md (its full Windows run, runs/, and the four co-load reds) first. For each row: reproduce under controlled load (e.g. run the row with -count=N while a CPU/fsync load generator of your own runs, or run the whole package), root-cause it, and decide product vs test with evidence. Never weaken what a row proves; a wall-clock-only fix (a bigger timeout) is not acceptable unless you prove the bound was wrong and write a criterion-change rationale.
(a) TestE2EShutdownIfReachable_WaitsForASpawnStillInFlight (aec178a, w2-hookout): the helper returned 3.2 ms before the late daemon's cmd.Wait returned; the helper counts the daemon gone when its lock is released, the test asserts process exit. Make the helper and the assertion agree on one definition of "gone" that is correct for every caller of the helper (a helper that returns while a daemon still has files open is what breaks TempDir cleanup on Windows).
(b) TestV5_PreCompactToRehydrateToDroppedRoundTrip/full_budget_round_trip: a Windows sharing violation reading state/rehydrate-sess-e2e-v5-x04.json (v5_x04_test.go:305) under co-load. Find whether the daemon's writer (atomic rename while a reader has the file open) or the test's reader (not using paths.ReadFileShared / not retrying a documented transient) is at fault. If a PRODUCT reader of that state file (status, dropped(), MCP) can hit the same sharing violation on Windows, that is a product defect: fix it at the source with a test.
(c) TestV4_HotPathUnchangedWithTheFullWave3ResidentSet: under load the baseline arm touched spool/<client> (a hook spooled because it missed its ACK) and the wave-3 arm did not, so the touch-set comparison differed. Decide what the row is meant to prove and make it compare the right thing (e.g. exclude hook-spool files that exist only because of an ACK miss, or assert on them separately) without losing its power to catch a real extra write.
(d) TestV3_HotPathUnchangedWithLedgerResident fails even alone on a loaded host (B-A p50 30.7 ms against 15 ms). That is a timing row: do not change its budget; confirm it is purely a timing gate and that its non-timing assertions pass under load, and say so. The quiet C5.1 run judges its numbers.
Finish with the whole test/e2e package alone on Windows (quiet as you can make it) and on Linux via the script, and report every row.
Scope: test/e2e helpers and rows, and the daemon/store writer or reader of state/rehydrate-*.json only if (b) proves a product defect. Coordinate: syncs edits internal/observer and internal/store publication code; startroute edits internal/daemon; paths edits internal/paths.` })

const RESULT = { type: 'object', properties: {
  status: { type: 'string', enum: ['done', 'partial', 'blocked'] }, head: { type: 'string' },
  commits: { type: 'array', items: { type: 'string' } }, root_cause: { type: 'string' }, summary: { type: 'string' },
  tests: { type: 'array', items: { type: 'object', properties: { command: { type: 'string' }, result: { type: 'string' } }, required: ['command', 'result'] } },
  criterion_changes: { type: 'array', items: { type: 'string' } }, open_issues: { type: 'array', items: { type: 'string' } },
  needs_owner: { type: 'array', items: { type: 'string' } },
}, required: ['status', 'head', 'commits', 'summary', 'tests', 'open_issues', 'needs_owner'] }
const FINDINGS = { type: 'object', properties: {
  verdict: { type: 'string', enum: ['sound', 'needs-fixes', 'unsound'] },
  findings: { type: 'array', items: { type: 'object', properties: {
    severity: { type: 'string', enum: ['blocker', 'major', 'minor', 'nit'] }, location: { type: 'string' },
    issue: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' },
  }, required: ['severity', 'location', 'issue', 'evidence', 'fix'] } },
}, required: ['verdict', 'findings'] }

const LENS = 'Lenses: (a) root cause proven and fixed at the source; correctness incl. concurrency (races, deadlocks, lock order, goroutine leaks), durability/crash semantics (fsync ordering, WAL retention, idempotency, identity never re-minted), fail-closed paths, Windows vs POSIX, bounded memory/CPU; (b) check-weakening (deleted/loosened assertions, skips, nolint/nomagic, lowered thresholds, regenerated goldens, widened timeouts, tests bent to buggy output) and legitimacy of every criterion change; (c) docs consistent with behaviour, generated docs via generators; (d) commit hygiene (conventional subjects, Refs footer, no attribution trailers); (e) was the whole task done, or parts silently dropped? (f) the merge of closeout/integration: conflicts resolved without losing either side.'

const results = await pipeline(
  WS,
  (w) => agent(`${COMMON(w)}\n\n${RESUME(w)}\n\n${w.task}`, { label: `impl:${w.ws}`, phase: 'Implement', schema: RESULT }),
  async (impl, w) => {
    if (!impl) return { w, impl: null, review: null }
    const review = await agent(`You are an independent, adversarial reviewer for Qompack V6 close-out workstream "${w.ws}" (${w.cid}). Worktree ${ROOT}/qompack-cx-${w.dir}, branch closeout/${w.dir}. The branch was started on ${w.oldBase}, paused overnight, resumed, and has merged closeout/integration ${INT}; review \`git -C ${ROOT}/qompack-cx-${w.dir} log ${INT}..HEAD\` and the net diff \`git diff ${INT} HEAD\`. The task was:\n---\n${w.task}\n---\nImplementer result: ${JSON.stringify(impl)}\nREAD-ONLY: do not edit, commit, stash or reset. You may run focused tests (never ./...; never kill processes you did not start; the machine is loaded — re-run a timing failure alone before believing it). No real claude sessions.\n${LENS}\nReturn findings with severity, file:line, evidence and a concrete fix; if sound, verdict "sound" and an empty list.`,
      { label: `review:${w.ws}`, phase: 'Review', schema: FINDINGS, effort: 'high' })
    return { w, impl, review }
  },
  async (r) => {
    if (!r.impl) return { w: r.w, ws: r.w.ws, impl: null, review: null, final: null }
    const actionable = (r.review ? r.review.findings : []).filter((f) => f.severity !== 'nit')
    if (actionable.length === 0) return { w: r.w, ws: r.w.ws, impl: r.impl, review: r.review, final: r.impl, fixRan: false, actionable }
    const final = await agent(`${COMMON(r.w)}\n\nYou are the FIX seat for this workstream (the implementer has finished; its branch already merged closeout/integration ${INT}). Its task was:\n---\n${r.w.task}\n---\nIndependent reviewer findings:\n${JSON.stringify(actionable, null, 1)}\nVerify each independently; fix the correct ones (failing test first where applicable) and re-run focused tests; rebut wrong ones with evidence. Blockers/majors must be resolved or rebutted. Return the final state with a "Review resolution" section (finding -> action/rebuttal) in your summary.`,
      { label: `fix:${r.w.ws}`, phase: 'Fix', schema: RESULT })
    return { w: r.w, ws: r.w.ws, impl: r.impl, review: r.review, final, fixRan: true, actionable }
  },
  async (r) => {
    if (!r.fixRan || !r.final) return { ws: r.ws, impl: r.impl, review: r.review, final: r.final, fixRan: !!r.fixRan, verify: null }
    const verify = await agent(`You are an independent verifier for Qompack V6 close-out workstream "${r.ws}". Worktree ${ROOT}/qompack-cx-${r.w.dir}, branch closeout/${r.w.dir}. A reviewer raised these findings:\n${JSON.stringify(r.actionable, null, 1)}\nThe fix seat's result: ${JSON.stringify(r.final)}\nFor EACH finding decide whether it is now resolved correctly or rebutted soundly, by reading the code at HEAD and the fix commits (\`git -C ${ROOT}/qompack-cx-${r.w.dir} log ${r.impl.head}..HEAD\`), and check the fix commits introduced no new defect or check-weakening. READ-ONLY: do not edit, commit, stash or reset; focused tests allowed (never ./...; never kill processes you did not start). Return as findings ONLY what is still wrong (unresolved, badly rebutted, or newly introduced), with severity, file:line, evidence and fix; verdict "sound" with an empty list if everything is resolved.`,
      { label: `verify:${r.ws}`, phase: 'Verify', schema: FINDINGS, effort: 'high' })
    return { ws: r.ws, impl: r.impl, review: r.review, final: r.final, fixRan: true, verify }
  },
)
return results
