const LIM15A = `EVIDENCE: the candidate 4 live re-run's audit (plans/sdd/V6-closeout/live/report-c4.md, section "Independent audit") and its evidence under plans/sdd/V6-closeout/live/rerun-c4/ are on your base. Coordinator decision D50 in the ledger fixes the dispositions: read D45, D46, D49 and D50 first.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and six seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, and do NOT run the hot-path rows (TestIntegration_HotPath*, TestV3_HotPath*) or whole test/integration / test/e2e packages; run the focused rows you add or touch and the touched packages in full once. The Linux container is STOPPED: do not start it. No real Claude Code sessions: reproduce with deterministic tests that are RED before the fix.
Other seats running now: wave 15 rehydrate (internal/rehydrate), ledger (internal/negknow, checkpoint decisions), services (daemon config reload, mcp recall in handlers.go, store publication accounting, fsck index.files), docs; and paging / snapshot in this wave. Do not fix their items or edit their files beyond what your fix needs; if your root cause is theirs, say so and stop.`

const WS = []

WS.push({ ws: 'paging', cid: 'C4.4/C4.10', effort: 'high', reviewEffort: 'high', task: `TASK — MCP response paging consistency (D50).
${LIM15A}
Evidence: rerun-c4/UAT-12/notes.txt and cli/20-mcp-probe.json, cli/21 (a 354,352-byte capture): (1) the final page answers truncated:true with no next_span; (2) an explicit span 0:354352 pages as next_span 217070:16384 while full:true pages as 217070:137282. D50: a page that is truncated always carries a next_span that continues it (and a page that reaches the end is not truncated); an explicit span pages exactly like full:true over the same range (same cut, a next_span covering the rest of the requested span). Keep the D48 safeCut properties and every existing response-bound test green. Tests RED first for both.
Scope: internal/mcp (response bounds, expand/re_read span handling; NOT the recall handler), its tests; docs/mcp-tools.md only if its paging text must change.` })

WS.push({ ws: 'snapshot', cid: 'C4.5', effort: 'high', reviewEffort: 'high', task: `TASK — the host-contract snapshot and the status banner (D50).
${LIM15A}
Evidence: rerun-c4/UAT-01/notes.txt:50-55 and docs/uat.md UAT-01 Result: after the session's MCP call the daemon's contract snapshot reads mcp.server_registered 'initialize-pending' and hook.additional_context_delivered 'not-yet-observed', while the same store's state/history.json records mcp_initialized true and sentinel observed true; the status banner still said 'host contract: 9 assertion(s), all holding'. D50: an observed MCP initialize or sentinel refreshes the snapshot (status/doctor read what history.json already knows), and the banner never counts a pending or not-yet-observed row as holding (it says how many are pending). Tests RED first. Find where the snapshot is written and read (internal/diag or internal/daemon contract code, cmd status).
Scope: the contract snapshot writer/reader, the status/doctor banner, their tests; docs/commands.md or troubleshooting.md only where the banner text they quote changes.` })
