const LIM15C = `Coordinator decisions D49 and D51 in the ledger govern this task: read them. The wave 15 services report is on your base: plans/sdd/V6-closeout/w15-services/report.md (its needs_owner and open issues are the source of this task).
MACHINE LIMITS FOR THIS SEAT (override the general rules): the owner is using this laptop and another seat runs. Use \`-p 2\`, no load generators except the bounded measurement below, no hot-path rows, no whole test/integration or test/e2e. The Linux container is STOPPED: do not start it. No real Claude Code sessions.
Other seat running now: wave 15 rehydrate (internal/rehydrate). Do not edit its files.`

const WS = []

WS.push({ ws: 'pubscan', cid: 'C1.6/C4.5', effort: 'high', reviewEffort: 'high', task: `TASK — make the background publication pass cheap and out of the session's way, and document the reload's key classes (D51).
${LIM15C}
(1) The startup publication accounting now finishes in the background, unpaced (internal/daemon/publication_audit.go, internal/store/publication_audit.go): 15.1 s cold / ~4 s warm on a 10x store (3800 objects, 3961 dirs, 700 captures) and PutBytes p99 16 -> 26 ms beside it (runs/review-pubscan-10x-diagnostic.txt in the w15-services dir). D51: (a) reuse one os.Root for the whole pass instead of an OpenRoot plus an Lstat on every parent directory per directory, keeping the confinement guarantees (the maintenance/GC confinement tests must stay green); (b) the pass yields to capture work: it never runs beside a hook request (pause while one is in flight, resume after), so a session's I/O does not pay for it. Any new number is a named constant with a derivation. Measure before/after with the same 10x diagnostic (bounded, <=20 min, <=8 processes) and report cold/warm pass time and PutBytes p99 alone and beside the pass. Tests: the pass completes, reports the same gaps as before, and pauses while a request is in flight (deterministic, no sleeps; the sleepcheck lint applies).
(2) Docs: docs/config-reference.md (and troubleshooting.md where the reload is described) say which keys take effect on reload, which need a daemon restart (the reload_keys.go table), which have no effect in 0.3.0 (runtime.logging.*, selection.deltaScoring, selection.submodular.lazyGreedy, runtime.selection.loopWarningsEnabled, runtime.telemetry), the LOUD 'config change needs a daemon restart' line and admin.reload's restart_required and no_effect fields. If config-reference.md is generated, change its generator and regenerate. Make sure a test ties the doc's key lists to reload_keys.go so they cannot drift (a docs test in test/docs or beside the generator).
Scope: internal/daemon/publication_audit.go, internal/store/publication_audit.go (and the store's root helpers it needs), their tests, docs, the generator if any.` })
