const LIM15 = `EVIDENCE: the live re-run on candidate 4 (9f6a2fad, decision D47) ran real Claude Code sessions with the frozen bundle. Its evidence is committed on your base under plans/sdd/V6-closeout/live/rerun-c4/<row>/ and the Result blocks in docs/uat.md; the findings named below come from there. Coordinator decision D49 in the ledger says every one is fixed before 0.3.0 and fixes each disposition: read D45, D46 and D49 first.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and four seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, and do NOT run the hot-path rows (TestIntegration_HotPath*, TestV3_HotPath*) or whole test/integration / test/e2e packages; run the focused rows you add or touch and the touched packages in full once. The Linux container is STOPPED: do not start it. No real Claude Code sessions: reproduce each finding with a deterministic test (a real daemon/store/hook process in a temp project is fine) that is RED before the fix.
Other seats: rehydrate (fallback visibility, evolution admission, eviction order), ledger (stale bloom, advance_frontier, decisions across checkpoints, fork inheritance), services (config reload, recall k, publication accounting, fsck index.files), docs. Do not fix their items; if your root cause is theirs, say so and stop.`

const WS = []

WS.push({ ws: 'rehydrate', cid: 'C4.3', effort: 'xhigh', reviewEffort: 'high', task: `TASK — rehydration's current-authority and fallback defects (D49).
${LIM15}
(1) F-C4-UAT03-1 (rerun-c4/UAT-03/probe/): when the newest checkpoint does not verify (one byte corrupted), SessionStart(compact) builds the payload from the previous checkpoint and presents it as current: 'checkpoint 0001', state dropped [], degraded false, no section-7 entry; LOUD.log names only the refusal of 0002. D49: a fallback is never silent. The payload names it (section 7: newest checkpoint N refused, rebuilt from M, what may be missing, how to restore), the rehydrate state reads degraded true with the reason, the drop report carries it, and LOUD.log says 'rolled back to M'.
(2) F-C4-UAT06-1 + F-C4-UAT06-3 (rerun-c4/UAT-06/C-block2-SessionStart-compact.txt, section2-in-order.txt): the fixed 10% evolution share drops the only correction in force (named 'user_intent_evolution 0 — did not fit') while the block uses 2,652 of 9,400 chars; evolution holds every later prompt, so ordinary prompts push a correction out. D49: the newest restatement of the user's intent (the correction in force) is admitted with the original, ahead of the share; the share stays for older entries, and room the payload leaves unused goes to evolution newest-first before the payload is final. Keep D5 (whole records or a named overflow) and D46's ceilings.
(3) F-C4-UAT05-3 (rerun-c4/UAT-05/): at a 150-token budget section 8 (retrieval) is evicted while the pinned invariant stays. Read ADR 0011's tier-1 admission order and make the eviction follow it exactly; if ADR 0011 and the code are both defensible but disagree, follow the ADR and say so. A test at a tiny budget pins the order.
Scope: internal/rehydrate (and the checkpoint loader it calls), their tests.` })

WS.push({ ws: 'ledger', cid: 'C4.3/C4.4', effort: 'high', reviewEffort: 'high', task: `TASK — elimination ledger and decisions across restarts, resumes and forks (D49).
${LIM15}
(1) R4-1 (rerun-c4/UAT-09/): after a daemon restart already_tried answers {"state":"absent"} for a STALE elimination. From code (internal/negknow): the tried.bloom query filter holds only ACTIVE records, Record adds a key only to the in-memory filter, reconcileBloom finds no active record missing and does not rebuild, and Query's first !bloom.Test returns absent before it reads the stale record; an idle rebuild_bloom (rebuildOnStale) drops the key the same way. D49: a record goes stale, never absent: the filter covers every record that exists (active and stale), rebuild and reconcile included, with tests for the restart and the idle-rebuild paths.
(2) F-C4-C49-3 (rerun-c4/C4.9/): in a session with no compaction and no elimination, the idle task act.advance_frontier fails every 30 s ('SourceSet.Ledger is nil: its accessor resolved to no ledger: qompack: running in degraded mode'). D49: no ledger yet is not an error: the frontier advances without negative knowledge (or the task is a quiet no-op until a ledger exists), no WARN, and the frontier does advance; test it.
(3) F-C4-UAT06-2 (rerun-c4/UAT-06/steps/checkpoint-0001.json vs checkpoint-0002.json): after --resume, the same session's second checkpoint has decisions [] although 0001 had dec_991dbff588ec and the elimination is still carried. D49: a decision stays in every later checkpoint of the session while it holds (the way eliminations carry), under the existing cap and ranking.
(4) F-C4-UAT06-1, ledger half: a --fork-session's checkpoints (0004/0005) carry eliminated [] and decisions []: the parent's session-scoped eliminations and decisions are not inherited. D49: a fork continues the parent's conversation, so the parent's session-scoped records up to the fork point are visible to the fork (already_tried, why, checkpoints), attributed to the parent session; a later sibling session still does not see them.
Scope: internal/negknow, internal/checkpoint (decisions, advance), internal/daemon idle wiring, their tests.` })

WS.push({ ws: 'services', cid: 'C4.4/C4.5', effort: 'high', reviewEffort: 'high', task: `TASK — daemon services: config reload, recall, publication accounting, fsck (D49).
${LIM15}
(1) F-C4-UAT05-2 (rerun-c4/UAT-05/cli/run2-b-*): the daemon logs 'config reloaded changed=[runtime.rehydrate.maxTokens runtime.rehydrate.minTokens]' but rehydrates at its startup budget until a restart (reload.go updates d.cfg; the rehydrate service reads s.o.Cfg). The same class in UAT-09: a mid-session eliminations.staleResponse change is reloaded but already_tried keeps the old form. D49: every setting the reload reports as changed takes effect in the running daemon, or the reload says it needs a restart. Audit every service that holds a config copy (rehydrate, negknow, mcp, scheduler, gc...) and fix each; a test per service that a reload reaches it.
(2) F1 (rerun-c4/UAT-12/cli/50-mcp-probe-recall.json, sessionC): recall's k counts hits that authorization then withholds (handlers.go asks store.Search for K hits and drops denied ones afterwards): at k=5 the caller got 2 hits and denied:3 while three permitted hits existed. D49: k is the number of permitted hits returned when that many exist (keep fetching past denied ones, bounded), denied stays a count. Also, Qompack's own retrieval self-records rank above the original captures (UAT-07, UAT-12): they rank after every non-self hit.
(3) F2 (rerun-c4/UAT-12/store/logs_LOUD.log): the startup publication accounting is bounded at 250 ms (publicationStartupBound); on a 3-session store (70 captures, ~380 objects) every start logs LOUD 'publication accounting incomplete ... scan interrupted'. D49: a healthy store never gets that line: the scan finishes (continue it in the background after the startup bound, or make it fast enough), and LOUD is written only for a real gap or a scan that cannot finish. Measure the scan on a store of that size in the test.
(4) Investigate (rerun-c4/UAT-04/, post-run): with a planted unparseable config in place fsck exited 1 on index.files 'absent while its log carries 4 path(s)'. Reproduce deterministically; if it is a product defect fix it, if it follows from the planted config say exactly why and whether fsck's message is right.
Scope: internal/daemon (reload, services), internal/mcp (recall), internal/store (publication accounting, fsck index.files), their tests.` })

WS.push({ ws: 'docs', cid: 'C4.10', effort: 'medium', reviewEffort: 'medium', task: `TASK — documentation findings from the candidate 4 re-run (D49). No product code.
${LIM15}
(1) F3: docs/troubleshooting.md §3 still says 'Read the record's Fidelity' and 'read that record's fidelity through expand', contradicting mcp-tools.md (no retrieval response carries fidelity or coverage, D46). Say where fidelity is recorded and how an operator reads it (the capture sidecar / fsck / doctor, whatever the shipped code offers: read internal/ and cmd/).
(2) Document the host's decoding of binary files (UAT-12 step 4, UAT-02): Claude Code refuses Read on a binary, decodes Bash output as text and sends images as base64, so Qompack records what the host delivered (fidelity exact) and never decodes anything itself. Put it in user-guide.md and cannot-do.md (or wherever the existing structure says), consistently.
(3) F-C4-UAT05-1: UAT-05 step 5 says '--set runtime.rehydrate.maxTokens on a hook invocation' changes the budget; when the daemon builds the rehydration its config governs. Fix the step (and any doc making the same claim) to what the code does.
(4) UAT-09 step 5's 'reachable form' (a project with no ledger answers unavailable/degraded) is stale: the ledger now opens on first use and answers absent. Rewrite the step to a reachable degraded form (the re-run used records/eliminations.jsonl made unreadable) and keep its expectation.
(5) UAT-02: the non-exact fidelity capability is not observable through this host (it delivers oversized/binary content whole or not at all). D49 records it as host-limited, covered by tests: name those tests in the UAT-02 block (exact names) with a one-line note 'non-exact fidelity is host-limited on Claude Code 2.1.280; covered by <tests> (D49, 2026-09-30)'. Do not change a verdict.
(6) The stdio \`qompack mcp\` probe outside a host session answers denied:N for records an in-session recall returns (rerun-c4/C4.9, retrieval notes): read internal/mcp authorization, and document why (no host permission context = fail closed, or whatever the code does) in mcp-tools.md; if it is a product defect, do not fix it: report it.
(7) docs/uat.md's intro paragraph (about lines 8-18) still describes the candidate 3 run: make it describe the current record (candidate 3 first run, candidate 4 re-run under D47) in two or three sentences.
Run go test ./test/docs and the docs gen --check tasks. Scope: docs/ only.` })
