const LIM16C = `Wave 16b is merged into your base, along with every earlier wave. Its reports are on your base under plans/sdd/V6-closeout/w16b-<ws>/report.md; read the ones your task names. Coordinator decisions D53 and D55 in the ledger (${ROOT}/qompack-v6/plans/V6-CLOSEOUT-CHECKLIST.md) govern this wave.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and one other seat runs at once. Use \`-p 2\`, no load generators, no -race on whole packages, no hot-path rows (TestIntegration_HotPath*, TestV3_HotPath*), and no whole test/integration or test/e2e package. Run the focused rows you add or touch by exact name, and each touched package in full once (test/bench/hotpath in full is fine; test/integration only by the exact names of rows whose text you change, and not the hot-path rows). The Linux container and Docker Desktop's engine are STOPPED; do not start them. No real Claude Code sessions.
Other seat in this wave: settle2 (internal/daemon) and tidy (everything else listed in its task). Do not edit the other seat's files.`

const WS = []

WS.push({ ws: 'settle2', cid: 'C4.3', effort: 'high', reviewEffort: 'high', task: `TASK — close the three nits wave 16b's settle review left open (plans/sdd/V6-closeout/w16b-settle/report.md, the Review section's nit findings). The verify pass found the seat sound; these are the remaining review nits, and the drop report's "never silently missing" contract makes the second one more than cosmetic.
${LIM16C}
(1) precompact_settle_spool_reads over-attributes. It is the change in the index-wide spoolHeads.reads counter while the settle runs, so the client-spool watcher's indexClientSpools and a concurrent settle of another session are counted against this settle. Count the reads of this settle's own scans (have the scan return its read count, or pass a counter), and add those. Keep or drop the index-wide total as you see fit. Add or adjust a row so a concurrent indexClientSpools pass during a settle does not change the settle's count (a deterministic seam, not sleeps).
(2) The spool index can serve a recreated file's stale heads. Entries leave the index only when a later listing no longer shows the file. A drain can remove client-<pid>.ndjson, and a hook with a reused pid can recreate it with the same size and modification time before the next listing (coarse mtime on the slow filesystems spool submode targets). The settle then neither replays nor counts that session's capture. Invalidate the index entry when the daemon itself removes or truncates a client spool (the drain's removal path, e.g. drain.go near the os.Remove of a released client spool, or a callback in drainConfig). Pin it with a row that removes a file through the daemon's own path and recreates it with the same bytes and mtime (os.Chtimes), then checks the next settle reads it again and names the capture.
(3) Item 4's wiring is untested. TestSpoolWatch_TheIdleTickKicksItInSpoolSubmode calls kickSpoolWatchInSpoolSubmode itself, so removing the call from Run's idle tick fails nothing. Factor the tick body into a method that Run calls (for example d.onIdleTick(ctx, now)) and have the row call that method, or drive Run itself with a small IdleExitSeconds in spool submode. Either way, deleting the kick from the tick path must turn the row red; show that once (a temporary local edit, not committed) and say so.
Optional, only if it is a few lines: drain.go's drainWalPrefix/isClientSpoolName may call ipc.SpoolFileKindOf (added by wave 16b) instead of respelling the prefixes. Skip it if it widens the diff.
No new budget or bound numbers. Scope: internal/daemon and its tests.` })

WS.push({ ws: 'tidy', cid: 'C4.6', effort: 'medium', reviewEffort: 'high', task: `TASK — six small follow-ups from wave 16b's reports (w16b-polish, w16b-cirec, w16b-cover on your base). Item (1) is a privacy fail-open and comes first.
${LIM16C}
(1) MINOR, privacy. internal/hostperm/policy.go shortNameRe (\`~[0-9*?\\[\\\\]|\\[[^\\]]*~\`) misses a bracket expression that lists an escaped ] before the tilde: Read(**/CREDEN[\\]~]1.SEC) and Read(**/CREDEN[\\]-~]1.SEC) still match CREDEN~1.SEC under path.Match, yet shortShaped is false, so prefixRow skips the 8.3 alt and a deleted file is judged on its long name. The base (any tilde) denied these. See w16b-polish/report.md, section Verify, for the probe.
  - Make the class alternative step over escapes. The verifier's probed candidate: \`~[0-9*?\\[\\\\]|\\[(?:\\\\.|[^\\]\\\\])*\\\\?~\`. Probe it yourself against at least: creden[\\]~]1.sec, creden[\\]-~]1.sec, creden[~]1.sec, creden[}-~]1.sec, creden[\\~]1.sec, creden\\~1.sec (all shaped) and *~, *.txt~, *.[ch]~ (not shaped). If you find another legal spelling where a pattern that path.Match would match against an ~<digit> name still is not shaped, close it too, or state it. The rule: whenever a segment contains a tilde that path.Match can match literally and that is followed by something able to match a digit, it is shaped. Failing closed is acceptable; failing open is not.
  - Add the rows: creden[\\]~]1.sec in TestShortShaped_NamesAnEightDotThreeNameOnlyByShape, and Read(**/CREDEN[\\]~]1.SEC) in the 8.3-shaped rows of TestShortNames_ATildeThatNamesNoShortNameJudgesDeletedFiles (a backslash in a rule needs the existing JSON quoting there).
  - Correct the shortNameRe comment so it does not overclaim.
  - Do not widen this into the pre-existing no-tilde case (CREDEN?1.SEC); that stays as recorded.
(2) plans/00-ARCHITECTURE.md's plugin.json example (near line 826) still lists the "cache" keyword that wave 16b dropped from the shipped manifest. Drop it, with a revision-log line if the document keeps one.
(3) Stale lane lists (w16b-cirec review finding 2, routed here). On hosted runners bench-gate, timing, test-e2e (D53(e)) and now nightly bench-deep (D55) report B-A, B-B and B-E's wall row under QOMPACK_NONREFERENCE_DISK, and ADR 0010 Addendum 2 says no hosted job gates those rows. These texts still say those lanes enforce the limits:
  - test/bench/hotpath/report.go (baWallWaivedNote, bbWallWaivedNote and the comment near line 198; they are written into the JSON artifacts);
  - test/bench/hotpath/main.go near lines 178 and 239;
  - test/integration/hotpath_test.go near lines 1090 and 1235 (comments only);
  - internal/obs/nonrefdisk.go's doc (lines 4-9: add D55 and nightly bench-deep).
  Qualify each list along the lines of "on a reference disk (the owner's quiet runs); hosted runs of these lanes report the row under QOMPACK_NONREFERENCE_DISK (ADR 0010 Addendum 2)". Update report_test.go's pinned lane check (line 280) so it pins what the note now says, not less. Do not change any gate, limit or which rows are reported.
(4) plans/sdd/V6-closeout/w16-ci/runs/fix-daemon-count2-windows.log line 43 says "nightly's -race run of the package alone took 1203 s". nightly's race-windows job runs the whole tree, so write "internal/daemon took 1203 s inside nightly's whole-tree -race run there". Edit only that commentary line.
(5) internal/store/gc_delivery_segments_edge_test.go TestDsealParsers_RefuseAnOversizedDocument cannot tell whether the size bound works (an oversized run of spaces fails json.Unmarshal anyway). Rename or comment it so it does not claim to pin the bound; say the bound is a cost guard. Do not delete it.
(6) internal/store/demand_compact_edge_test.go:46 hard-codes 1<<17 as "past the scanner's bound"; use bufio.MaxScanTokenSize+1.
Scope: internal/hostperm, plans/00-ARCHITECTURE.md, test/bench/hotpath, test/integration/hotpath_test.go (comments only), internal/obs/nonrefdisk.go, that one log line, the two store test files.` })
