const LIM16D = `Waves 16 and 16b are merged into your base. Their reports are under plans/sdd/V6-closeout/w16-<ws>/ and w16b-<ws>/report.md. Coordinator decisions D53 and D55 in the ledger (${ROOT}/qompack-v6/plans/V6-CLOSEOUT-CHECKLIST.md) govern this wave, and Q1 (hosted fsync figures are never constants; hosted fsync-bound rows report under QOMPACK_NONREFERENCE_DISK) applies.
Hosted CI run 36905843834 (verify/v6 07a748cb, the integration tree ae601390 merged) is green on ubuntu and macOS test, every timing and bench-gate leg, test-e2e ubuntu and macOS, security, replay-gate, docs, crossbuild and plugin-validate. Your task is one of its two reds. Read the job log with \`gh api repos/AidanHT/qompack/actions/jobs/<job>/logs\` (read-only); a copy is in ${SCRATCH}/../ci6/.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and three other seats run at once (wave 16c: settle2 in internal/daemon spool watcher, drain.go, precompact_settle.go, spool_heads.go and daemon.go's idle tick; tidy in internal/hostperm, test/bench/hotpath, internal/obs, store tests). Use \`-p 2\`, no load generators, no -race on whole packages, no hot-path rows, no whole test/integration or test/e2e package: run the e2e rows you touch by exact name. The Linux container and Docker Desktop's engine are STOPPED; do not start them. No real Claude Code sessions.
Never make a row pass by raising a product budget, removing an assertion or skipping: a fixture change is acceptable only when the row's subject is not the thing changed and another row pins that thing; record each such change as a criterion change with the rationale and the row that pins it.`

const WS = []

WS.push({ ws: 'warnlate', cid: 'C3.2', effort: 'high', reviewEffort: 'high', task: `TASK — hosted red: test-e2e (windows-latest), job 110516048026. TestV5_ThrashWarningVisibleInStatusAndCheckpoint/sequitur_warning_is_warning_only_and_once_per_rule fails at test/e2e/v5_x10_test.go:466, "the prompt after a thrashing loop must carry the warning": the prompt hook's output had no HookSpecificOutput. It passed on ubuntu and macOS, and locally (w16-e2erows). Candidate 5's hosted run failed the same row at a different line (the checkpoint carried the warning), which wave 16 fixed.
${LIM16D}
(1) Find the cause. Candidates, not conclusions:
  - the hook client's ACK deadline expired on the hosted disk (Windows B-A 50 ms; hosted fsync p99 ~74 ms with a tail past 1 s), so the client spooled the prompt and printed no output;
  - or the daemon's reply exceeded promptReplyDeadline (250 ms, internal/daemon/handlers.go callObservePromptWithDeadline), which sends the reply empty by design and counts l0_prompt_reply_late.
  Tell them apart with evidence: the log, the code paths, and a local reproduction through a deterministic seam (a held ingest or reply seam, or a slowed fsync seam), not wall-clock luck.
(2) Decide the product question with evidence and fix it if it is a defect. When the warning does not reach the host (late reply, or the client deferred on its ACK deadline), is it consumed so the rule is treated as delivered? Then a loop that continues is never warned about on a slow disk. That is a real defect: a warning the host never received must not count as delivered for once-per-rule. Keep the documented design that a stale warning is not replayed into a later turn; the fix is that the detector may warn afresh when the loop continues. If the code already behaves this way, show it with a row.
(3) Make the e2e row hold on a non-reference disk without weakening it. On a reference disk the first prompt after the loop must still carry the warning. When this prompt's reply was observably late or deferred (the counter, or the client spool), the row must prove recovery instead: e.g. one more loop cycle, after which the next prompt carries the warning. Assert every other property (channel, once per rule, nothing durable, not in the checkpoint) exactly as now. Keep the late or deferred branch observable and logged, never silent.
Also report anything else in that job's log that failed or warned.
Scope: internal/daemon/handlers.go (prompt reply path), internal/observer (prompt delivery), internal/grammar (statewarn delivery accounting), test/e2e/v5_x10_test.go, and their tests. Do not edit settle2's files.` })

WS.push({ ws: 'sealrow', cid: 'C4.3', effort: 'high', reviewEffort: 'high', task: `TASK — hosted red: cover (ubuntu), job 110516048246. internal/cli TestPreCompactInSpoolSubmodeSealsTheSpooledReads (wave 16 spoolseal's row) failed at precompact_spool_submode_test.go:93. Both spooled Reads were replayed and sealed, but the checkpoint's dropped list held an unreplayed_capture: "1 capture(s) of this session (0 tool result(s), 0 prompt(s), 1 other) were still waiting to be replayed into the store when this checkpoint was sealed". The ubuntu test job (-race, cacheable) and every other leg passed it; cover runs it with -covermode=atomic, in parallel with the other packages.
${LIM16D}
(1) Find the cause. Which capture was the "1 other": the spooled Stop, the session-start, or something else? Why was it not replayed inside precompactSettleBound (500 ms) when the Reads were? Candidates: a slow cover-instrumented drain under co-load; the drain ordering or a lease wait for the Stop; the settle's own-spool detection; a race between the Stop hook's spool write and the first look. Show it with evidence: the code, plus a deterministic local reproduction (a held drain seam, an instrumented build, or -covermode=atomic with -cpu 1 and -count=N). Do not rely on wall-clock luck.
(2) If it is a product defect (e.g. a Stop that could be replayed within the bound is left behind, or a capture is miscounted), fix it with a red row first. Be careful: wave 16c's settle2 seat is editing internal/daemon/precompact_settle.go, spool_heads.go, drain.go and daemon.go in parallel. Keep any product edit there minimal and self-contained, and describe it precisely so the coordinator can merge it.
(3) If it is the designed degrade (the bound ran out under instrumentation and co-load, and the capture is named, nothing lost), make the row's subject hold deterministically: the replay of the session's own spools before the seal. Use a fixture that gives the settle enough bound for that subject (the rig's PreCompact budget), because the bound itself is pinned by its own rows (name them). Record the criterion change. Run the row at -count=20 with -covermode=atomic locally to show it is stable.
Scope: internal/cli (precompact_spool_submode_test.go and its rig), internal/daemon only for a real defect, and their tests.` })
