const LIM16E = `Waves 16, 16b and 16c are merged into your base. Their reports are under plans/sdd/V6-closeout/w16-<ws>/, w16b-<ws>/ and w16c-<ws>/report.md. Coordinator decisions D53 and D55 in the ledger (${ROOT}/qompack-v6/plans/V6-CLOSEOUT-CHECKLIST.md) govern this wave, and Q1 applies: hosted fsync figures are never constants, and hosted fsync-bound rows report under QOMPACK_NONREFERENCE_DISK.
Hosted CI run 36905843834 (verify/v6 07a748cb = integration ae601390, before wave 16c) found these reds. Read the job logs with \`gh api repos/AidanHT/qompack/actions/jobs/<job>/logs\` (read-only); copies are in ${SCRATCH}/../ci6/ (test-win.log, reldry.log, cover.log, e2e-win.log).
Wave 16d runs in parallel: warnlate (internal/daemon/handlers.go prompt reply, internal/observer, internal/grammar statewarn, test/e2e/v5_x10_test.go) and sealrow (internal/cli/precompact_spool_submode_test.go and its rig, the cover red of TestPreCompactInSpoolSubmodeSealsTheSpooledReads). Do not edit their files.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and three other seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, no hot-path rows, and no whole test/integration or test/e2e package. Run the rows you add or touch by exact name, and each touched package in full once. No real Claude Code sessions.
Never make a row pass by raising a product budget, removing an assertion or skipping. A fixture change is acceptable only when the thing changed is not the row's subject and another row pins it. Record each one as a criterion change, with the rationale and the row that pins it.`

const WS = []

WS.push({ ws: 'settlewin', cid: 'C4.3', effort: 'high', reviewEffort: 'high', task: `TASK — hosted red: test (windows-latest), job 110516048169 (whole tree, -count=2, co-loaded on a slow hosted disk; internal/daemon took 2367 s). Three internal/daemon PreCompact settle rows from waves 16/16b failed:
  - TestPreCompactSettle_ReplaysTheSpoolBeforeTheSeal (both iterations; precompact_settle_test.go:69);
  - TestPreCompactSettle_ReplaysThisSessionsSpoolBeforeOlderOnesOfOthers (:409);
  - TestPreCompactSettle_NamesWhatTheBoundLeftUnreplayed (:108). Its actual drop entry was "0 capture(s) ... ; 2 hook client spool file(s) could not be read within the bound".
The internal/cli row TestPreCompactInSpoolSubmodeSealsTheSpooledReads failed there too; wave 16d's sealrow owns it.
${LIM16E}
(1) Confirm the cause from the log and the code. Wave 16b made every look at the spools count against precompactSettleBound (B-E minus MaxPreCompactWindow, 500 ms by default, derived from config). Under that run's co-load and disk, the first look could not even read the session's own spool files before the deadline. That is the designed, approved degrade (D55: named, nothing lost). Say whether anything else contributed: lane waits, listing, scheduling.
(2) Rows whose subject is not the bound (replay before the seal, own session first) must hold deterministically on a slow, loaded host. Give them a bound their subject cannot exhaust through the config the bound is derived from (the rig's PreCompact budget). Name the rows that pin the bound itself: the zero-bound row, the look-past-the-bound row, the cold-backlog row and the bound's derivation row.
(3) A row whose subject IS the bound (NamesWhatTheBoundLeftUnreplayed) must cut deterministically through a seam, not wall clock. Hold the replay so exactly the intended capture is left, and give the reads time enough that they are not the cut. Assert exactly what it asserts now.
(4) Sweep every other precompact_settle*_test.go and spool-watch row added in waves 16, 16b and 16c for the same wall-clock exposure (a 500 ms bound, a cold first open, a co-loaded host), and treat each the same way. List each row you judged safe, with the reason.
(5) Product check, report only: in real use, the client-spool watcher (kicked from the idle tick at most every 30 s in spool submode) should keep the backlog a settle meets small. Say whether the code bears that out on Windows, where each hook process writes its own client-<pid>.ndjson and a first open of a just-written file costs about 13 ms under real-time scanning. If you find a product defect, fix it with a red row first.
Run the touched rows at -count=10 on Windows. Run them once more with a co-load generator capped at two busy goroutines for at most 60 s, as the only exception to the no-load-generator rule, to show they hold under load.
Scope: internal/daemon tests (precompact_settle*_test.go, spool watch rows, their rigs). Product code only for a real defect, kept minimal; report it.` })

WS.push({ ws: 'hpcover', cid: 'C3.6', effort: 'high', reviewEffort: 'high', task: `TASK — hosted red: release-dry-run (ubuntu), job 110516048382. ci-local cover reports "hostperm: 88.6% line coverage < floor 90% (00-ARCHITECTURE.md §6.4)". Waves 16 and 16b added the 8.3 short-name logic (policy.go longNameAliases/shortShaped, rules.go prefixRow/literalEqual, alias_* files); wave 16c (merged into your base) added rule rows.
${LIM16E}
- Measure internal/hostperm's per-function coverage on Linux at your base (wave 16c is in), with CI's own command shape: \`go test -coverprofile=... -covermode=atomic ./internal/hostperm\`, no -count. Then raise it to at least 90 % with meaningful tests: behaviour rows for real branches, error paths through existing seams, and platform branches that run on Linux.
- No padding: no tests that only call functions without asserting their effects, no coverage-only build tags, no excluded files, no lowered floor. A function that can run only on Windows does not count on Linux; say which uncovered lines are Linux-unreachable by design.
- Measure on Linux. You may start Docker Desktop's engine (\`docker desktop start\`) and the existing container qompack-v6-linux-verification (\`docker start\`; never create, remove or reset it). Use the committed gate script plans/sdd/V6-closeout/linux/linux-nonroot-gate.sh with --prefix cx-w16e-hpcover and --no-race (read its header for the flags; pass --repo and --out as Windows-style C:/ paths), or the same non-root \`go test -coverprofile\` in CI's shape. Wave 16b's cover report (plans/sdd/V6-closeout/w16b-cover/report.md) shows both, and its review's test-log blocker shows why CI's cacheable shape matters.
- When you are done, stop the container (\`docker stop qompack-v6-linux-verification\`) and the engine (\`docker desktop stop\`): the owner needs the memory.
- Also check, from the reldry.log copy, that every other floor in that ci-local cover passed. Report before and after for hostperm, with the evidence log.
Scope: tests in internal/hostperm and its test helpers. Product code only for a real defect a new test finds; report each one.` })
