const LIM16F = `Waves 16 to 16e are merged into your base. Their reports are under plans/sdd/V6-closeout/w16*-<ws>/report.md; read the ones your task names. Coordinator decisions D53, D55 and D56 in the ledger (${ROOT}/qompack-v6/plans/V6-CLOSEOUT-CHECKLIST.md) govern this wave. This is the last wave before release candidate 6 is frozen, so keep every change minimal and contained.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and two other seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, no hot-path rows, and no whole test/integration or test/e2e package. Run the rows you add or touch by exact name, and each touched package in full once. Do NOT start Docker Desktop or the Linux container: the owner's own containers run on that engine. No real Claude Code sessions.
Other seats in this wave: rearm (internal/daemon drain.go and handlers.go, internal/observer, .github/workflows/ci.yml comment), settlekick (internal/daemon daemon.go's served-request kick and the PreCompact route, precompact_settle.go wording), hpdepth (internal/hostperm sources.go). Do not edit their files.
Never make a row pass by raising a product budget, removing an assertion or skipping. Show every new row red first, against the base or with a temporary local edit that is not committed.`

const WS = []

WS.push({ ws: 'rearm', cid: 'C3.2', effort: 'high', reviewEffort: 'high', task: `TASK — close the residual thrash-warning loss that wave 16d's warnlate left open (plans/sdd/V6-closeout/w16d-warnlate/report.md: open_issues and the review's mode-(b) finding).
${LIM16F}
(1) The window. The observer can claim a reply just inside req.TS+250 ms, yet the rendered reply reaches the hook after the hook's own give-up. The hook then spools the prompt, while the rule stays in WarnedRules: the warning counts as delivered although the host never saw it. The signal is exact. When the drain settles a client-spooled observe.prompt whose nonce the daemon already answered live (drain.go absorbs that copy without dispatch, around the code that handles a live copy that is ahead), and that live reply carried a warning, re-arm the rule the same way a refused claim does (rearmUndelivered: remove it from WarnedRules, clear the queued warning, hold the multiplicity floor). The loop then warns afresh only if it continues. Record which nonce's live reply carried a warning in memory, bounded (no new persisted format) and keyed by the nonce. Count the re-arm under the existing observer.thrash_undelivered counter, or a sibling, and log it at Info.
  Row: a deterministic seam where the claim succeeds, the reply is held until the hook has given up and spooled, then the drain absorbs the copy and the rule is re-armed; the loop continuing then warns again. Red first.
(2) internal/daemon/handlers.go: the callObservePromptWithDeadline doc block still says the replayed WAL line "for observe.prompt runs only the sentinel scan", which SP08-D3 made false. Correct it.
(3) .github/workflows/ci.yml, the test-e2e job's QOMPACK_NONREFERENCE_DISK comment: also name X10's late or deferred prompt-reply recovery branch, as internal/obs/nonrefdisk.go now lists it.
Scope: internal/daemon (drain.go, handlers.go and the prompt reply handoff), internal/observer, their tests, the ci.yml comment.` })

WS.push({ ws: 'settlekick', cid: 'C4.3', effort: 'high', reviewEffort: 'high', task: `TASK — the PreCompact settle waits behind a watcher pass that the PreCompact request itself starts (wave 16e settlewin, product check item 5 and open_issues; plans/sdd/V6-closeout/w16e-settlewin/report.md).
${LIM16F}
(1) The defect. Every served non-hot request calls noteServed (internal/daemon/daemon.go), which kicks the client-spool watcher. For the PreCompact request, that kick can start a budgeted watcher pass over every session's spools. The pass takes the drain mutex, and the settle's DrainClientSpoolsWithin then waits behind it (lockWithin), spending this session's 500 ms bound on other sessions' backlog. Confirm it with a deterministic row: a due spool of another session, a PreCompact, and the settle's replay of this session's own spool must not wait behind a pass the PreCompact itself kicked. Show it red first.
  Fix it minimally: the PreCompact route's own kick runs after the seal, not before the settle. Keep the watcher's own idle-tick and other kicks as they are. If the watcher pass is already running for another reason when the settle starts, that wait stays the designed D55 degrade: named in the drop report, nothing lost. Say so, and do not redesign the drain mutex.
(2) The unread-spools clause (precompact_settle.go unreadSpoolsClauseFormat and its doc comment). Since wave 16d (c71740c2) it also covers a spool that failed to read with an I/O or sharing error, not only one the bound ended before. Word it to cover both truthfully, e.g. "could not be read within the bound or failed to read". Update every row and doc that pins the text: grep the tree, including docs/ and the plans' section 7 text it names.
Scope: internal/daemon (daemon.go's noteServed or the PreCompact route, precompact_settle.go) and its tests, plus the docs or plans that quote the clause.` })

WS.push({ ws: 'hpdepth', cid: 'C4.6', effort: 'medium', reviewEffort: 'high', task: `TASK — fix a privacy fail-open in internal/hostperm found by wave 16e (plans/sdd/V6-closeout/w16e-hpcover/report.md, open_issues and needs_owner).
${LIM16F}
collectPermissions (internal/hostperm/sources.go, maxNesting=8 near line 43, the depth check near line 426) stops walking the server-managed cache (~/.claude/remote-settings.json) past depth 8. A permissions block nested deeper is dropped with no error, so its Read deny and ask rules are not enforced. The doc comment says "wherever its rules sit, they apply".
D56 decides the fix: no silent truncation, and no refusing everything for a deep but harmless document. Walk the whole decoded document for permissions blocks. Its size is already bounded by the source read, and its depth by encoding/json's own nesting limit. If a bound on the walk is still needed, crossing it must be a sourceError (fail closed, as for an undecodable source), never a silent drop. Remove maxNesting if nothing else needs it.
Rows, red first:
  - a permissions block 9 levels deep (and a much deeper one, e.g. 100) whose Read deny rule is enforced;
  - a deep document with no permissions block, which stays a normal, enforced policy;
  - a hooks block at depth 7 still parses.
Keep docs/security.md accurate if it describes the walk.
Scope: internal/hostperm (sources.go and its tests), docs/security.md if needed.` })
