const LIM16 = `Coordinator decision D53 in the ledger governs this wave: read it, with D45, D46, D49 and D50. The independent audit it disposes is plans/sdd/V6-closeout/audit/goal-metrics-audit.md on verify/v6 (read it at ${ROOT}/qompack-v6/plans/sdd/V6-closeout/audit/goal-metrics-audit.md). Candidate 5's overnight evidence is under ${ROOT}/qompack-v6/plans/sdd/V6-closeout/phase3/c5/ (p3-win-e2e-timing.log, linux/cx-p3-p3-linux-e2e-timing-*/, quiet/).
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and other seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, and do NOT run the hot-path rows (TestIntegration_HotPath*, TestV3_HotPath*) or whole test/integration / test/e2e packages; run the focused rows you add or touch (by exact name) and each touched package in full once. The Linux container is STOPPED: do not start it; the coordinator runs Linux verification and the whole e2e package at night. No real Claude Code sessions.
Other seats in this wave: e2erows (the three e2e rows and the store benchmark HOME leak), spoolseal (PreCompact after client spools, spool-submode wording, slow-disk docs), relhyg (bundle notices, descriptions, marketplace trigger, recall self-record prefix), ci (hosted CI reds: os/exec allow-list, macOS zombie liveness and socket paths, Q1 non-reference disk declaration, cover's TestE2EHookRoundTrip). Do not fix their items or edit their files beyond what your fix needs; if your root cause is theirs, say so and stop.`

const WS = []

WS.push({ ws: 'e2erows', cid: 'C3.4', effort: 'high', reviewEffort: 'high', task: `TASK — candidate 5's three failing e2e rows and the store benchmark HOME leak (D53(a)).
${LIM16}
Each row fails identically on Windows and Linux (phase3/c5/p3-win-e2e-timing.log lines 1-6 and 150-182). Decide each one as a stale criterion or a product defect from evidence, never by preference, and write the rationale for every criterion change in your report. A criterion change must still fail on the regression the row exists to catch: show that, for each one, by temporarily breaking the product and naming the result as a temporary diagnostic.
(1) TestDaemonIdleRunsSchedulerWork (test/e2e/scheduler_idle_test.go:186-198) requires sched counter "sources unavailable" > 0 because "a daemon that has never compacted has no ledger". D49 made "no ledger yet is not an advance_frontier error", and wave 15 ledger changed when the ledger opens (read plans/sdd/V6-closeout/w15-ledger/report.md). Find what the shipped daemon now does on an idle pass with no ledger and assert exactly that, so a regression that unwires the advancer or turns the no-ledger case back into an error still fails. Check its comment's claims (eager open, sketches/tried.bloom, which tests guard it) against the code and correct them.
(2) TestV5_ObserveToStatusRoundTrip/daemon_down_falls_back_to_persisted_snapshot: "B-A from disk: p99" expected 147456 µs, got 141000. e2e7e480 made status clamp every percentile to the snapshot's max (internal/commands/statuscollect.go:452-470). The helper x1v5RequireLatencyEquals still compares raw quantiles: apply the same clamp, keeping the "same distribution" check exact otherwise.
(3) TestV5_ObserveToStatusRoundTrip/live: two status reads of the same state differ only in the TS of hook.additional_context_delivered (1790821924508 vs ...539). The live row is right: a contract result that status or doctor refreshes from state/history.json (wave 15a snapshot, plans/sdd/V6-closeout/w15a-snapshot/report.md) must carry the time of the observation it was derived from, never the read time, so two reads of unchanged state are equal. Fix the product with a failing unit test first; the e2e row must then pass unchanged.
(4) TestV5_ThrashWarningVisibleInStatusAndCheckpoint/sequitur_warning_is_warning_only_and_once_per_rule (test/e2e/v5_x10_test.go:430-452): the arm echoes the delivered warning back as a user prompt, and since D45/D46 every user prompt reaches user_intent.evolution verbatim, so the sealed checkpoint carries the warning text as that prompt. Verbatim user prompts are a guarantee (never strip or rewrite a user's words). Narrow the assertion to what the row protects: Qompack never puts its own warning on a durable surface. The checkpoint may contain the warning text only as evolution entries that are exactly an echoed prompt, and nowhere else: not in any other field, and not attached to the prompt the warning was delivered with. Keep the elimination-record checks.
(5) The store benchmark binary exits 1 after PASS in quiet C5.2 rounds 2-4 on Windows (phase3/c5/quiet/c52-win/c52-win-r2-candidate-store-1s.log and the r3/r4 logs): "pathstest: HOME is ...\\1661447237\\001\\home at the end of the run, not the isolated home". A benchmark leaves HOME changed (b.Setenv in internal/store/bench_test.go benchStore and BenchmarkOpenStore_50kRoots, or something else). Find the leak, fix it (test code only), and prove it with the same invocation as quiet.sh's c52 store step: -test.run '^$', the same -test.bench pattern, -test.benchtime 100ms, -test.count 3. Check every other package quiet.sh benchmarks for the same pattern.
Scope: test/e2e/scheduler_idle_test.go, test/e2e/v5_x01_test.go, test/e2e/v5_x10_test.go, the contract snapshot refresh code (internal/commands and/or internal/contract), internal/store benchmark code and whatever (5) points to. Run each e2e row you touch by exact name with -count=1 (each alone; they start daemons), and the packages you change in full once.` })

WS.push({ ws: 'spoolseal', cid: 'C4.3', effort: 'high', reviewEffort: 'high', task: `TASK — a compaction never misses this session's spooled captures, and slow-disk spool submode stops looking broken (D53(c)).
${LIM16}
Background: on a disk whose fsync is slower than runtime.budgets.l0IngestMs (Linux default 15 ms; the Docker Desktop/WSL2 container measures B-B p50 ~37 ms), each hook waits at most the ACK deadline and spools a copy, and after three consecutive 512-sample breach windows the daemon moves to spool submode for the rest of the session (internal/daemon/budget.go:95-124, handlers.go:451-463; D39, D41, D44). Nothing is lost (phase3/c5/quiet/c51-linux/c51-linux.log: 3590 deferred, 0 lost). The audit (section 2.2) found two problems.
(1) Possible context gap: the PreCompact route seals without replaying the session's client spools (internal/daemon/handlers.go:1171-1230, wire_checkpoint.go:145-196); spooled captures reach the store about two watcher intervals later (spool_watch.go:44-53). Verify this first with a failing test: a compaction while this session's newest tool results sit only in a client spool, deferred or in spool submode, must seal a checkpoint and a rehydration that account for them. Fix: before sealing, PreCompact replays this session's client-spooled captures (the C1.13 session-end path does the same for SessionEnd; reuse it), bounded inside PreCompact's existing budget (B-E, the 20 s manifest timeout, compactAnswerBudget; no new number unless derived from these and named). A capture still unreplayed when the bound expires is named in the checkpoint's drop report and the payload's section 7, never silently missing. Prove that a healthy session (nothing spooled) pays nothing measurable.
(2) Spool submode must not make a healthy session look broken (D45, D41's precedent). Find every user-facing surface the transition reaches: the WARN and LOUD lines, status, doctor, the SessionStart degrade banner and the contract mode. Make the wording say what happened, that nothing is lost, what ends it, and how to tune it:
  - what happened: durable writes on this disk took longer than runtime.budgets.l0IngestMs, so hooks hand captures to the spool, which the daemon replays;
  - what ends it: a new session or the daemon's idle exit (there is no stop command);
  - how to tune it: runtime.hotPath.budgetMs, runtime.budgets.l0IngestMs and the ACK deadline key, named exactly as config-reference.md names them.
  If status or doctor reports FAILING, or the banner calls the session degraded, purely because of spool submode, make it informational but still visible. Machine-readable fields stay stable or change additively. No default number changes.
(3) docs/troubleshooting.md: a slow-disk entry (WSL2, containers, network or encrypted filesystems): the symptom, that it is expected and loses nothing, and the tuning keys. Correct any page that attributes spool submode only to a "heavily loaded" machine or names a stop command.
Scope: internal/daemon (PreCompact route, spool replay, budget/breach surfaces), internal/commands (status/doctor wording), internal/checkpoint or internal/rehydrate only for the drop entry, docs. Run the daemon rows you add or touch by name and the touched packages in full once.` })

WS.push({ ws: 'relhyg', cid: 'C7.5', effort: 'medium', reviewEffort: 'high', task: `TASK — release hygiene for a public plugin (D53(e), audit F2, F4, F8).
${LIM16}
(1) LICENSE and notices in every bundle (F4): devtool bundle (tools/devtool) and .goreleaser.yaml must ship the repo's LICENSE and THIRD_PARTY_NOTICES.md in every target's bundle and zip. THIRD_PARTY_NOTICES.md wrongly says the Go standard library is not redistributed (around lines 40-46 and 843-844): the Go runtime and standard library are compiled into every binary, so add Go's licence text (BSD-3-Clause, from the Go distribution's LICENSE) and correct the statement. Check that every statically linked module's licence is present (go-winio, klauspost/compress, golang.org/x/sys, any other in go.mod's build list for the shipped binary). Update the bundle tests, plugin-validate expectations and packaging/README.md's file list. Reproducibility must hold: two bundle builds of one target stay byte-identical (run it for windows/amd64 and linux/amd64).
(2) Accurate descriptions (F8): plugin/.claude-plugin/plugin.json's description, internal/pluginmanifest/manifest.go and tools/devtool/marketplace.go say "Cache-aware, retrieval-backed context compaction". Qompack does not compact, and the cache state is passed as unknown. Write one accurate sentence: Qompack keeps a local record of the session and restores the important parts after Claude Code compacts its context, with tools to recall anything left out. Use it everywhere it appears, regenerate generated files, and update tests and goldens to the new text (this is a text change, not a weakened check). The /qompack:pin command text says pins are "never summarized away". Pins are re-injected after a compaction within the 9,500-character cap, and nothing shields them from the summarizer: reword it to say that.
(3) .github/workflows/marketplace.yml fires only on release 'published' and skips pre-releases. Promoting a pre-release fires 'released', so the documented 'pre-release first, then promote' route would never open the marketplace pull request. Make it run exactly once for a full release, whether published directly or promoted from a pre-release, and never for a pre-release. Update docs/release.md, and add a test or lint row if the repo tests workflow files (test/release).
(4) Recall's self-record test (internal/mcp/recall_rank.go:9-22) assumes the host names tools mcp__plugin_qompack_qompack__<tool>. A release install comes from a marketplace entry named qompack-<os>-<arch>; the probe plans/sdd/V6-closeout/packaging/evidence/c7.5-marketplace/entry-name-probe.txt shows the host lists it as qompack-windows-amd64@qompack, and the tool namespace for such an entry has never been observed. Match mcp__plugin_<any entry segment>_qompack__<a Qompack retrieval tool> so both spellings rank last. Another plugin's tool, or a non-retrieval tool with a similar name, must not match: require the server segment and a known tool name. Add tests for both spellings and the negatives. Find any other code or doc that hard-codes the plugin_qompack_qompack prefix or the /qompack: command namespace, and list it in your report. Do not change docs that state the namespace: the candidate 6 live lane observes it (D53(f)).
Scope: tools/devtool (bundle, marketplace), .goreleaser.yaml, THIRD_PARTY_NOTICES.md, packaging/, plugin/, internal/pluginmanifest, internal/mcp/recall_rank.go, .github/workflows/marketplace.yml, docs/release.md, their tests.` })

WS.push({ ws: 'ci', cid: 'C7.2', effort: 'high', reviewEffort: 'high', task: `TASK — make hosted CI (C7.2) green honestly on all three OSes (D53(e), (h)).
${LIM16}
verify/v6 was pushed and ci.yml ran on candidate 5's code: run 36816905394 (https://github.com/AidanHT/qompack/actions/runs/36816905394). Read each failed job's log with \`gh run view 36816905394 --json jobs\` and \`gh api repos/AidanHT/qompack/actions/jobs/<id>/logs\` (read-only; never re-run, cancel or push). The e2e rows TestDaemonIdleRunsSchedulerWork, TestV5_ObserveToStatusRoundTrip and TestV5_ThrashWarningVisibleInStatusAndCheckpoint belong to the e2erows seat. TestCarriedDefects_WaveReportRequiresResolution (five perf rows) belongs to the coordinator's C2.8 dispositions. Everything else red is yours:
(1) security: the os/exec allow-list step fails on internal/paths/pathstest, which runs \`go env\` (a9f276e7, b763d728) to pin toolchain paths before isolating HOME. pathstest is test support like internal/testutil, which the list already allows. Add it with a comment saying why, and make the step also prove that no non-test package imports pathstest or testutil. A product package with os/exec must still fail.
(2) macOS, zombie liveness: TestShutdownDaemonUntilGone_ReadsTheHolderBeforeEachShutdown and TestShutdownDaemonUntilGone_WaitsForEveryLockHolderToExit (internal/testutil), and TestE2EShutdownIfReachable_WaitsForASpawnStillInFlight and TestE2EShutdownIfReachable_WaitsForEveryLockHolderToExit (test/e2e), see "still running" for 20 s. The process is then "reaped 121µs after the return": it is the test's own exited but unreaped child, and the liveness probe counts a zombie as alive on darwin. Fix the probe so an exited zombie counts as gone on every POSIX platform; read how Linux does it today first. Keep the guarantee these helpers exist for: never return while a live daemon still writes into the tree. Check that the product's own lock liveness (internal/daemon lock and pid checks) has no darwin zombie hole. Its daemons are detached and reaped by launchd, but confirm it and say so.
(3) macOS, socket paths: TestBackupCLI_VerifyJudgesWhatRestoreJudges (internal/cli) fails with "ipc address exceeds sun_path limit". The test's TMPDIR is a long t.TempDir() under /var/folders/..., so even the short fallback exceeds 100 bytes. TestReadBoundedObject_RefusesASocketLeaf (internal/store) fails the same way: "bind: invalid argument" for a socket under t.TempDir(). Give these fixtures a short directory on darwin (for example under /tmp, removed by t.Cleanup), and find every other test that binds a Unix socket under t.TempDir(). Confirm with a unit test of ipc.resolveFor that a typical macOS TMPDIR (/var/folders/<2>/<30>/T/) resolves within sunPathMax. If any real-user case can exceed it, report it; do not change product behaviour for it.
(4) Q1, hosted fsync-bound rows: bench-gate (ubuntu-latest B-B p50 0.58 ms but p99 41 ms; windows-latest p50 45 ms), timing (windows-latest TestIntegration_HotPathWarmWithRealResidentState) and any hosted X11 failure (test-e2e) fail on the hosted runners' fsync tail (memory of Q1: hosted figures never become constants, and hosted runners are not co-loaded, so QOMPACK_UNDER_COLOAD must NOT be used). Add one explicit declaration that a run is on a non-reference disk, for example QOMPACK_NONREFERENCE_DISK=1 or a bench-hotpath flag; follow the codebase's naming:
  - it is honoured only when GITHUB_ACTIONS=true;
  - under it, the fsync-bound wall rows (B-A, B-B and B-E's wall row) and the spool-submode transition are reported, not gated, with the reason named in the output and the JSON;
  - B-E_cpu, the delivery-ledger identity, 0 lost, the census and every structural check stay gated exactly as now;
  - ci.yml sets it in bench-gate, the timing job and test-e2e on every hosted OS, with a comment citing Q1 and D53.
  Add a guard test that the declaration is ignored outside GitHub Actions and never set by quiet.sh, phase3.sh or overnight.sh. The local isolated D28 rows and quiet C5.1 stay gated as today.
(5) cover (ubuntu-latest): TestE2EHookRoundTrip failed under coverage instrumentation ("Condition never satisfied" at test/e2e/daemon_e2e_test.go:273). Find the root cause: an instrumentation-slowed wait, or a real race. Fix it accordingly; never widen a timeout that hides a defect.
(6) lint-windows fails only stubskips: inside its whole-tree run the test/e2e binary was killed past -timeout=30m on windows-latest, so its skips were never inspected (the hosted e2e package alone takes about 25 min there, X11 390 s). Fix how stubskips runs e2e so the tree is fully inspected, without dropping any package and without the timeout hiding a hang. Then, when run 36816905394 finishes, read the windows-latest test job. Fix any further red on any OS that is none of the above and not another seat's, or report it with its cause. Check whether ci.yml's EXPECTED_FAILING_ROWS mechanism needs the carried-defect rows until the coordinator dispositions them; do not add them, say what the coordinator must do.
You cannot run hosted CI; prove each fix locally where the platform allows (GOOS=darwin vet/build for darwin code, Windows and the darwin-equivalent logic in unit tests) and say exactly what only the next hosted run can confirm.
Scope: .github/workflows/ci.yml, internal/testutil, test/e2e shutdown helpers, the darwin-affected test fixtures, internal/ipc tests, test/bench/hotpath and tools/devtool bench-hotpath (the declaration), test/integration and test/e2e hot-path rows' gating reads, test/guards for the new guard.` })
