export const meta = {
  name: 'v6-closeout-wave5-resume',
  description: 'Wave 5 close-out (resumed after a host restart): cold-start spawn lock + hook bound (D17), home-dir refusal (D18), Windows file semantics, shutdown helpers, directory-fsync redundancy (D20), dependency bumps; each reviewed, fixed and verified',
  phases: [
    { title: 'Implement', detail: 'six workstreams off closeout/integration 90e1db3' },
    { title: 'Review', detail: 'independent adversarial review' },
    { title: 'Fix', detail: 'resolve confirmed findings' },
    { title: 'Verify', detail: 'check the fix seat resolved every non-nit finding' },
  ],
}

const ROOT = 'C:/Users/Quant/Documents/Programming/Projects'
const BASE = '90e1db3'
const SCRATCH = 'C:/Users/Quant/AppData/Local/Temp/claude/C--Users-Quant-Documents-Programming-Projects-qompack/9c57653d-e5ff-4791-8ab4-ad49457994c1/scratchpad/w5'

const COMMON = (w) => `You are one of six parallel workstreams closing out the Qompack V6 verification (Qompack is a Go Claude Code plugin: hooks -> resident daemon -> content-addressed store under .qompack/, an MCP retrieval server, slash commands). Coordinator ledger (read it; do NOT edit it): ${ROOT}/qompack-v6/plans/V6-CLOSEOUT-CHECKLIST.md — owner decisions D1-D20 and the coordinator defaults are there. Earlier workstream reports are committed on your base under plans/sdd/V6-closeout/<ws>/report.md (wave 1: ingest, e2e, config, hostperm, rollover, perfstore, perfobs, eval, linux, packaging, rehydrate-cap; wave 2b: w2-*; wave 3/4: w3-startroute, w3-paths, w3-e2ereds, w3-eval3, w4-syncs, w4-e2eflakes) — read the ones relevant to your task first.

YOUR WORKTREE: ${ROOT}/qompack-cx-w5-${w.ws} on branch closeout/w5-${w.ws}, cut from closeout/integration @ ${BASE} (every earlier wave merged). The Bash tool resets cwd between calls: prefix every command with \`cd ${ROOT}/qompack-cx-w5-${w.ws} &&\` or use absolute paths. Never edit other worktrees. Never push, tag, merge, rebase or reset other branches, change git config/hooks, or SendMessage anyone. Your scratch files go under ${SCRATCH}/${w.ws}/ (create it); never delete anything else in that scratchpad.

Hard rules (owner directives, non-negotiable):
- Never weaken a check: no t.Skip, no //nolint, no //nomagic:allow added to silence something, no lowered threshold/budget, no golden regenerated to match broken output, no deleted or loosened assertion, no widened timeout that hides a defect. Criterion changes only with a written rationale in your returned report.
- Root cause first; failing regression test first; then fix.
- New budget/bound numbers are the owner's: implement them behind a named constant with a derivation comment, and list each one (value, derivation, what breaks if it is wrong) under needs_owner; the coordinator gets approval before merging.
- Commits: conventional \`type(scope): subject\` (lowercase scope, subject <=64 chars, no trailing period), body lines <=100 chars, \`Refs: V6-VERIFY, ${w.cid}\` footer on feat/fix, NO attribution trailers (no Co-Authored-By, Signed-off-by, Claude-Session, "Generated with", robot emoji) — the commit-msg hook rejects them. Small focused commits. Evidence logs may be committed under plans/sdd/V6-closeout/w5-${w.ws}/runs/.
- \`go run ./tools/devtool fmt\`/\`fmt-check\`, \`go vet\` on touched packages (Windows and GOOS=linux); \`go test ./test/docs\` and gen-*-docs --check when docs/generated inputs change. Use \`go run ./tools/devtool lint --only=golangci-lint,nomagic,importgraph,testdeps,bindeps,sleepcheck,docmarkers,runpatterns\`: never the stubskips sub-check (it runs a whole-tree go test).
- Tests: FOCUSED runs plus each touched package once in full; never ./... or devtool test/test-race (five other workstreams run tests on this machine and in the Linux container at the same time, so the machine is loaded: re-run any wall-clock failure alone before believing it, and say so). Never let a pipe mask go test's exit code.
- Every \`go test -run\` pattern you quote in your report must match a real test name exactly (the runpatterns lint checks committed reports); name temporary diagnostics as such.
- Processes: never kill a process you did not start. If you must stop your own processes, match on YOUR worktree path or your own scratch subdirectory.
- Linux: container \`qompack-v6-linux-verification\`; the committed script plans/sdd/V6-closeout/linux/linux-nonroot-gate.sh runs an exact commit non-root with -race (see its header; use --prefix cx-w5-${w.ws}; pass --repo and --out as Windows-style C:/ paths, a POSIX /c/ path is refused); never reuse or delete other /work dirs.
- Never create, read or modify the real ~/.qompack or ~/.claude in tests; use a fake HOME/USERPROFILE. Real Claude Code sessions are NOT allowed.
- The harness refuses report files from subagents: do NOT write report.md. Return the full report (root causes with evidence, what changed, exact commands + results, criterion changes, open items, owner decisions) in your returned summary; the coordinator commits it.`

const DIGEST = 'C:/Users/Quant/AppData/Local/Temp/claude/C--Users-Quant-Documents-Programming-Projects-qompack/9c57653d-e5ff-4791-8ab4-ad49457994c1/scratchpad/resume'
const NOTES = {
  coldstart: 'The earlier seat had made no commits; it left uncommitted edits in internal/daemon/spawn.go and internal/ipc/client.go and new files internal/ipc/spawnlock.go, spawnlock_test.go, spawnlock_claim_test.go and internal/daemon/spawn_lock_test.go, and was instrumenting the drain and running red tests on the pre-fix tree when it stopped. Any temporary instrumentation it added to product code must not survive: check git diff line by line.',
  home: 'The earlier seat committed bb9b5a7 (paths.IsHome) and left untracked internal/cli/homeroot.go, homeroot_test.go and internal/mcp/refused.go; it was writing the real implementation when it stopped.',
  winfiles: 'The earlier seat committed 0c7a699 (backup of deep projects through logical paths) and left an edit in test/guards/sharedreaders_test.go and a new internal/contract/marker_windows_test.go; it was about to run the guard and contract tests red before the readMarker fix. Items (c) and (d) and the full runs were not done.',
  helpers: 'The earlier seat committed 919b0fb (one definition of gone in testutil) and left edits in six test/e2e files plus an untracked DIAGNOSTIC test/fault/zz_diag_w5_shutdown_test.go (never commit a diagnostic; keep its source as evidence under runs/ as a .txt if you rely on it); it was rewriting the fault helper. Items (b), (c) and the full runs were not done.',
  dirsync: 'The earlier seat committed 2ff7ccb, 3412869 and 658a806 (barrier counter, one fsync per directory per pass, presized set) and left uncommitted edits in internal/daemon/delivery_generation.go and delivery_segment.go plus a new internal/daemon/delivery_dirsync_test.go (item (3) applied to delivery segments) and evidence files under runs/; it was running a RED check through a temporary copy of the pre-fix code. The A/B measurements were not done.',
  deps: 'The earlier seat committed 5023c12 (klauspost/compress v1.18.7) and left uncommitted go.mod, go.sum and THIRD_PARTY_NOTICES.md edits (presumably the x/mod upgrade); it was starting the full package runs. Re-verify everything.',
}
const RESUME = (w) => `RESUMING — read this first. This workstream started 2026-09-26 17:11 and was killed at 17:45 when the host was restarted (not a failure of the work). The earlier seat's work is preserved in your worktree and has NOT been reviewed: commits ${BASE}..HEAD plus uncommitted and untracked files. A chronological digest of its tool calls and narration is at ${DIGEST}/w5-${w.ws}.txt; read it to learn what it found and where it stopped. ${NOTES[w.ws]}
Before anything else: \`git log --oneline ${BASE}..HEAD\`, \`git status\`, \`git diff\`. Treat the earlier commits and edits as a colleague's unreviewed draft: keep, revise or revert each one deliberately (prefer new commits). Evidence from before the restart is partial: re-run everything you rely on at your final HEAD. The Linux container restarts with Docker Desktop after the reboot; if \`docker exec qompack-v6-linux-verification true\` fails, wait for Docker (poll for up to 10 minutes) and run \`docker start qompack-v6-linux-verification\` if the container is stopped; never create, remove or reset the container. Then finish the whole task below.`

const WS = []

WS.push({ ws: 'coldstart', cid: 'C1.16/D17', task: `TASK — cold start (owner decision D17). Read plans/sdd/V6-closeout/w3-startroute/report.md (item (3), runs/15, runs/50, runs/51 and the cold-start diagnostic runs/zz_startroute_coldstart_diag_test.go.txt) and plans/sdd/V6-closeout/w2-lifetime/report.md first.
(1) D17a: EnsureRunning must honour a FRESH spawn lock: when another hook has just spawned this project's daemon, wait for that daemon instead of spawning a second one. Establish today's behaviour with a failing test first (e.g. two concurrent cold hooks on one project, or a hook arriving while a staged-copy spawn is still starting). Define "fresh" so a crashed spawner's lock cannot block forever (fail safe to spawning after a bound), and keep the Windows staged-copy path (D10) and MCP lazy spawn on the same rule.
(2) Root-cause the NOUP row: under full CPU co-load one daemon took daemon.lock and wrote state.bin, then could not be dialled for 30 s and was gone from the process list (w3-startroute runs/50). Is it a second daemon losing a race and exiting, a listener that never came up, a startup that exceeded a bound and exited, or something else? A product defect is presumed until evidence says otherwise; fix at the source with a regression test.
(3) D17b: bound session-start's pre-send step (staging + EnsureRunning poll + connect) so the WHOLE hook ends inside the 15 s manifest timeout together with the 10 s reply deadline (one co-load row took 21.2 s; a staged-cold start reached 13.4 s). Derive the split, implement it behind named constants, and send the numbers to the owner (needs_owner). Whatever is cut short must degrade the way a missed start already does (spool / probe loss / the D9 deferred note for compact), never hang or break the host.
Measure before/after under CPU co-load with the diagnostic (copied temporarily, never committed): spool rate per source (startup/resume/compact, staged-cold vs warm) and whole-hook wall time distribution.
Scope: internal/cli (EnsureRunning, spawn, staging, the session-start hook client), internal/daemon startup only if (2) proves a daemon defect, internal/mcp lazy spawn, tests, docs (architecture, troubleshooting). Coordinate: w5-home adds a home-directory refusal at hook/command entry (keep your hook-entry edits minimal); w5-winfiles edits internal/paths guard code and internal/contract.` })

WS.push({ ws: 'home', cid: 'C3.5/D18', task: `TASK — refuse the home directory as a project root (owner decision D18). Read plans/sdd/V6-closeout/w3-paths/report.md (its "Needs the owner" item on paths.Resolve) first.
Today paths.Resolve walks up for .git and otherwise takes the working directory, so a session started in the home directory itself, or below a home that is a git work tree (a dotfiles repo), resolves the project root to home, and the project store becomes ~/.qompack — the user-global layer's own directory (config, calibration, fallback log, the D10 staged daemon copies under ~/.qompack/bin).
D18: when the resolved project root IS the user's home directory (compare after cleaning; case-insensitive on Windows; junction/symlink aware; also when QOMPACK_PROJECT_ROOT names home), Qompack records nothing for that session and says why. Required behaviour, each pinned by tests with a fake home (never the real one):
- all seven hooks exit 0, create nothing under ~/.qompack that a project store would create (no run/, index/, objects/, state/, checkpoints/, spool, daemon.lock), and start no daemon;
- SessionStart answers with ONE short host message (systemMessage, far under the host caps; see D15's ceilings) saying Qompack is inactive in the home directory and how to fix it (open a project directory); the other hooks stay silent;
- the MCP server's tools return a clear, stable error; status and doctor say why; fsck/backup/other commands refuse cleanly with a non-zero exit where they would otherwise touch the store;
- a project BELOW home with its own .git, or a non-git directory below home, still works exactly as before (regression rows);
- the user-global layer keeps working (config load, calibration, staged copies).
Decide where the check lives (one function, e.g. in internal/paths next to Resolve, used by every entry point) and audit every entry point that resolves a project root. Docs: architecture §3.3, install/user-guide/troubleshooting/cannot-do; if Qompack.md itself defines the resolution order, add a Revision-log entry citing owner decision D18 (that decision authorizes the revision) rather than leaving it contradicted.
Scope: internal/paths (Resolve), internal/cli hook entry and commands, internal/mcp, internal/daemon start guard, docs, tests. Coordinate: w5-coldstart edits internal/cli EnsureRunning/spawn/session-start client; w5-winfiles edits internal/paths appendonly guard and internal/config loaders.` })

WS.push({ ws: 'winfiles', cid: 'C1.7/C3.2', task: `TASK — four Windows file-semantics defects routed by wave 3/4. Read plans/sdd/V6-closeout/w3-paths/report.md and plans/sdd/V6-closeout/w4-e2eflakes/report.md first.
(a) Backup long paths (C1.7, V6-RECOVERY-2): \`qompack backup create\` fails when the project's .qompack path exceeds ~240 chars on Windows. TakeBackup walks paths.Long(Dot), so walked paths carry the \\\\?\\ prefix, while maintNoFollow does filepath.Rel against the unprefixed m.root (w3-paths runs/15, runs/16; two TestBackupCLI rows fail from path length). Fix at the source with deep-path regression tests, and check every other maintenance walk (backup verify/restore, fsck, GC, rollover) for the same prefixed/unprefixed mismatch.
(b) contract.readMarker (internal/contract/marker.go) reads run/marker.json with os.ReadFile; checkSessionStartFires calls it and \`qompack selftest\` (internal/cli/selftest.go) can reach it from another process. On Windows that read can make the daemon's WriteMarker replace fail, and it is never retried. Fix at the source (the repository's shared-read helper, paths.ReadFileShared), add it to test/guards' sharedReaders, and audit EVERY product reader of a file the daemon or store replaces atomically (state/*.json, run/*, index and delivery files, config) for the same class; fix each and make the guard's list complete.
(c) Coordinator default: the §7.4 protected-path guard (paths.IsProtected / mayBeProtected in internal/paths/appendonly.go) compares protected names case-sensitively, so on Windows WriteAtomic(<root>\\.qompack\\CHECKPOINTS\\0001.json) replaces a sealed checkpoint and OpenFile(<root>\\.qompack\\PINS\\invariants.jsonl, O_TRUNC) empties the pins log (w3-paths runs/fix/03, runs/fix/04). Fold case on case-insensitive filesystems (always on Windows; on darwin conservatively), with regression tests; document Windows 8.3 short names and ::$DATA stream suffixes as out of scope for a textual guard unless handling them is cheap and safe.
(d) internal/config/load.go and capture_load.go hand-join HomeDir with ".qompack"; name the user-global root through paths.Global if the import graph allows (importgraph lint), else say why.
Scope: internal/paths (appendonly guard only; w5-home owns Resolve), internal/store maintenance/backup, internal/contract, internal/cli selftest, internal/config, test/guards, docs. Coordinate: w5-home edits paths.Resolve and entry points; w5-coldstart edits internal/cli spawn code; w5-dirsync edits internal/store publication sync.` })

WS.push({ ws: 'helpers', cid: 'C3.2', task: `TASK — test-harness items that make the final whole-tree gates trustworthy. Read plans/sdd/V6-closeout/w4-e2eflakes/report.md and plans/sdd/V6-closeout/w4-syncs/report.md first.
(a) Port test/e2e's e2eLockHolders definition of "gone" (lock-holder checks before and after each Send, tracking of unidentified holders, and pid 0 — an empty lock caught mid-create — is NOT settled) to the sibling daemon-shutdown helpers, which still take one pid read: test/fault/fault.go (~948, ~1082), test/platform/platform.go (~1131, ~1162), test/release/release.go (~781, ~818), test/security/security.go (~1221, ~1288), test/guards/v1_integration_test.go (~942). Prefer ONE shared helper (e.g. in internal/testutil) if the testdeps/importgraph rules allow, so there is a single definition; add a regression test for the spawn-in-flight case.
(b) internal/daemon/observer_atomic_publication_test.go: atomicFaultStore's doc comment claims to cover "the write path production actually takes", but the row is unleased (no nonce) and the wrapper cannot carry a leased delivery. Either give the row a nonce and forward ObservationRecovery/PublicationSync so it truly covers the leased path, or correct the comment; prefer real coverage.
(c) test/e2e/v4_x13_test.go: the x13 Received count relies on a spelled counter name (hotpath_sample_invalid) and a B-A histogram looked up from obs.Budgets(); a rename would make it undercount silently. Make a missing counter/histogram fail the row loudly.
Run every touched package once in full on Windows and on Linux via the script (test/e2e on Linux with --timeout 150m), and report every row.
Scope: internal/testutil, test/*, that one internal/daemon test file. Do not change product code.` })

WS.push({ ws: 'dirsync', cid: 'C2.3/SP08-D1/D20', task: `TASK — SP08-D1 pure-redundancy removal (owner decision D20: keep the FULL post-write re-proof; only pure redundancy may go; the index-only post-write pass and an in-process proven-object cache were REJECTED, do not implement them). Read plans/sdd/V6-closeout/w4-syncs/report.md (its durability property table and its proposals), plans/sdd/V6-closeout/perfstore/report.md and plans/CARRIED-DEFECTS.tsv (SP08-D1) first.
Within one SyncPublication pass the store fsyncs a directory once per object: the objects/ root about 34 times for a 34-object root, about 102 directory fsyncs per pass. A directory fsync persists every entry created in that directory before the call, so one fsync per distinct directory, issued after every entry that must be durable in it is in place and before the step that depends on it, is equivalent. (1) Prove that equivalence against the property table (what must be durable before the ACK, before the tool_use line is visible, before the capture link, before the file-version record); if any ordering constraint makes a per-object directory fsync load-bearing, keep it and say why. (2) Implement it; pin the new per-pass and per-capture fsync counts with the existing counting seam (not timing); every crash sweep (including internal/observer/publication_sweep_test.go) and every publication/fault/integration row stays green unchanged. (3) Look for the same per-object directory-fsync pattern in other store writes (PutBytes, checkpoint Finalize, negknow Open/append, delivery segments) and apply it only where the same proof holds. (4) Establish what a directory fsync actually does on Windows in this code (Go's File.Sync on a directory handle) and report it. (5) Measure: fsync counts per 256 KB leased capture before/after, allocs/op, B/op, and paired interleaved A/B timing of BenchmarkOnToolUse_TestOutput256KB_Leased and its Deduped/Delta/AllNovel variants (-count >= 10 per side, ABBA, Windows and Linux via the script) reported only as paired ratios with a sign test; absolute timings on this loaded host are not budget evidence. Do not change any budget constant or CARRIED-DEFECTS status.
Scope: internal/store (publication sync and the other writers in (3)), internal/observer tests/benchmarks, docs/architecture.md durability text if it names the passes. Coordinate: w5-winfiles edits internal/store maintenance/backup walks.` })

WS.push({ ws: 'deps', cid: 'C3.7', task: `TASK — dependency hygiene before the release gates. The pinned govulncheck (\`go run -modfile=tools/pinned/go.mod golang.org/x/vuln/cmd/govulncheck ./...\`) lists two module-level findings that are not called: github.com/klauspost/compress v1.18.0 (GO-2026-5841, fixed in v1.18.7; it IS in the shipped binary through zstd) and golang.org/x/mod v0.25.0 (GO-2026-6180, GO-2026-6179, fixed in v0.40.0; indirect — find out which package pulls x/mod/semver and whether it reaches the shipped binary).
Upgrade both to the fixed versions and only what they require; if a fixed version needs a newer Go toolchain than go.mod's (Go 1.26.6) or forces API changes beyond a trivial rename, stop and report instead. Then: go mod tidy and go mod verify; \`go run ./tools/devtool licenses --check\` (regenerate THIRD_PARTY_NOTICES.md with \`licenses --write\` if required); the pinned govulncheck; \`go run ./tools/devtool build-all\`; bindeps and importgraph lint; full test runs of every package that imports klauspost/compress or x/mod (find them with go list -deps) on Windows and on Linux via the script; and prove bundle reproducibility still holds: \`go run ./tools/devtool bundle --target windows/amd64 --target linux/amd64\` twice into two scratch dirs and compare every file byte for byte. Record binary size before/after.
Scope: go.mod, go.sum, THIRD_PARTY_NOTICES.md, and only code changes the upgrades force.` })

const RESULT = { type: 'object', properties: {
  status: { type: 'string', enum: ['done', 'partial', 'blocked'] }, head: { type: 'string' },
  commits: { type: 'array', items: { type: 'string' } }, root_cause: { type: 'string' }, summary: { type: 'string' },
  tests: { type: 'array', items: { type: 'object', properties: { command: { type: 'string' }, result: { type: 'string' } }, required: ['command', 'result'] } },
  criterion_changes: { type: 'array', items: { type: 'string' } }, open_issues: { type: 'array', items: { type: 'string' } },
  needs_owner: { type: 'array', items: { type: 'string' } },
}, required: ['status', 'head', 'commits', 'summary', 'tests', 'open_issues', 'needs_owner'] }
const FINDINGS = { type: 'object', properties: {
  verdict: { type: 'string', enum: ['sound', 'needs-fixes', 'unsound'] },
  findings: { type: 'array', items: { type: 'object', properties: {
    severity: { type: 'string', enum: ['blocker', 'major', 'minor', 'nit'] }, location: { type: 'string' },
    issue: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' },
  }, required: ['severity', 'location', 'issue', 'evidence', 'fix'] } },
}, required: ['verdict', 'findings'] }

const LENS = 'Lenses: (a) root cause proven and fixed at the source; correctness incl. concurrency (races, deadlocks, lock order, goroutine leaks), durability/crash semantics (fsync ordering, WAL retention, idempotency, identity never re-minted), fail-closed paths, Windows vs POSIX, bounded memory/CPU; (b) check-weakening (deleted/loosened assertions, skips, nolint/nomagic, lowered thresholds, regenerated goldens, widened timeouts, tests bent to buggy output) and legitimacy of every criterion change; (c) every new bound/budget number is named, derived, and listed for the owner; (d) docs consistent with behaviour, generated docs via generators; (e) commit hygiene (conventional subjects, Refs footer, no attribution trailers); (f) was the whole task done, or parts silently dropped?'

const results = await pipeline(
  WS,
  (w) => agent(`${COMMON(w)}\n\n${RESUME(w)}\n\n${w.task}`, { label: `impl:${w.ws}`, phase: 'Implement', schema: RESULT }),
  async (impl, w) => {
    if (!impl) return { w, impl: null, review: null }
    const review = await agent(`You are an independent, adversarial reviewer for Qompack V6 close-out wave-5 workstream "${w.ws}" (${w.cid}). Worktree ${ROOT}/qompack-cx-w5-${w.ws}, branch closeout/w5-${w.ws}, base ${BASE}. The task was:\n---\n${w.task}\n---\nImplementer result: ${JSON.stringify(impl)}\nReview \`git -C ${ROOT}/qompack-cx-w5-${w.ws} log ${BASE}..HEAD\` and the full diff \`git diff ${BASE} HEAD\`. READ-ONLY: do not edit, commit, stash or reset. You may run focused tests (never ./...; never kill processes you did not start; the machine is loaded — re-run a timing failure alone before believing it). No real claude sessions; never touch the real ~/.qompack or ~/.claude.\n${LENS}\nReturn findings with severity, file:line, evidence and a concrete fix; if sound, verdict "sound" and an empty list.`,
      { label: `review:${w.ws}`, phase: 'Review', schema: FINDINGS, effort: 'high' })
    return { w, impl, review }
  },
  async (r) => {
    if (!r.impl) return { w: r.w, ws: r.w.ws, impl: null, review: null, final: null }
    const actionable = (r.review ? r.review.findings : []).filter((f) => f.severity !== 'nit')
    if (actionable.length === 0) return { w: r.w, ws: r.w.ws, impl: r.impl, review: r.review, final: r.impl, fixRan: false, actionable }
    const final = await agent(`${COMMON(r.w)}\n\nYou are the FIX seat for this workstream (the implementer has finished). Its task was:\n---\n${r.w.task}\n---\nIndependent reviewer findings:\n${JSON.stringify(actionable, null, 1)}\nVerify each independently; fix the correct ones (failing test first where applicable) and re-run focused tests; rebut wrong ones with evidence. Blockers/majors must be resolved or rebutted. Return the final state with a "Review resolution" section (finding -> action/rebuttal) in your summary, and carry forward every needs_owner item still open (the implementer's were: ${JSON.stringify(r.impl.needs_owner || [])}).`,
      { label: `fix:${r.w.ws}`, phase: 'Fix', schema: RESULT })
    return { w: r.w, ws: r.w.ws, impl: r.impl, review: r.review, final, fixRan: true, actionable }
  },
  async (r) => {
    if (!r.fixRan || !r.final) return { ws: r.ws, impl: r.impl, review: r.review, final: r.final, fixRan: !!r.fixRan, verify: null }
    const verify = await agent(`You are an independent verifier for Qompack V6 close-out wave-5 workstream "${r.ws}". Worktree ${ROOT}/qompack-cx-w5-${r.ws}, branch closeout/w5-${r.ws}. A reviewer raised these findings:\n${JSON.stringify(r.actionable, null, 1)}\nThe fix seat's result: ${JSON.stringify(r.final)}\nFor EACH finding decide whether it is now resolved correctly or rebutted soundly, by reading the code at HEAD and the fix commits (\`git -C ${ROOT}/qompack-cx-w5-${r.ws} log ${r.impl.head}..HEAD\`), and check the fix commits introduced no new defect or check-weakening. READ-ONLY: do not edit, commit, stash or reset; focused tests allowed (never ./...; never kill processes you did not start; never touch the real ~/.qompack or ~/.claude). Return as findings ONLY what is still wrong (unresolved, badly rebutted, or newly introduced), with severity, file:line, evidence and fix; verdict "sound" with an empty list if everything is resolved.`,
      { label: `verify:${r.ws}`, phase: 'Verify', schema: FINDINGS, effort: 'high' })
    return { ws: r.ws, impl: r.impl, review: r.review, final: r.final, fixRan: true, verify }
  },
)
return results
