export const meta = {
  name: 'v6-closeout-wave16f',
  description: 'Wave 16f close-out (last before candidate 6): thrash-warning re-arm on an absorbed answered prompt, PreCompact kick after the seal, hostperm deep permissions walk; reviewed, fixed and verified',
  phases: [
    { title: 'Implement', detail: 'three workstreams off closeout/integration 8fe6c1f4' },
    { title: 'Review', detail: 'independent adversarial review' },
    { title: 'Fix', detail: 'resolve confirmed findings' },
    { title: 'Verify', detail: 'check the fix seat resolved every non-nit finding' },
  ],
}

const ROOT = 'C:/Users/Quant/Documents/Programming/Projects'
const BASE = '8fe6c1f4'
const SCRATCH = 'C:/Users/Quant/AppData/Local/Temp/claude/C--Users-Quant-Documents-Programming-Projects-qompack/9c57653d-e5ff-4791-8ab4-ad49457994c1/scratchpad/w16f'

const COMMON = (w) => `You are one of the parallel workstreams (wave 16f: rearm, settlekick, hpdepth) closing out the Qompack V6 verification (Qompack is a Go Claude Code plugin: hooks -> resident daemon -> content-addressed store under .qompack/, an MCP retrieval server, slash commands). Coordinator ledger (read it; do NOT edit it): ${ROOT}/qompack-v6/plans/V6-CLOSEOUT-CHECKLIST.md — owner decisions D1-D49 and the coordinator defaults are there. Earlier workstream reports are committed on your base under plans/sdd/V6-closeout/<ws>/report.md (wave 1: ingest, e2e, config, hostperm, rollover, perfstore, perfobs, eval, linux, packaging, rehydrate-cap; wave 2b: w2-*; wave 3/4: w3-startroute, w3-paths, w3-e2ereds, w3-eval3, w4-syncs, w4-e2eflakes; wave 5: w5-coldstart, w5-home, w5-winfiles, w5-helpers, w5-dirsync, w5-deps; wave 6: w6-borrow, w6-config, w6-ckptsync, w6-gcserial, w6-linuxrows; wave 7: w7-spawnclaim, w7-layout, w7-sp08d3, w7-docs, w7b-selftest, w7b-checkpoint; wave 8: w8-sp08d3fix, w8-stagerace, w8b-polish) — read the ones relevant to your task first.

YOUR WORKTREE: ${ROOT}/qompack-cx-w16f-${w.ws} on branch closeout/w16f-${w.ws}, cut from closeout/integration @ ${BASE} (every earlier wave merged). The Bash tool resets cwd between calls: prefix every command with \`cd ${ROOT}/qompack-cx-w16f-${w.ws} &&\` or use absolute paths. Never edit other worktrees. Never push, tag, merge, rebase or reset other branches, change git config/hooks, or SendMessage anyone. Your scratch files go under ${SCRATCH}/${w.ws}/ (create it); never delete anything else in that scratchpad.

Hard rules (owner directives, non-negotiable):
- Never weaken a check: no t.Skip, no //nolint, no //nomagic:allow added to silence something, no lowered threshold/budget, no golden regenerated to match broken output, no deleted or loosened assertion, no widened timeout that hides a defect. Criterion changes only with a written rationale in your returned report.
- Root cause first; failing regression test first; then fix.
- New budget/bound numbers are the owner's: implement them behind a named constant with a derivation comment, and list each one (value, derivation, what breaks if it is wrong) under needs_owner; the coordinator gets approval before merging.
- Commits: conventional \`type(scope): subject\` (lowercase scope, subject <=64 chars, no trailing period), body lines <=100 chars, \`Refs: V6-VERIFY, ${w.cid}\` footer on feat/fix, NO attribution trailers (no Co-Authored-By, Signed-off-by, Claude-Session, "Generated with", robot emoji) — the commit-msg hook rejects them. Small focused commits. Evidence logs may be committed under plans/sdd/V6-closeout/w16f-${w.ws}/runs/.
- \`go run ./tools/devtool fmt\`/\`fmt-check\`, \`go vet\` on touched packages (Windows and GOOS=linux); \`go test ./test/docs\` and gen-*-docs --check when docs/generated inputs change. Use \`go run ./tools/devtool lint --only=golangci-lint,nomagic,importgraph,testdeps,bindeps,sleepcheck,docmarkers,runpatterns\`: never the stubskips sub-check (it runs a whole-tree go test).
- Tests: FOCUSED runs plus each touched package once in full; never ./... or devtool test/test-race (four other workstreams run tests on this machine and in the Linux container at the same time, so the machine is loaded: re-run any wall-clock failure alone before believing it, and say so). Never let a pipe mask go test's exit code.
- Every \`go test -run\` pattern you quote in your report must match a real test name exactly (the runpatterns lint checks committed reports); name temporary diagnostics as such.
- Processes: never kill a process you did not start. If you must stop your own processes, match on YOUR worktree path or your own scratch subdirectory.
- Linux: container \`qompack-v6-linux-verification\`; the committed script plans/sdd/V6-closeout/linux/linux-nonroot-gate.sh runs an exact commit non-root with -race (see its header; use --prefix cx-w16f-${w.ws}; pass --repo and --out as Windows-style C:/ paths, a POSIX /c/ path is refused); never reuse or delete other /work dirs.
- CPU: the owner uses this laptop interactively. Any load generator you start must be bounded with \`timeout\` to at most 20 minutes per run and at most 8 busy processes (of 22 cores), and you must stop it when the measurement ends; never leave one running. Stop your own background diagnostics before you finish.
- Never create, read or modify the real ~/.qompack or ~/.claude in tests; use a fake HOME/USERPROFILE. Real Claude Code sessions are NOT allowed.
- The harness refuses report files from subagents: do NOT write report.md. Return the full report (root causes with evidence, what changed, exact commands + results, criterion changes, open items, owner decisions) in your returned summary; the coordinator commits it.`

const MACHINE = `MACHINE LIMITS FOR THIS SEAT (override the general rules): Phase 3 gates run on this laptop now and memory is tight. The Linux container is STOPPED on purpose: do NOT start it and do not run the Linux gate script; the coordinator runs Linux verification later. On Windows use \`-p 2\`, no load generators. The Phase 3 chain logs to C:/Users/Quant/Documents/Programming/Projects/qompack-v6/plans/sdd/V6-closeout/phase3/chain-2.log: while that file has a "win-timing start" line with no later "win-timing exit" line, an ISOLATED timing gate is running and you must not run anything load-bearing (no hot-path row, no test/integration package, no -race, no benchmark) until it ends; do code reading and cheap deterministic unit tests meanwhile. Run at most one load-bearing test at a time.`

const EV = `EVIDENCE: the Phase 4 live lane ran real Claude Code 2.1.280 sessions on the frozen candidate 3 (d5598eb4) with the packaged bundle. Its report is plans/sdd/V6-closeout/live/report.md in your worktree (evidence dirs beside it under plans/sdd/V6-closeout/live/uat/, c4/, recovery/). Read the rows named below and their evidence files before touching code. Coordinator decision D45 (ledger) says these are fixed before 0.3.0.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and six seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, and do NOT run the hot-path rows (TestIntegration_HotPath*, TestV3_HotPath*) or whole test/integration / test/e2e packages; run only the focused rows you add or touch plus the touched packages in full once. The Linux container is STOPPED: do not start it. Real Claude Code sessions are NOT allowed: reproduce each live finding with a deterministic test (a real daemon/store/hook process in a temp project is fine) that is RED before the fix. The coordinator re-runs the live rows on the fixed candidate.
Other seats in this wave (do not fix their items; if your root cause turns out to be theirs, say so and stop): ledger (elimination ledger, MCP self-record turns, timeline), intent (rehydration intent/corrections/fork), restore (backup/restore/fsck segments/cross-version), pinsckpt (pins view, checkpoint pointers), diag (sentinel scan, status/doctor diagnostics), mcpresp (MCP response bounds/selectors/messages, UAT docs).`

const LIM = `MACHINE LIMITS FOR THIS SEAT (override the general rules): three seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, and do NOT run the hot-path rows (TestIntegration_HotPath*, TestV3_HotPath*) or whole test/integration / test/e2e packages; run the focused rows you add or touch and the touched packages in full once. The Linux container is STOPPED: do not start it. No real Claude Code sessions: reproduce with deterministic tests that are RED before the fix. Read coordinator decision D46 in the ledger. Other seats: observer, decisions, safecut.`

const LIM15_UNUSED = `EVIDENCE: the live re-run on candidate 4 (9f6a2fad, decision D47) ran real Claude Code sessions with the frozen bundle. Its evidence is committed on your base under plans/sdd/V6-closeout/live/rerun-c4/<row>/ and the Result blocks in docs/uat.md; the findings named below come from there. Coordinator decision D49 in the ledger says every one is fixed before 0.3.0 and fixes each disposition: read D45, D46 and D49 first.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and four seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, and do NOT run the hot-path rows (TestIntegration_HotPath*, TestV3_HotPath*) or whole test/integration / test/e2e packages; run the focused rows you add or touch and the touched packages in full once. The Linux container is STOPPED: do not start it. No real Claude Code sessions: reproduce each finding with a deterministic test (a real daemon/store/hook process in a temp project is fine) that is RED before the fix.
Other seats: rehydrate (fallback visibility, evolution admission, eviction order), ledger (stale bloom, advance_frontier, decisions across checkpoints, fork inheritance), services (config reload, recall k, publication accounting, fsck index.files), docs. Do not fix their items; if your root cause is theirs, say so and stop.`

const LIM15A_UNUSED = `EVIDENCE: the candidate 4 live re-run's audit (plans/sdd/V6-closeout/live/report-c4.md, section "Independent audit") and its evidence under plans/sdd/V6-closeout/live/rerun-c4/ are on your base. Coordinator decision D50 in the ledger fixes the dispositions: read D45, D46, D49 and D50 first.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and six seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, and do NOT run the hot-path rows (TestIntegration_HotPath*, TestV3_HotPath*) or whole test/integration / test/e2e packages; run the focused rows you add or touch and the touched packages in full once. The Linux container is STOPPED: do not start it. No real Claude Code sessions: reproduce with deterministic tests that are RED before the fix.
Other seats running now: wave 15 rehydrate (internal/rehydrate), ledger (internal/negknow, checkpoint decisions), services (daemon config reload, mcp recall in handlers.go, store publication accounting, fsck index.files), docs; and paging / snapshot in this wave. Do not fix their items or edit their files beyond what your fix needs; if your root cause is theirs, say so and stop.`

const LIM15B_UNUSED = `EVIDENCE: the candidate 4 live re-run's audit (plans/sdd/V6-closeout/live/report-c4.md, section "Independent audit") and its evidence under plans/sdd/V6-closeout/live/rerun-c4/ are on your base, with wave 15 (docs, ledger) and wave 15a (paging, snapshot) merged. Coordinator decision D50 in the ledger fixes the dispositions: read D46, D49 and D50 first.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and other seats run at once. Use \`-p 2\`, no load generators, no hot-path rows, no whole test/integration or test/e2e packages. The Linux container is STOPPED: do not start it. No real Claude Code sessions.
Other seats running now: wave 15 rehydrate (internal/rehydrate) and services (daemon reload, mcp recall, store publication accounting, fsck). Do not edit their files.`

const LIM15C = `Coordinator decisions D49 and D51 in the ledger govern this task: read them. The wave 15 services report is on your base: plans/sdd/V6-closeout/w15-services/report.md (its needs_owner and open issues are the source of this task).
MACHINE LIMITS FOR THIS SEAT (override the general rules): the owner is using this laptop and another seat runs. Use \`-p 2\`, no load generators except the bounded measurement below, no hot-path rows, no whole test/integration or test/e2e. The Linux container is STOPPED: do not start it. No real Claude Code sessions.
Other seat running now: wave 15 rehydrate (internal/rehydrate). Do not edit its files.`

const LIM16 = `Coordinator decision D53 in the ledger governs this wave: read it, with D45, D46, D49 and D50. The independent audit it disposes is plans/sdd/V6-closeout/audit/goal-metrics-audit.md on verify/v6 (read it at ${ROOT}/qompack-v6/plans/sdd/V6-closeout/audit/goal-metrics-audit.md). Candidate 5's overnight evidence is under ${ROOT}/qompack-v6/plans/sdd/V6-closeout/phase3/c5/ (p3-win-e2e-timing.log, linux/cx-p3-p3-linux-e2e-timing-*/, quiet/).
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and other seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, and do NOT run the hot-path rows (TestIntegration_HotPath*, TestV3_HotPath*) or whole test/integration / test/e2e packages; run the focused rows you add or touch (by exact name) and each touched package in full once. The Linux container is STOPPED: do not start it; the coordinator runs Linux verification and the whole e2e package at night. No real Claude Code sessions.
Other seats in this wave: e2erows (the three e2e rows and the store benchmark HOME leak), spoolseal (PreCompact after client spools, spool-submode wording, slow-disk docs), relhyg (bundle notices, descriptions, marketplace trigger, recall self-record prefix), ci (hosted ci.yml reds: os/exec allow-list, macOS zombie liveness and socket paths, Q1 non-reference disk declaration, cover's TestE2EHookRoundTrip, stubskips timeout, test/fault artifacts), winci (hosted Windows: the 8.3 short-name deny-rule bypass, elevated-runner ACL fixtures, Stop behind a session end's drain, cross-drive paths). Do not fix their items or edit their files beyond what your fix needs; if your root cause is theirs, say so and stop.`

const LIM16B = `Wave 16 is merged into your base, along with every earlier wave. Its reports are on your base under plans/sdd/V6-closeout/w16-<ws>/report.md; read the one your task names. Coordinator decisions D53 and D55 in the ledger (${ROOT}/qompack-v6/plans/V6-CLOSEOUT-CHECKLIST.md) govern this wave.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and three other seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, no hot-path rows (TestIntegration_HotPath*, TestV3_HotPath*), and no whole test/integration or test/e2e package. Run the focused rows you add or touch by exact name, and each touched package in full once. The Linux container is STOPPED and Docker Desktop's engine is stopped; only the cover seat may start them, as its task says. No real Claude Code sessions.
Other seats in this wave: settle (PreCompact settle follow-ups), polish (hostperm 8.3 trigger, grammar self-markers, plugin keywords), cirec (CI records, timeouts, the non-reference-disk docs), cover (Linux coverage floors for internal/paths and internal/store). Do not edit their files beyond what your fix needs.`

const LIM16C = `Wave 16b is merged into your base, along with every earlier wave. Its reports are on your base under plans/sdd/V6-closeout/w16b-<ws>/report.md; read the ones your task names. Coordinator decisions D53 and D55 in the ledger (${ROOT}/qompack-v6/plans/V6-CLOSEOUT-CHECKLIST.md) govern this wave.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and one other seat runs at once. Use \`-p 2\`, no load generators, no -race on whole packages, no hot-path rows (TestIntegration_HotPath*, TestV3_HotPath*), and no whole test/integration or test/e2e package. Run the focused rows you add or touch by exact name, and each touched package in full once (test/bench/hotpath in full is fine; test/integration only by the exact names of rows whose text you change, and not the hot-path rows). The Linux container and Docker Desktop's engine are STOPPED; do not start them. No real Claude Code sessions.
Other seat in this wave: settle2 (internal/daemon) and tidy (everything else listed in its task). Do not edit the other seat's files.`

const LIM16D = `Waves 16 and 16b are merged into your base. Their reports are under plans/sdd/V6-closeout/w16-<ws>/ and w16b-<ws>/report.md. Coordinator decisions D53 and D55 in the ledger (${ROOT}/qompack-v6/plans/V6-CLOSEOUT-CHECKLIST.md) govern this wave, and Q1 (hosted fsync figures are never constants; hosted fsync-bound rows report under QOMPACK_NONREFERENCE_DISK) applies.
Hosted CI run 36905843834 (verify/v6 07a748cb, the integration tree ae601390 merged) is green on ubuntu and macOS test, every timing and bench-gate leg, test-e2e ubuntu and macOS, security, replay-gate, docs, crossbuild and plugin-validate. Your task is one of its two reds. Read the job log with \`gh api repos/AidanHT/qompack/actions/jobs/<job>/logs\` (read-only); a copy is in ${SCRATCH}/../ci6/.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and three other seats run at once (wave 16c: settle2 in internal/daemon spool watcher, drain.go, precompact_settle.go, spool_heads.go and daemon.go's idle tick; tidy in internal/hostperm, test/bench/hotpath, internal/obs, store tests). Use \`-p 2\`, no load generators, no -race on whole packages, no hot-path rows, no whole test/integration or test/e2e package: run the e2e rows you touch by exact name. The Linux container and Docker Desktop's engine are STOPPED; do not start them. No real Claude Code sessions.
Never make a row pass by raising a product budget, removing an assertion or skipping: a fixture change is acceptable only when the row's subject is not the thing changed and another row pins that thing; record each such change as a criterion change with the rationale and the row that pins it.`

const LIM16E = `Waves 16, 16b and 16c are merged into your base. Their reports are under plans/sdd/V6-closeout/w16-<ws>/, w16b-<ws>/ and w16c-<ws>/report.md. Coordinator decisions D53 and D55 in the ledger (${ROOT}/qompack-v6/plans/V6-CLOSEOUT-CHECKLIST.md) govern this wave, and Q1 applies: hosted fsync figures are never constants, and hosted fsync-bound rows report under QOMPACK_NONREFERENCE_DISK.
Hosted CI run 36905843834 (verify/v6 07a748cb = integration ae601390, before wave 16c) found these reds. Read the job logs with \`gh api repos/AidanHT/qompack/actions/jobs/<job>/logs\` (read-only); copies are in ${SCRATCH}/../ci6/ (test-win.log, reldry.log, cover.log, e2e-win.log).
Wave 16d runs in parallel: warnlate (internal/daemon/handlers.go prompt reply, internal/observer, internal/grammar statewarn, test/e2e/v5_x10_test.go) and sealrow (internal/cli/precompact_spool_submode_test.go and its rig, the cover red of TestPreCompactInSpoolSubmodeSealsTheSpooledReads). Do not edit their files.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and three other seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, no hot-path rows, and no whole test/integration or test/e2e package. Run the rows you add or touch by exact name, and each touched package in full once. No real Claude Code sessions.
Never make a row pass by raising a product budget, removing an assertion or skipping. A fixture change is acceptable only when the thing changed is not the row's subject and another row pins it. Record each one as a criterion change, with the rationale and the row that pins it.`

const LIM16F = `Waves 16 to 16e are merged into your base. Their reports are under plans/sdd/V6-closeout/w16*-<ws>/report.md; read the ones your task names. Coordinator decisions D53, D55 and D56 in the ledger (${ROOT}/qompack-v6/plans/V6-CLOSEOUT-CHECKLIST.md) govern this wave. This is the last wave before release candidate 6 is frozen, so keep every change minimal and contained.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and two other seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, no hot-path rows, and no whole test/integration or test/e2e package. Run the rows you add or touch by exact name, and each touched package in full once. Do NOT start Docker Desktop or the Linux container: the owner's own containers run on that engine. No real Claude Code sessions.
Other seats in this wave: rearm (internal/daemon drain.go and handlers.go, internal/observer, .github/workflows/ci.yml comment), settlekick (internal/daemon daemon.go's served-request kick and the PreCompact route, precompact_settle.go wording), hpdepth (internal/hostperm sources.go). Do not edit their files.
Never make a row pass by raising a product budget, removing an assertion or skipping. Show every new row red first, against the base or with a temporary local edit that is not committed.`

const WS = []

WS.push({ ws: 'rearm', cid: 'C3.2', effort: 'high', reviewEffort: 'high', task: `TASK — close the residual thrash-warning loss that wave 16d's warnlate left open (plans/sdd/V6-closeout/w16d-warnlate/report.md: open_issues and the review's mode-(b) finding).
${LIM16F}
(1) The window. The observer can claim a reply just inside req.TS+250 ms, yet the rendered reply reaches the hook after the hook's own give-up. The hook then spools the prompt, while the rule stays in WarnedRules: the warning counts as delivered although the host never saw it. The signal is exact. When the drain settles a client-spooled observe.prompt whose nonce the daemon already answered live (drain.go absorbs that copy without dispatch, around the code that handles a live copy that is ahead), and that live reply carried a warning, re-arm the rule the same way a refused claim does (rearmUndelivered: remove it from WarnedRules, clear the queued warning, hold the multiplicity floor). The loop then warns afresh only if it continues. Record which nonce's live reply carried a warning in memory, bounded (no new persisted format) and keyed by the nonce. Count the re-arm under the existing observer.thrash_undelivered counter, or a sibling, and log it at Info.
  Row: a deterministic seam where the claim succeeds, the reply is held until the hook has given up and spooled, then the drain absorbs the copy and the rule is re-armed; the loop continuing then warns again. Red first.
(2) internal/daemon/handlers.go: the callObservePromptWithDeadline doc block still says the replayed WAL line "for observe.prompt runs only the sentinel scan", which SP08-D3 made false. Correct it.
(3) .github/workflows/ci.yml, the test-e2e job's QOMPACK_NONREFERENCE_DISK comment: also name X10's late or deferred prompt-reply recovery branch, as internal/obs/nonrefdisk.go now lists it.
Scope: internal/daemon (drain.go, handlers.go and the prompt reply handoff), internal/observer, their tests, the ci.yml comment.` })

WS.push({ ws: 'settlekick', cid: 'C4.3', effort: 'high', reviewEffort: 'high', task: `TASK — the PreCompact settle waits behind a watcher pass that the PreCompact request itself starts (wave 16e settlewin, product check item 5 and open_issues; plans/sdd/V6-closeout/w16e-settlewin/report.md).
${LIM16F}
(1) The defect. Every served non-hot request calls noteServed (internal/daemon/daemon.go), which kicks the client-spool watcher. For the PreCompact request, that kick can start a budgeted watcher pass over every session's spools. The pass takes the drain mutex, and the settle's DrainClientSpoolsWithin then waits behind it (lockWithin), spending this session's 500 ms bound on other sessions' backlog. Confirm it with a deterministic row: a due spool of another session, a PreCompact, and the settle's replay of this session's own spool must not wait behind a pass the PreCompact itself kicked. Show it red first.
  Fix it minimally: the PreCompact route's own kick runs after the seal, not before the settle. Keep the watcher's own idle-tick and other kicks as they are. If the watcher pass is already running for another reason when the settle starts, that wait stays the designed D55 degrade: named in the drop report, nothing lost. Say so, and do not redesign the drain mutex.
(2) The unread-spools clause (precompact_settle.go unreadSpoolsClauseFormat and its doc comment). Since wave 16d (c71740c2) it also covers a spool that failed to read with an I/O or sharing error, not only one the bound ended before. Word it to cover both truthfully, e.g. "could not be read within the bound or failed to read". Update every row and doc that pins the text: grep the tree, including docs/ and the plans' section 7 text it names.
Scope: internal/daemon (daemon.go's noteServed or the PreCompact route, precompact_settle.go) and its tests, plus the docs or plans that quote the clause.` })

WS.push({ ws: 'hpdepth', cid: 'C4.6', effort: 'medium', reviewEffort: 'high', task: `TASK — fix a privacy fail-open in internal/hostperm found by wave 16e (plans/sdd/V6-closeout/w16e-hpcover/report.md, open_issues and needs_owner).
${LIM16F}
collectPermissions (internal/hostperm/sources.go, maxNesting=8 near line 43, the depth check near line 426) stops walking the server-managed cache (~/.claude/remote-settings.json) past depth 8. A permissions block nested deeper is dropped with no error, so its Read deny and ask rules are not enforced. The doc comment says "wherever its rules sit, they apply".
D56 decides the fix: no silent truncation, and no refusing everything for a deep but harmless document. Walk the whole decoded document for permissions blocks. Its size is already bounded by the source read, and its depth by encoding/json's own nesting limit. If a bound on the walk is still needed, crossing it must be a sourceError (fail closed, as for an undecodable source), never a silent drop. Remove maxNesting if nothing else needs it.
Rows, red first:
  - a permissions block 9 levels deep (and a much deeper one, e.g. 100) whose Read deny rule is enforced;
  - a deep document with no permissions block, which stays a normal, enforced policy;
  - a hooks block at depth 7 still parses.
Keep docs/security.md accurate if it describes the walk.
Scope: internal/hostperm (sources.go and its tests), docs/security.md if needed.` })

const RESULT = { type: 'object', properties: {
  status: { type: 'string', enum: ['done', 'partial', 'blocked'] }, head: { type: 'string' },
  commits: { type: 'array', items: { type: 'string' } }, root_cause: { type: 'string' }, summary: { type: 'string' },
  tests: { type: 'array', items: { type: 'object', properties: { command: { type: 'string' }, result: { type: 'string' } }, required: ['command', 'result'] } },
  criterion_changes: { type: 'array', items: { type: 'string' } }, open_issues: { type: 'array', items: { type: 'string' } },
  needs_owner: { type: 'array', items: { type: 'string' } },
}, required: ['status', 'head', 'commits', 'summary', 'tests', 'open_issues', 'needs_owner'] }
const FINDINGS = { type: 'object', properties: {
  verdict: { type: 'string', enum: ['sound', 'needs-fixes', 'unsound'] },
  findings: { type: 'array', items: { type: 'object', properties: {
    severity: { type: 'string', enum: ['blocker', 'major', 'minor', 'nit'] }, location: { type: 'string' },
    issue: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' },
  }, required: ['severity', 'location', 'issue', 'evidence', 'fix'] } },
}, required: ['verdict', 'findings'] }

const LENS = 'Lenses: (a) root cause proven and fixed at the source; correctness incl. concurrency (races, deadlocks, lock order, goroutine leaks), durability/crash semantics (fsync ordering, WAL retention, idempotency, identity never re-minted), fail-closed paths, Windows vs POSIX, bounded memory/CPU; (b) check-weakening (deleted/loosened assertions, skips, nolint/nomagic, lowered thresholds, regenerated goldens, widened timeouts, tests bent to buggy output) and legitimacy of every criterion change; (c) every new bound/budget number is named, derived, and listed for the owner; (d) docs consistent with behaviour, generated docs via generators; (e) commit hygiene (conventional subjects, Refs footer, no attribution trailers); (f) was the whole task done, or parts silently dropped?'

const results = await pipeline(
  WS,
  (w) => agent(`${COMMON(w)}\n\n${w.task}`, { label: `impl:${w.ws}`, phase: 'Implement', schema: RESULT, effort: w.effort }),
  async (impl, w) => {
    if (!impl) return { w, impl: null, review: null }
    const review = await agent(`You are an independent, adversarial reviewer for Qompack V6 close-out wave-16f workstream "${w.ws}" (${w.cid}). Worktree ${ROOT}/qompack-cx-w16f-${w.ws}, branch closeout/w16f-${w.ws}, base ${BASE}. The task was:\n---\n${w.task}\n---\nImplementer result: ${JSON.stringify(impl)}\nReview \`git -C ${ROOT}/qompack-cx-w16f-${w.ws} log ${BASE}..HEAD\` and the full diff \`git diff ${BASE} HEAD\`. READ-ONLY: do not edit, commit, stash or reset. You may run focused tests (never ./...; never kill processes you did not start; the machine is loaded — re-run a timing failure alone before believing it). No real claude sessions; never touch the real ~/.qompack or ~/.claude.\n${LENS}\nReturn findings with severity, file:line, evidence and a concrete fix; if sound, verdict "sound" and an empty list.`,
      { label: `review:${w.ws}`, phase: 'Review', schema: FINDINGS, effort: w.reviewEffort })
    return { w, impl, review }
  },
  async (r) => {
    if (!r.impl) return { w: r.w, ws: r.w.ws, impl: null, review: null, final: null }
    const actionable = (r.review ? r.review.findings : []).filter((f) => f.severity !== 'nit')
    if (actionable.length === 0) return { w: r.w, ws: r.w.ws, impl: r.impl, review: r.review, final: r.impl, fixRan: false, actionable }
    const final = await agent(`${COMMON(r.w)}\n\nYou are the FIX seat for this workstream (the implementer has finished). Its task was:\n---\n${r.w.task}\n---\nIndependent reviewer findings:\n${JSON.stringify(actionable, null, 1)}\nVerify each independently; fix the correct ones (failing test first where applicable) and re-run focused tests; rebut wrong ones with evidence. Blockers/majors must be resolved or rebutted. Return the final state with a "Review resolution" section (finding -> action/rebuttal) in your summary, and carry forward every needs_owner item still open (the implementer's were: ${JSON.stringify(r.impl.needs_owner || [])}).`,
      { label: `fix:${r.w.ws}`, phase: 'Fix', schema: RESULT, effort: r.w.effort })
    return { w: r.w, ws: r.w.ws, impl: r.impl, review: r.review, final, fixRan: true, actionable }
  },
  async (r) => {
    if (!r.fixRan || !r.final) return { ws: r.ws, impl: r.impl, review: r.review, final: r.final, fixRan: !!r.fixRan, verify: null }
    const verify = await agent(`You are an independent verifier for Qompack V6 close-out wave-16f workstream "${r.ws}". Worktree ${ROOT}/qompack-cx-w16f-${r.ws}, branch closeout/w16f-${r.ws}. A reviewer raised these findings:\n${JSON.stringify(r.actionable, null, 1)}\nThe fix seat's result: ${JSON.stringify(r.final)}\nFor EACH finding decide whether it is now resolved correctly or rebutted soundly, by reading the code at HEAD and the fix commits (\`git -C ${ROOT}/qompack-cx-w16f-${r.ws} log ${r.impl.head}..HEAD\`), and check the fix commits introduced no new defect or check-weakening. READ-ONLY: do not edit, commit, stash or reset; focused tests allowed (never ./...; never kill processes you did not start; never touch the real ~/.qompack or ~/.claude). Return as findings ONLY what is still wrong (unresolved, badly rebutted, or newly introduced), with severity, file:line, evidence and fix; verdict "sound" with an empty list if everything is resolved.`,
      { label: `verify:${r.ws}`, phase: 'Verify', schema: FINDINGS, effort: r.w.reviewEffort })
    return { ws: r.ws, impl: r.impl, review: r.review, final: r.final, fixRan: true, verify }
  },
)
return results
