export const meta = {
  name: 'v6-closeout-wave16d',
  description: 'Wave 16d close-out: hosted reds on 07a748cb (thrash warning on a late reply, spool-submode seal row under cover); reviewed, fixed and verified',
  phases: [
    { title: 'Implement', detail: 'two workstreams off closeout/integration ae601390' },
    { title: 'Review', detail: 'independent adversarial review' },
    { title: 'Fix', detail: 'resolve confirmed findings' },
    { title: 'Verify', detail: 'check the fix seat resolved every non-nit finding' },
  ],
}

const ROOT = 'C:/Users/Quant/Documents/Programming/Projects'
const BASE = 'ae601390'
const SCRATCH = 'C:/Users/Quant/AppData/Local/Temp/claude/C--Users-Quant-Documents-Programming-Projects-qompack/9c57653d-e5ff-4791-8ab4-ad49457994c1/scratchpad/w16d'

const COMMON = (w) => `You are one of the parallel workstreams (wave 16d: warnlate, sealrow) closing out the Qompack V6 verification (Qompack is a Go Claude Code plugin: hooks -> resident daemon -> content-addressed store under .qompack/, an MCP retrieval server, slash commands). Coordinator ledger (read it; do NOT edit it): ${ROOT}/qompack-v6/plans/V6-CLOSEOUT-CHECKLIST.md — owner decisions D1-D49 and the coordinator defaults are there. Earlier workstream reports are committed on your base under plans/sdd/V6-closeout/<ws>/report.md (wave 1: ingest, e2e, config, hostperm, rollover, perfstore, perfobs, eval, linux, packaging, rehydrate-cap; wave 2b: w2-*; wave 3/4: w3-startroute, w3-paths, w3-e2ereds, w3-eval3, w4-syncs, w4-e2eflakes; wave 5: w5-coldstart, w5-home, w5-winfiles, w5-helpers, w5-dirsync, w5-deps; wave 6: w6-borrow, w6-config, w6-ckptsync, w6-gcserial, w6-linuxrows; wave 7: w7-spawnclaim, w7-layout, w7-sp08d3, w7-docs, w7b-selftest, w7b-checkpoint; wave 8: w8-sp08d3fix, w8-stagerace, w8b-polish) — read the ones relevant to your task first.

YOUR WORKTREE: ${ROOT}/qompack-cx-w16d-${w.ws} on branch closeout/w16d-${w.ws}, cut from closeout/integration @ ${BASE} (every earlier wave merged). The Bash tool resets cwd between calls: prefix every command with \`cd ${ROOT}/qompack-cx-w16d-${w.ws} &&\` or use absolute paths. Never edit other worktrees. Never push, tag, merge, rebase or reset other branches, change git config/hooks, or SendMessage anyone. Your scratch files go under ${SCRATCH}/${w.ws}/ (create it); never delete anything else in that scratchpad.

Hard rules (owner directives, non-negotiable):
- Never weaken a check: no t.Skip, no //nolint, no //nomagic:allow added to silence something, no lowered threshold/budget, no golden regenerated to match broken output, no deleted or loosened assertion, no widened timeout that hides a defect. Criterion changes only with a written rationale in your returned report.
- Root cause first; failing regression test first; then fix.
- New budget/bound numbers are the owner's: implement them behind a named constant with a derivation comment, and list each one (value, derivation, what breaks if it is wrong) under needs_owner; the coordinator gets approval before merging.
- Commits: conventional \`type(scope): subject\` (lowercase scope, subject <=64 chars, no trailing period), body lines <=100 chars, \`Refs: V6-VERIFY, ${w.cid}\` footer on feat/fix, NO attribution trailers (no Co-Authored-By, Signed-off-by, Claude-Session, "Generated with", robot emoji) — the commit-msg hook rejects them. Small focused commits. Evidence logs may be committed under plans/sdd/V6-closeout/w16d-${w.ws}/runs/.
- \`go run ./tools/devtool fmt\`/\`fmt-check\`, \`go vet\` on touched packages (Windows and GOOS=linux); \`go test ./test/docs\` and gen-*-docs --check when docs/generated inputs change. Use \`go run ./tools/devtool lint --only=golangci-lint,nomagic,importgraph,testdeps,bindeps,sleepcheck,docmarkers,runpatterns\`: never the stubskips sub-check (it runs a whole-tree go test).
- Tests: FOCUSED runs plus each touched package once in full; never ./... or devtool test/test-race (four other workstreams run tests on this machine and in the Linux container at the same time, so the machine is loaded: re-run any wall-clock failure alone before believing it, and say so). Never let a pipe mask go test's exit code.
- Every \`go test -run\` pattern you quote in your report must match a real test name exactly (the runpatterns lint checks committed reports); name temporary diagnostics as such.
- Processes: never kill a process you did not start. If you must stop your own processes, match on YOUR worktree path or your own scratch subdirectory.
- Linux: container \`qompack-v6-linux-verification\`; the committed script plans/sdd/V6-closeout/linux/linux-nonroot-gate.sh runs an exact commit non-root with -race (see its header; use --prefix cx-w16d-${w.ws}; pass --repo and --out as Windows-style C:/ paths, a POSIX /c/ path is refused); never reuse or delete other /work dirs.
- CPU: the owner uses this laptop interactively. Any load generator you start must be bounded with \`timeout\` to at most 20 minutes per run and at most 8 busy processes (of 22 cores), and you must stop it when the measurement ends; never leave one running. Stop your own background diagnostics before you finish.
- Never create, read or modify the real ~/.qompack or ~/.claude in tests; use a fake HOME/USERPROFILE. Real Claude Code sessions are NOT allowed.
- The harness refuses report files from subagents: do NOT write report.md. Return the full report (root causes with evidence, what changed, exact commands + results, criterion changes, open items, owner decisions) in your returned summary; the coordinator commits it.`

const MACHINE = `MACHINE LIMITS FOR THIS SEAT (override the general rules): Phase 3 gates run on this laptop now and memory is tight. The Linux container is STOPPED on purpose: do NOT start it and do not run the Linux gate script; the coordinator runs Linux verification later. On Windows use \`-p 2\`, no load generators. The Phase 3 chain logs to C:/Users/Quant/Documents/Programming/Projects/qompack-v6/plans/sdd/V6-closeout/phase3/chain-2.log: while that file has a "win-timing start" line with no later "win-timing exit" line, an ISOLATED timing gate is running and you must not run anything load-bearing (no hot-path row, no test/integration package, no -race, no benchmark) until it ends; do code reading and cheap deterministic unit tests meanwhile. Run at most one load-bearing test at a time.`

const EV = `EVIDENCE: the Phase 4 live lane ran real Claude Code 2.1.280 sessions on the frozen candidate 3 (d5598eb4) with the packaged bundle. Its report is plans/sdd/V6-closeout/live/report.md in your worktree (evidence dirs beside it under plans/sdd/V6-closeout/live/uat/, c4/, recovery/). Read the rows named below and their evidence files before touching code. Coordinator decision D45 (ledger) says these are fixed before 0.3.0.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and six seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, and do NOT run the hot-path rows (TestIntegration_HotPath*, TestV3_HotPath*) or whole test/integration / test/e2e packages; run only the focused rows you add or touch plus the touched packages in full once. The Linux container is STOPPED: do not start it. Real Claude Code sessions are NOT allowed: reproduce each live finding with a deterministic test (a real daemon/store/hook process in a temp project is fine) that is RED before the fix. The coordinator re-runs the live rows on the fixed candidate.
Other seats in this wave (do not fix their items; if your root cause turns out to be theirs, say so and stop): ledger (elimination ledger, MCP self-record turns, timeline), intent (rehydration intent/corrections/fork), restore (backup/restore/fsck segments/cross-version), pinsckpt (pins view, checkpoint pointers), diag (sentinel scan, status/doctor diagnostics), mcpresp (MCP response bounds/selectors/messages, UAT docs).`

const LIM = `MACHINE LIMITS FOR THIS SEAT (override the general rules): three seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, and do NOT run the hot-path rows (TestIntegration_HotPath*, TestV3_HotPath*) or whole test/integration / test/e2e packages; run the focused rows you add or touch and the touched packages in full once. The Linux container is STOPPED: do not start it. No real Claude Code sessions: reproduce with deterministic tests that are RED before the fix. Read coordinator decision D46 in the ledger. Other seats: observer, decisions, safecut.`

const LIM15_UNUSED = `EVIDENCE: the live re-run on candidate 4 (9f6a2fad, decision D47) ran real Claude Code sessions with the frozen bundle. Its evidence is committed on your base under plans/sdd/V6-closeout/live/rerun-c4/<row>/ and the Result blocks in docs/uat.md; the findings named below come from there. Coordinator decision D49 in the ledger says every one is fixed before 0.3.0 and fixes each disposition: read D45, D46 and D49 first.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and four seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, and do NOT run the hot-path rows (TestIntegration_HotPath*, TestV3_HotPath*) or whole test/integration / test/e2e packages; run the focused rows you add or touch and the touched packages in full once. The Linux container is STOPPED: do not start it. No real Claude Code sessions: reproduce each finding with a deterministic test (a real daemon/store/hook process in a temp project is fine) that is RED before the fix.
Other seats: rehydrate (fallback visibility, evolution admission, eviction order), ledger (stale bloom, advance_frontier, decisions across checkpoints, fork inheritance), services (config reload, recall k, publication accounting, fsck index.files), docs. Do not fix their items; if your root cause is theirs, say so and stop.`

const LIM15A_UNUSED = `EVIDENCE: the candidate 4 live re-run's audit (plans/sdd/V6-closeout/live/report-c4.md, section "Independent audit") and its evidence under plans/sdd/V6-closeout/live/rerun-c4/ are on your base. Coordinator decision D50 in the ledger fixes the dispositions: read D45, D46, D49 and D50 first.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and six seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, and do NOT run the hot-path rows (TestIntegration_HotPath*, TestV3_HotPath*) or whole test/integration / test/e2e packages; run the focused rows you add or touch and the touched packages in full once. The Linux container is STOPPED: do not start it. No real Claude Code sessions: reproduce with deterministic tests that are RED before the fix.
Other seats running now: wave 15 rehydrate (internal/rehydrate), ledger (internal/negknow, checkpoint decisions), services (daemon config reload, mcp recall in handlers.go, store publication accounting, fsck index.files), docs; and paging / snapshot in this wave. Do not fix their items or edit their files beyond what your fix needs; if your root cause is theirs, say so and stop.`

const LIM15B_UNUSED = `EVIDENCE: the candidate 4 live re-run's audit (plans/sdd/V6-closeout/live/report-c4.md, section "Independent audit") and its evidence under plans/sdd/V6-closeout/live/rerun-c4/ are on your base, with wave 15 (docs, ledger) and wave 15a (paging, snapshot) merged. Coordinator decision D50 in the ledger fixes the dispositions: read D46, D49 and D50 first.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and other seats run at once. Use \`-p 2\`, no load generators, no hot-path rows, no whole test/integration or test/e2e packages. The Linux container is STOPPED: do not start it. No real Claude Code sessions.
Other seats running now: wave 15 rehydrate (internal/rehydrate) and services (daemon reload, mcp recall, store publication accounting, fsck). Do not edit their files.`

const LIM15C = `Coordinator decisions D49 and D51 in the ledger govern this task: read them. The wave 15 services report is on your base: plans/sdd/V6-closeout/w15-services/report.md (its needs_owner and open issues are the source of this task).
MACHINE LIMITS FOR THIS SEAT (override the general rules): the owner is using this laptop and another seat runs. Use \`-p 2\`, no load generators except the bounded measurement below, no hot-path rows, no whole test/integration or test/e2e. The Linux container is STOPPED: do not start it. No real Claude Code sessions.
Other seat running now: wave 15 rehydrate (internal/rehydrate). Do not edit its files.`

const LIM16 = `Coordinator decision D53 in the ledger governs this wave: read it, with D45, D46, D49 and D50. The independent audit it disposes is plans/sdd/V6-closeout/audit/goal-metrics-audit.md on verify/v6 (read it at ${ROOT}/qompack-v6/plans/sdd/V6-closeout/audit/goal-metrics-audit.md). Candidate 5's overnight evidence is under ${ROOT}/qompack-v6/plans/sdd/V6-closeout/phase3/c5/ (p3-win-e2e-timing.log, linux/cx-p3-p3-linux-e2e-timing-*/, quiet/).
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and other seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, and do NOT run the hot-path rows (TestIntegration_HotPath*, TestV3_HotPath*) or whole test/integration / test/e2e packages; run the focused rows you add or touch (by exact name) and each touched package in full once. The Linux container is STOPPED: do not start it; the coordinator runs Linux verification and the whole e2e package at night. No real Claude Code sessions.
Other seats in this wave: e2erows (the three e2e rows and the store benchmark HOME leak), spoolseal (PreCompact after client spools, spool-submode wording, slow-disk docs), relhyg (bundle notices, descriptions, marketplace trigger, recall self-record prefix), ci (hosted ci.yml reds: os/exec allow-list, macOS zombie liveness and socket paths, Q1 non-reference disk declaration, cover's TestE2EHookRoundTrip, stubskips timeout, test/fault artifacts), winci (hosted Windows: the 8.3 short-name deny-rule bypass, elevated-runner ACL fixtures, Stop behind a session end's drain, cross-drive paths). Do not fix their items or edit their files beyond what your fix needs; if your root cause is theirs, say so and stop.`

const LIM16B = `Wave 16 is merged into your base, along with every earlier wave. Its reports are on your base under plans/sdd/V6-closeout/w16-<ws>/report.md; read the one your task names. Coordinator decisions D53 and D55 in the ledger (${ROOT}/qompack-v6/plans/V6-CLOSEOUT-CHECKLIST.md) govern this wave.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and three other seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, no hot-path rows (TestIntegration_HotPath*, TestV3_HotPath*), and no whole test/integration or test/e2e package. Run the focused rows you add or touch by exact name, and each touched package in full once. The Linux container is STOPPED and Docker Desktop's engine is stopped; only the cover seat may start them, as its task says. No real Claude Code sessions.
Other seats in this wave: settle (PreCompact settle follow-ups), polish (hostperm 8.3 trigger, grammar self-markers, plugin keywords), cirec (CI records, timeouts, the non-reference-disk docs), cover (Linux coverage floors for internal/paths and internal/store). Do not edit their files beyond what your fix needs.`

const LIM16C = `Wave 16b is merged into your base, along with every earlier wave. Its reports are on your base under plans/sdd/V6-closeout/w16b-<ws>/report.md; read the ones your task names. Coordinator decisions D53 and D55 in the ledger (${ROOT}/qompack-v6/plans/V6-CLOSEOUT-CHECKLIST.md) govern this wave.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and one other seat runs at once. Use \`-p 2\`, no load generators, no -race on whole packages, no hot-path rows (TestIntegration_HotPath*, TestV3_HotPath*), and no whole test/integration or test/e2e package. Run the focused rows you add or touch by exact name, and each touched package in full once (test/bench/hotpath in full is fine; test/integration only by the exact names of rows whose text you change, and not the hot-path rows). The Linux container and Docker Desktop's engine are STOPPED; do not start them. No real Claude Code sessions.
Other seat in this wave: settle2 (internal/daemon) and tidy (everything else listed in its task). Do not edit the other seat's files.`

const LIM16D = `Waves 16 and 16b are merged into your base. Their reports are under plans/sdd/V6-closeout/w16-<ws>/ and w16b-<ws>/report.md. Coordinator decisions D53 and D55 in the ledger (${ROOT}/qompack-v6/plans/V6-CLOSEOUT-CHECKLIST.md) govern this wave, and Q1 (hosted fsync figures are never constants; hosted fsync-bound rows report under QOMPACK_NONREFERENCE_DISK) applies.
Hosted CI run 36905843834 (verify/v6 07a748cb, the integration tree ae601390 merged) is green on ubuntu and macOS test, every timing and bench-gate leg, test-e2e ubuntu and macOS, security, replay-gate, docs, crossbuild and plugin-validate. Your task is one of its two reds. Read the job log with \`gh api repos/AidanHT/qompack/actions/jobs/<job>/logs\` (read-only); a copy is in ${SCRATCH}/../ci6/.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and three other seats run at once (wave 16c: settle2 in internal/daemon spool watcher, drain.go, precompact_settle.go, spool_heads.go and daemon.go's idle tick; tidy in internal/hostperm, test/bench/hotpath, internal/obs, store tests). Use \`-p 2\`, no load generators, no -race on whole packages, no hot-path rows, no whole test/integration or test/e2e package: run the e2e rows you touch by exact name. The Linux container and Docker Desktop's engine are STOPPED; do not start them. No real Claude Code sessions.
Never make a row pass by raising a product budget, removing an assertion or skipping: a fixture change is acceptable only when the row's subject is not the thing changed and another row pins that thing; record each such change as a criterion change with the rationale and the row that pins it.`

const WS = []

WS.push({ ws: 'warnlate', cid: 'C3.2', effort: 'high', reviewEffort: 'high', task: `TASK — hosted red: test-e2e (windows-latest), job 110516048026. TestV5_ThrashWarningVisibleInStatusAndCheckpoint/sequitur_warning_is_warning_only_and_once_per_rule fails at test/e2e/v5_x10_test.go:466, "the prompt after a thrashing loop must carry the warning": the prompt hook's output had no HookSpecificOutput. It passed on ubuntu and macOS, and locally (w16-e2erows). Candidate 5's hosted run failed the same row at a different line (the checkpoint carried the warning), which wave 16 fixed.
${LIM16D}
(1) Find the cause. Candidates, not conclusions:
  - the hook client's ACK deadline expired on the hosted disk (Windows B-A 50 ms; hosted fsync p99 ~74 ms with a tail past 1 s), so the client spooled the prompt and printed no output;
  - or the daemon's reply exceeded promptReplyDeadline (250 ms, internal/daemon/handlers.go callObservePromptWithDeadline), which sends the reply empty by design and counts l0_prompt_reply_late.
  Tell them apart with evidence: the log, the code paths, and a local reproduction through a deterministic seam (a held ingest or reply seam, or a slowed fsync seam), not wall-clock luck.
(2) Decide the product question with evidence and fix it if it is a defect. When the warning does not reach the host (late reply, or the client deferred on its ACK deadline), is it consumed so the rule is treated as delivered? Then a loop that continues is never warned about on a slow disk. That is a real defect: a warning the host never received must not count as delivered for once-per-rule. Keep the documented design that a stale warning is not replayed into a later turn; the fix is that the detector may warn afresh when the loop continues. If the code already behaves this way, show it with a row.
(3) Make the e2e row hold on a non-reference disk without weakening it. On a reference disk the first prompt after the loop must still carry the warning. When this prompt's reply was observably late or deferred (the counter, or the client spool), the row must prove recovery instead: e.g. one more loop cycle, after which the next prompt carries the warning. Assert every other property (channel, once per rule, nothing durable, not in the checkpoint) exactly as now. Keep the late or deferred branch observable and logged, never silent.
Also report anything else in that job's log that failed or warned.
Scope: internal/daemon/handlers.go (prompt reply path), internal/observer (prompt delivery), internal/grammar (statewarn delivery accounting), test/e2e/v5_x10_test.go, and their tests. Do not edit settle2's files.` })

WS.push({ ws: 'sealrow', cid: 'C4.3', effort: 'high', reviewEffort: 'high', task: `TASK — hosted red: cover (ubuntu), job 110516048246. internal/cli TestPreCompactInSpoolSubmodeSealsTheSpooledReads (wave 16 spoolseal's row) failed at precompact_spool_submode_test.go:93. Both spooled Reads were replayed and sealed, but the checkpoint's dropped list held an unreplayed_capture: "1 capture(s) of this session (0 tool result(s), 0 prompt(s), 1 other) were still waiting to be replayed into the store when this checkpoint was sealed". The ubuntu test job (-race, cacheable) and every other leg passed it; cover runs it with -covermode=atomic, in parallel with the other packages.
${LIM16D}
(1) Find the cause. Which capture was the "1 other": the spooled Stop, the session-start, or something else? Why was it not replayed inside precompactSettleBound (500 ms) when the Reads were? Candidates: a slow cover-instrumented drain under co-load; the drain ordering or a lease wait for the Stop; the settle's own-spool detection; a race between the Stop hook's spool write and the first look. Show it with evidence: the code, plus a deterministic local reproduction (a held drain seam, an instrumented build, or -covermode=atomic with -cpu 1 and -count=N). Do not rely on wall-clock luck.
(2) If it is a product defect (e.g. a Stop that could be replayed within the bound is left behind, or a capture is miscounted), fix it with a red row first. Be careful: wave 16c's settle2 seat is editing internal/daemon/precompact_settle.go, spool_heads.go, drain.go and daemon.go in parallel. Keep any product edit there minimal and self-contained, and describe it precisely so the coordinator can merge it.
(3) If it is the designed degrade (the bound ran out under instrumentation and co-load, and the capture is named, nothing lost), make the row's subject hold deterministically: the replay of the session's own spools before the seal. Use a fixture that gives the settle enough bound for that subject (the rig's PreCompact budget), because the bound itself is pinned by its own rows (name them). Record the criterion change. Run the row at -count=20 with -covermode=atomic locally to show it is stable.
Scope: internal/cli (precompact_spool_submode_test.go and its rig), internal/daemon only for a real defect, and their tests.` })

const RESULT = { type: 'object', properties: {
  status: { type: 'string', enum: ['done', 'partial', 'blocked'] }, head: { type: 'string' },
  commits: { type: 'array', items: { type: 'string' } }, root_cause: { type: 'string' }, summary: { type: 'string' },
  tests: { type: 'array', items: { type: 'object', properties: { command: { type: 'string' }, result: { type: 'string' } }, required: ['command', 'result'] } },
  criterion_changes: { type: 'array', items: { type: 'string' } }, open_issues: { type: 'array', items: { type: 'string' } },
  needs_owner: { type: 'array', items: { type: 'string' } },
}, required: ['status', 'head', 'commits', 'summary', 'tests', 'open_issues', 'needs_owner'] }
const FINDINGS = { type: 'object', properties: {
  verdict: { type: 'string', enum: ['sound', 'needs-fixes', 'unsound'] },
  findings: { type: 'array', items: { type: 'object', properties: {
    severity: { type: 'string', enum: ['blocker', 'major', 'minor', 'nit'] }, location: { type: 'string' },
    issue: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' },
  }, required: ['severity', 'location', 'issue', 'evidence', 'fix'] } },
}, required: ['verdict', 'findings'] }

const LENS = 'Lenses: (a) root cause proven and fixed at the source; correctness incl. concurrency (races, deadlocks, lock order, goroutine leaks), durability/crash semantics (fsync ordering, WAL retention, idempotency, identity never re-minted), fail-closed paths, Windows vs POSIX, bounded memory/CPU; (b) check-weakening (deleted/loosened assertions, skips, nolint/nomagic, lowered thresholds, regenerated goldens, widened timeouts, tests bent to buggy output) and legitimacy of every criterion change; (c) every new bound/budget number is named, derived, and listed for the owner; (d) docs consistent with behaviour, generated docs via generators; (e) commit hygiene (conventional subjects, Refs footer, no attribution trailers); (f) was the whole task done, or parts silently dropped?'

const results = await pipeline(
  WS,
  (w) => agent(`${COMMON(w)}\n\n${w.task}`, { label: `impl:${w.ws}`, phase: 'Implement', schema: RESULT, effort: w.effort }),
  async (impl, w) => {
    if (!impl) return { w, impl: null, review: null }
    const review = await agent(`You are an independent, adversarial reviewer for Qompack V6 close-out wave-16d workstream "${w.ws}" (${w.cid}). Worktree ${ROOT}/qompack-cx-w16d-${w.ws}, branch closeout/w16d-${w.ws}, base ${BASE}. The task was:\n---\n${w.task}\n---\nImplementer result: ${JSON.stringify(impl)}\nReview \`git -C ${ROOT}/qompack-cx-w16d-${w.ws} log ${BASE}..HEAD\` and the full diff \`git diff ${BASE} HEAD\`. READ-ONLY: do not edit, commit, stash or reset. You may run focused tests (never ./...; never kill processes you did not start; the machine is loaded — re-run a timing failure alone before believing it). No real claude sessions; never touch the real ~/.qompack or ~/.claude.\n${LENS}\nReturn findings with severity, file:line, evidence and a concrete fix; if sound, verdict "sound" and an empty list.`,
      { label: `review:${w.ws}`, phase: 'Review', schema: FINDINGS, effort: w.reviewEffort })
    return { w, impl, review }
  },
  async (r) => {
    if (!r.impl) return { w: r.w, ws: r.w.ws, impl: null, review: null, final: null }
    const actionable = (r.review ? r.review.findings : []).filter((f) => f.severity !== 'nit')
    if (actionable.length === 0) return { w: r.w, ws: r.w.ws, impl: r.impl, review: r.review, final: r.impl, fixRan: false, actionable }
    const final = await agent(`${COMMON(r.w)}\n\nYou are the FIX seat for this workstream (the implementer has finished). Its task was:\n---\n${r.w.task}\n---\nIndependent reviewer findings:\n${JSON.stringify(actionable, null, 1)}\nVerify each independently; fix the correct ones (failing test first where applicable) and re-run focused tests; rebut wrong ones with evidence. Blockers/majors must be resolved or rebutted. Return the final state with a "Review resolution" section (finding -> action/rebuttal) in your summary, and carry forward every needs_owner item still open (the implementer's were: ${JSON.stringify(r.impl.needs_owner || [])}).`,
      { label: `fix:${r.w.ws}`, phase: 'Fix', schema: RESULT, effort: r.w.effort })
    return { w: r.w, ws: r.w.ws, impl: r.impl, review: r.review, final, fixRan: true, actionable }
  },
  async (r) => {
    if (!r.fixRan || !r.final) return { ws: r.ws, impl: r.impl, review: r.review, final: r.final, fixRan: !!r.fixRan, verify: null }
    const verify = await agent(`You are an independent verifier for Qompack V6 close-out wave-16d workstream "${r.ws}". Worktree ${ROOT}/qompack-cx-w16d-${r.ws}, branch closeout/w16d-${r.ws}. A reviewer raised these findings:\n${JSON.stringify(r.actionable, null, 1)}\nThe fix seat's result: ${JSON.stringify(r.final)}\nFor EACH finding decide whether it is now resolved correctly or rebutted soundly, by reading the code at HEAD and the fix commits (\`git -C ${ROOT}/qompack-cx-w16d-${r.ws} log ${r.impl.head}..HEAD\`), and check the fix commits introduced no new defect or check-weakening. READ-ONLY: do not edit, commit, stash or reset; focused tests allowed (never ./...; never kill processes you did not start; never touch the real ~/.qompack or ~/.claude). Return as findings ONLY what is still wrong (unresolved, badly rebutted, or newly introduced), with severity, file:line, evidence and fix; verdict "sound" with an empty list if everything is resolved.`,
      { label: `verify:${r.ws}`, phase: 'Verify', schema: FINDINGS, effort: r.w.reviewEffort })
    return { ws: r.ws, impl: r.impl, review: r.review, final: r.final, fixRan: true, verify }
  },
)
return results
