export const meta = {
  name: 'v6-closeout-wave2b',
  description: 'Wave 2b (re-run after usage limit): session-end/drain, daemon lifetime, hook outputs, rollover D6 diagnostics, lint gates, eval review, Windows security red; each reviewed and fixed',
  phases: [
    { title: 'Implement', detail: 'seven workstreams, one worktree each off closeout/integration b070bbe' },
    { title: 'Review', detail: 'independent adversarial review' },
    { title: 'Fix', detail: 'resolve confirmed findings' },
  ],
}

const ROOT = 'C:/Users/Quant/Documents/Programming/Projects'
const BASE = 'b070bbe'

const COMMON = (w) => `You are one of several parallel workstreams closing out the Qompack V6 verification (Qompack is a Go Claude Code plugin: hooks -> resident daemon -> content-addressed store under .qompack/, an MCP retrieval server, slash commands). Coordinator ledger (read it; do NOT edit it): ${ROOT}/qompack-v6/plans/V6-CLOSEOUT-CHECKLIST.md. Wave-1 workstream reports are committed on your base under plans/sdd/V6-closeout/<ws>/report.md (ingest, e2e, config, hostperm, rollover, perfstore, perfobs, eval, linux, packaging, rehydrate-cap) — read the ones relevant to your task first.

YOUR WORKTREE: ${ROOT}/qompack-cx-w2-${w.ws} on branch closeout/w2-${w.ws}, cut from closeout/integration @ ${BASE} (all wave-1 branches merged). The Bash tool resets cwd between calls: prefix every command with \`cd ${ROOT}/qompack-cx-w2-${w.ws} &&\` or use absolute paths. Never edit other worktrees. Never push, tag, merge, rebase other branches, change git config/hooks, or SendMessage anyone.

Hard rules (owner directives, non-negotiable):
- Never weaken a check: no t.Skip, no //nolint, no //nomagic:allow added to silence something, no lowered threshold/budget, no golden regenerated to match broken output, no deleted or loosened assertion, no widened timeout that hides a defect. Criterion changes only with a written rationale in your returned report.
- Root cause first; failing regression test first; then fix.
- Commits: conventional \`type(scope): subject\` (lowercase scope, subject <=64 chars, no trailing period), body lines <=100 chars, \`Refs: V6-VERIFY, ${w.cid}\` footer on feat/fix, NO attribution trailers (no Co-Authored-By, Signed-off-by, "Generated with", robot emoji) — the commit-msg hook rejects them. Small focused commits. Evidence logs may be committed under plans/sdd/V6-closeout/w2-${w.ws}/runs/.
- \`go run ./tools/devtool fmt\`/\`fmt-check\`, \`go vet\` on touched packages; \`go test ./test/docs\` and gen-*-docs --check when docs/generated inputs change.
- Tests: FOCUSED runs plus each touched package once in full; never ./... or devtool test/test-race (six other workstreams run tests on this machine and in the Linux container at the same time, so the machine is loaded: re-run any wall-clock failure alone before believing it, and say so). Never let a pipe mask go test's exit code.
- RESUMING: a first attempt at this exact task (workflow wf_0d8775ab-04e, 2026-09-23) was cut off by an account usage limit before it committed anything. FIRST run \`git status\` and \`git diff\` in your worktree: any uncommitted edits and any files under plans/sdd/V6-closeout/w2-${w.ws}/runs/ are that attempt's work. Read them, then adopt, revise or discard each deliberately (say which in your report); never assume they are correct or complete. ${w.prior || ''}
- Integrated-gate context (closeout/integration b070bbe, 2026-09-23, co-loaded and with the Windows host apparently asleep for part of the run): Linux non-root -race over every non-e2e package was green except test/guards TestCarriedDefects_WaveReportRequiresResolution (six carried defects awaiting dispositions — coordinator's job, not yours) and TestIntegration_HotPathWarmWithRealResidentState (known co-load timing row). The Windows whole-tree run was invalidated by the sleep; re-run alone, its daemon reds pass (FlushWaitsForABacklogThatKeepsPublishing 7.0 s, FlushSettlesQueuedSessionEventsBeforeSessionEnd 1.5 s, DeliveryRadix_ManyGenerationsOldRootsUsable 2.8 s).
- Processes: never kill a process you did not start. If you must stop your own processes, match on YOUR worktree path or your own scratch subdirectory, never on the shared session scratchpad root.
- Linux: container \`qompack-v6-linux-verification\`; the committed script plans/sdd/V6-closeout/linux/linux-nonroot-gate.sh runs an exact commit non-root with -race (see its header; use --prefix cx-w2-${w.ws}); never reuse or delete other /work dirs.
- Real Claude Code sessions are NOT allowed in this wave unless your task says so.
- The harness refuses report files from subagents: do NOT write report.md. Return the full report (root causes with evidence, what changed, exact commands + results, criterion changes, open items, owner decisions) in your returned summary; the coordinator commits it.`

const WS = [
  { ws: 'sessionend', prior: 'Your worktree has no leftover edits from it.', cid: 'C1.15/C1.13', task: `TASK C1.15 + C1.13 remainder + drained control-line sidecars.
(1) C1.15: Claude Code gives plugin SessionEnd hooks a SHARED 1.5 s budget ("SessionEnd hooks share a 1.5-second budget; if your settings set a longer per-hook timeout, Claude Code raises the budget to match, up to 60 seconds" — but per the packaging lane's real-host evidence "Timeouts set on plugin-provided hooks don't raise the budget"; verify the current docs at https://code.claude.com/docs/en/hooks and the evidence in plans/sdd/V6-closeout/packaging/). Qompack's \`flush\` SessionEnd hook was reported "Hook cancelled" in both live sessions. Wave 1 (ingest, a98bf9c + later) made flushRoute settle the session's deliveries before svc.SessionEnd with a bound of up to ~9 s — which the host will cancel. Redesign so the SessionEnd hook answers well inside ~1 s: e.g. the flush request becomes a durable, leased, ORDERED arrival of its session (WAL-appended + ACKed like an observe event) that the session lane processes after every earlier arrival, running the settle/drain/SessionEnd work asynchronously in the daemon; a cancelled/killed hook must lose nothing (the durable request is replayed on restart/drain). Keep the wave-1 ordering guarantee (SessionEnd never overtakes earlier same-session arrivals; monotone turns) and its tests (internal/daemon flush-ordering tests, flush_arrival_order_test.go). Nothing may depend on SessionEnd for correctness (Qompack.md §8.2): confirm recovery paths.
(2) C1.13 remainder: client-spool-only (unleased) deliveries — written by a hook that missed the ACK deadline — wait for a flush, admin.drain, restart or 120 s of idleness (IsIdle/DetectAfterSeconds) before being published. Make the daemon drain client spools promptly while the session is active (e.g. drain when a spool file appears/when the next ACK succeeds for that client, bounded and rate-limited), without busy loops and without violating the drain lock/ordering rules. Fix test/e2e's obsWaitDiag text/premise (observer_e2e_test.go) if it describes the old 30 s drain inaccurately — criterion rationale required.
(3) e2e lane's new defect: internal/daemon/drain.go (~L1152 at the e2e lane's base) publishes capture sidecars for leased NON-observe lines (spooled flush/checkpoint control lines); the publication audit and fsck then report 'unrecognized op' / 'publication requirement is unknown' permanently. Repro: plans/sdd/V6-closeout/e2e/runs/review-repro-drained-control-sidecar_test.go.txt. Fix the producer (no sidecar for control ops) and decide + implement tolerance for such sidecars already on disk (fsck/audit classify them as a known legacy artifact, not a defect — never silently delete evidence).
Verify with focused daemon tests (+ -race -count=5 on the new concurrency paths, CGO_ENABLED=1) and the e2e cases: TestE2E_ObserverThroughDaemon, TestE2E_ThinSliceDropsControlOnlyEdges, TestV3_CrashRecoveryReplaysObserverAndLedgerConsistently, TestUnknownSchema_NewerThanThisBuildDegradesWithoutRewriting (installs into user scope and uninstalls by design), and the six test/fault observer cases; Linux focused run via the script.
Scope: internal/daemon (handlers.go flushRoute, ingest.go, drain.go, delivery_order.go), internal/cli flush hook client, internal/store/cli audit tolerance, tests. Coordinate: another wave-2 workstream (lifetime) edits internal/daemon/daemon.go lifetime/idle, the SessionStart(compact) path and ipc shutdown; another (hookout) edits degradeBanner in handlers.go and wire_checkpoint.go. Keep your handlers.go edits confined to the flush route.` },

  { ws: 'lifetime', prior: "It left UNCOMMITTED phase-histogram instrumentation in internal/daemon/handlers.go (session_start.route/contract/seam/finish) and internal/daemon/rehydrate_service.go (rehydrate.latest/deps/selection/record) — a start on C1.16's attribution; it has no tests yet.", cid: 'C1.16/C1.17', task: `TASK C1.16 + C1.17 + two daemon robustness items.
(1) C1.16: in the packaging lane's live session 2 (plans/sdd/V6-closeout/packaging/evidence/live-s2-release-zip-autocompact), a SessionStart(source=compact) took 10.3 s under load and answered {} at the hook client's 10 s reply deadline, losing that rehydration even though the daemon emitted it. Find where the time goes (checkpoint finalize wait? rehydrate build? store reads? lock contention with ingest lanes/drain?) with instrumentation and a reproducible benchmark/test under concurrent ingest, and make the compact SessionStart answer reliably fast (target: well under 2 s p99 on this machine under the e2e workload; report distributions). The answer must never silently drop to {}: if the rehydration cannot be produced in time, answer with an explicit degraded note (still within the host cap; see internal/rehydrate hostcap.go) and keep the checkpoint recoverable via MCP.
(2) C1.17: the resident daemon outlives the Claude session and keeps the plugin's bin/qompack(.exe) open; on Windows this left a half-deleted plugin extraction dir and can break plugin update/uninstall (the host removes old version dirs ~14 days after update; see packaging evidence live-s2 "verify-exit=1" notes). Fix: e.g. idle exit when no session is active for a bounded time after the last SessionEnd, and/or run the daemon from a copy of the binary outside the plugin root (e.g. under the per-user qompack data dir, content-addressed by the binary's sha256, verified before exec) so the plugin dir is never locked. Preserve: single-daemon-per-project lock semantics, spawn races, Linux zombie-lock reclaim (5c8329e), no network I/O, and the security posture (docs/security.md: where binaries may run from; a copied binary must be integrity-checked and not writable by others). Document the chosen lifecycle in docs/architecture.md and troubleshooting.
(3) linux lane N1: the admin.shutdown reply can be lost — Stop's runCancel closes the in-flight connection (1/100 Linux -race runs). Fix per option (a): finish in-flight replies under a bounded write deadline in ipc Close, with a regression test that reproduces the loss deterministically (inject the ordering) and -race -count=50.
(4) hostperm lane remainder: internal/daemon/mcpop_test.go builds mcp.ToolDeps (~L138, ~L246) without a HostPolicy, so those tests read the machine's real Claude Code host policy (TestDaemonMCPOpDispatchesToolCall fails under a machine deny-all rule; evidence plans/sdd/V6-closeout/hostperm/runs/95*). Pass a hermetic hostperm policy (empty home, no env, no managed sources) as the integration rigs now do.
Scope: internal/daemon (daemon.go lifecycle/idle, spawn, SessionStart compact route), internal/cli spawn/launch, internal/ipc, internal/rehydrate/checkpoint only if the latency lives there, docs. Coordinate: the sessionend workstream edits handlers.go flushRoute, ingest.go, drain.go, delivery_order.go; the hookout workstream edits degradeBanner (handlers.go) and wire_checkpoint.go — keep your handlers.go edits to the SessionStart route.` },

  { ws: 'hookout', prior: "It left plans/sdd/V6-closeout/w2-hookout/runs/allsix-repro-windows-1.log: TestE2E_AllSixHooksExitZero/SessionStart fails ALONE on Windows at b070bbe (hooks_test.go:90 'SessionStart answers through hookSpecificOutput' — Expected value not to be nil).", cid: 'C1.18/C1.20', task: `TASK C1.18 + C1.20 + two unclassified e2e reds.
(1) C1.18: the daemon still renders and records PreCompact summarizer instructions (hookio.PreCompactOutput / SetPrecompactInstr producer, internal/daemon/wire_checkpoint.go; contract row precompact.custom_instructions_accepted warns FAILING) that no host accepts — the packaging lane made the hook client strip them (hookio.ConformOutput). Retire the producer cleanly: the checkpoint is still written; config key checkpoint.incrementalSpanInstruction's doc tag must stop claiming it "emits" an instruction (it is already marked retired-meaning); update the e2e PreCompactReply content rows that still expect instruction content (they should assert the conformant empty reply) with a criterion-change rationale; update the contract row semantics honestly (retired, not passing); docs (architecture, troubleshooting 189/473-ish stale "customInstructions" mentions, config-reference via its generator).
(2) C1.20: two hook fields are still unbounded by the host's 10,000-character cap (hookio.HostFieldMaxChars; count with hookio.HostChars): the SessionStart systemMessage degradeBanner (internal/daemon/handlers.go ~L862-869 quotes contract Expected/Observed with %q, no bound) and the UserPromptSubmit thrash-warning additionalContext (internal/observer, strings.Join of lines with no count bound). Bound both (truncate quoted values on a rune boundary to a fixed small budget; cap the warning list with a counted tail) so the whole field stays far under the cap, and pin each with a HostChars <= cap test including pathological inputs. Evidence: plans/sdd/V6-closeout/rehydrate-cap/ evidence/review-fix/unbounded-hook-outputs.txt.
(3) Unclassified e2e reds reported by the e2e lane: TestE2E_AllSixHooksExitZero/SessionStart ("hookSpecificOutput nil", reproduces alone) — likely an interaction with the packaging lane's ConformOutput (SessionStart with nothing to add may now legitimately emit {}): determine whether the test's expectation or the product is wrong, with evidence; and TestHooksExitZeroUnderFaults TempDir cleanup "directory is not empty" (a daemon or child still holding files at cleanup? — root-cause it).
Scope: internal/daemon (wire_checkpoint.go, handlers.go degradeBanner only), internal/hookio, internal/observer (thrash warning), internal/config doc tag, test/e2e rows, docs. Coordinate: sessionend (flushRoute/ingest/drain) and lifetime (daemon.go, SessionStart compact route, ipc) edit other parts of internal/daemon.` },

  { ws: 'rollover2', prior: "It left a Linux non-root -race BEFORE baseline of ./internal/daemon at b070bbe under plans/sdd/V6-closeout/w2-rollover2/runs/ (1383 pass / 0 fail / 1 skip; take the elapsed time from its console log/test.jsonl) — reuse it as your 'before' row instead of re-running it.", cid: 'C1.10/D6', task: `TASK — rollover follow-ups under owner decision D6 (2026-09-23): the rotation pause (2.3-6.8 s on a loaded host, every 65,536 deliveries) and the GC carry bounds are ACCEPTED as documented residuals, with diagnostics. Read plans/sdd/V6-closeout/rollover/report.md first.
(1) Diagnostics for D6: a loud log line + counter (and status/doctor visibility) whenever a rotation pause happens (duration recorded), and whenever GC halts because the carry exceeds 65,536 unacknowledged archived leases or a rotation fails closed at the 64 MiB carry; a Warn (once per store) BEFORE the first rotation stating that a backup taken before it is the only rollback path to an older build (docs/backup.md). Tests for each (counters/logs observable; no timing assertions that flake).
(2) Docs: architecture/troubleshooting/cannot-do/backup describe the pause, the carry bounds and the pre-rotation backup advice exactly; remove any claim that memory is bounded by the active window if it is not (rollover review major finding on gcrun.go memory growth with whole delivery history — state the true bound, or fix it if a bounded implementation is small and safe).
(3) Rollover review finding 5: predecessorsAcknowledged and leaseHeld (internal/daemon/delivery_order.go) do generation-store lookups while holding owner.mu and j.st (+35-45 us/call Windows, +8-10 us Linux with five archived windows). Evaluate whether the lookup can be moved out of the critical section or cached safely (the ordering gate is called per dispatch in the new per-session lanes); only change it if correctness (fail-closed, no stale answers) is provable; otherwise document.
(4) linux lane N3: internal/daemon under -race with GOMAXPROCS=4 cannot finish in 30 minutes on the shared host; the rollover-family tests take ~1430 s. CI's ubuntu \`test\` job runs the whole tree with -race (see .github/workflows/ci.yml) and would time out. Make the rollover tests fast WITHOUT weakening what they prove (e.g. smaller test-only rotation thresholds via the existing seam vars so each rotation needs far fewer deliveries, parallel subtests, removing redundant sleeps) — keep every assertion; show before/after package times under -race on Linux via the script (non-root) and on Windows.
Scope: internal/daemon delivery_*.go and their tests, internal/store gcrun.go/gc_delivery_segments.go, internal/cli status/doctor rows for the new counters, docs. Coordinate: sessionend edits delivery_order.go too (lanes); keep your delivery_order.go change minimal and in the two lookup functions only.` },

  { ws: 'lint', prior: 'Your worktree has no leftover edits from it.', cid: 'C1.19', task: `TASK C1.19 — make \`go run ./tools/devtool lint\` fully green on the integrated tree, without weakening any check.
(1) bindeps: 4 violations — golang.org/x/sys/unix reaches the shipped linux/darwin binary via internal/paths (pre-existing on cf31e01). Find which commit introduced the import and why (git log -S). Then either replace the x/sys/unix use with the standard library (syscall/os) if equivalent, or make the case for adding it to the bindeps allow-list: check how the allow-list is defined and justified (tools/devtool, docs/security.md or ADRs), whether go.mod already requires x/sys, license (THIRD_PARTY_NOTICES.md, devtool licenses --check), govulncheck — and record the rationale. Do not simply edit the allow-list without that record.
(2) stubskips: reported skip reasons that are not in the permitted set, in: internal/daemon TestDeliveryPath_V6_RefusesAliasedSegmentParent and DrainAfterPhysicalScopeChanges, internal/hookio TestCaptureScope_JunctionSwapDefeatsLexicalContainment, internal/store SymlinkComponentInBackupTree (all skip on Windows hosts without symlink privilege). Read how stubskips classifies permitted skip reasons and make these conform honestly (e.g. use the repo's standard platform/privilege skip helper so the reason is one the guard knows), or make the tests not need the skip (e.g. use a directory junction on Windows where the property is equivalent). Never delete the tests.
(3) Run the full \`go run ./tools/devtool lint\` ONCE at the end (it includes a whole-tree stubskips pass — that is allowed for this task only; note the machine is loaded, so a timeout inside stubskips is load, re-run that sub-check alone with --only if the tool supports it) and \`go run ./tools/devtool fmt-check\`, plus the Windows \`lint-windows\` equivalent if distinct. Report every sub-check's result.
Scope: internal/paths (if replacing), tools/devtool lint config/allow-list (only with recorded rationale), the four tests, THIRD_PARTY_NOTICES.md if needed, docs.` },

  { ws: 'eval2', prior: 'Your worktree has no leftover edits from it.', cid: 'C5.4', task: `TASK C5.4 completion — independent verification and the two open items of the evaluation harness. The wave-1 eval branch's code (internal/eval live*.go, tools/devtool/liveeval*.go, testdata/eval/live/, plans/sdd/V6-closeout/eval/preregistration.md) was written after its reviewer had already looked at an empty branch, so it has had NO independent review. Read plans/sdd/V6-closeout/eval/report.md.
(1) Review it adversarially yourself first, and fix real defects (failing tests first): usage accounting (never double-count resumed/overlapping usage; per-category input/cache-creation/cache-read/output; the compaction request; rate table dated and labelled estimate), grading (hidden checks copied in after the session; reference solutions pass, untouched fixtures fail), the real-home guard (settings.json/installed_plugins/known_marketplaces hashes, plugins/{cache,marketplaces,data}/qompack* dirs) and cleanup, the stock arm truly has no plugin, plugin-dir vs marketplace install paths, stream-json driving and step waits, statistics (Wilson/Newcombe, the pre-registered non-inferiority rule), and that the pre-registration is frozen (hash) and matches the code.
(2) \`qompack eval --json\` still exits 1 because commands.Deps.EvalArtifacts is nil. Wire a provider so the in-plugin command reports the latest live-eval summary.json (and the deterministic replay artifacts) with honest qualification (agent-executed, model, sample size, intervals), or explain precisely why it cannot; docs/commands/user-guide via generators.
(3) Stale text: ruling R7-2 ('deliberately left unwired') in tools/devtool/releasescopereport.go and the SP17-M7-07 row of docs/release.md; replay live-window off-by-one note (document or fix with rationale).
(4) Dry-run only (no model calls): \`go run ./tools/devtool live-eval ... --dry-run\` against a bundle built from THIS integrated tree (\`go run ./tools/devtool bundle --target windows/amd64 ...\`), confirming the task set hash, arms and install flow resolve. No real sessions in this workstream.
Scope: internal/eval, internal/commands/cli eval wiring, tools/devtool liveeval*/releasescopereport.go, testdata/eval/live, docs.` },
]

WS.push({ ws: 'wintriage', prior: 'CORRECTION for this workstream only: it is NEW in wave 2b, so there was no first attempt; plans/sdd/V6-closeout/w2-wintriage/runs/ holds the coordinator\'s repro record (int1-win-triage-security.json/.log, uncommitted — commit it with your first commit).', cid: 'C3.2', task: `TASK — the one Windows red of the integrated gate that reproduces ALONE, plus two slow fault cases.
(1) test/security TestSecurity_ArchivedTextIsDataNeverAnInstruction fails alone on Windows at b070bbe (coordinator run 2026-09-25, quiet machine, CGO_ENABLED=0, go test -count=1 -run ... ./test/security): "security: the observer never recorded a file version of docs/NOTES.md into <tmp>\\proj\\.qompack\\index\\files.jsonl within 30s (daemon lock pid N held=true)". The Read capture itself IS indexed (requireIndexed passed first); only the file version (index/files.jsonl) is missing. The same run's other four security cases pass alone, and the Linux non-root -race run of the same commit passed all 24 test/security cases — so this is Windows-specific. The test is hermetic (sibling HOME/USERPROFILE), so the machine's real Claude Code settings are not involved. Root-cause it: first re-run it alone a few times on Windows to confirm it is deterministic, then find what differs from the passing Linux path (the injection text embeds a Windows sentinel path; file-version recording for Read — observer / observation binding (intent-first index/observations.jsonl, exact-bytes original intent) / redaction / hostperm path handling / capture scope). Bisect across the wave-1 merges if useful (\`git log --first-parent cf31e01..b070bbe\` on closeout/integration; merges: ingest, e2e, config, hostperm, rollover, perfstore, perfobs, eval, linux, packaging, rehydrate-cap). Fix at the source (product or fixture — if the fixture is wrong, prove it with evidence and write a criterion-change rationale), with a failing regression test first. Confirm the case passes alone -count=5 on Windows and on Linux via the script, then run the whole test/security package alone once on Windows.
(2) Run alone on Windows, TestFault_PublicationBoundaries passes but two subcases are slow: config_json_corrupt 61.8 s and delivery_seal_torn_slot 32.1 s (all other subcases take about 3 s). Find out what they wait on. If a HOOK or the daemon's answer to a hook blocks for tens of seconds in those fault states, that is a product defect: the host would time the hook out. Fix it, or show with evidence that only the test's own wait-for-absence bound is slow, and propose a sound faster assertion that proves the same thing without weakening it.
Scope: whichever package owns the root cause, plus test/security and test/fault. Coordinate: sessionend edits internal/daemon handlers.go flushRoute/ingest.go/drain.go/delivery_order.go; lifetime edits daemon.go, the SessionStart route and ipc; hookout edits wire_checkpoint.go, degradeBanner and the observer thrash warning; rollover2 edits delivery_*.go. Keep any edit in those files minimal and say so.` })

const RESULT = { type: 'object', properties: {
  status: { type: 'string', enum: ['done', 'partial', 'blocked'] }, head: { type: 'string' },
  commits: { type: 'array', items: { type: 'string' } }, root_cause: { type: 'string' }, summary: { type: 'string' },
  tests: { type: 'array', items: { type: 'object', properties: { command: { type: 'string' }, result: { type: 'string' } }, required: ['command', 'result'] } },
  criterion_changes: { type: 'array', items: { type: 'string' } }, open_issues: { type: 'array', items: { type: 'string' } },
  needs_owner: { type: 'array', items: { type: 'string' } },
}, required: ['status', 'head', 'commits', 'summary', 'tests', 'open_issues', 'needs_owner'] }
const FINDINGS = { type: 'object', properties: {
  verdict: { type: 'string', enum: ['sound', 'needs-fixes', 'unsound'] },
  findings: { type: 'array', items: { type: 'object', properties: {
    severity: { type: 'string', enum: ['blocker', 'major', 'minor', 'nit'] }, location: { type: 'string' },
    issue: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' },
  }, required: ['severity', 'location', 'issue', 'evidence', 'fix'] } },
}, required: ['verdict', 'findings'] }

const LENS = 'Lenses: (a) root cause proven and fixed at the source; correctness incl. concurrency (races, deadlocks, lock order, goroutine leaks), durability/crash semantics (fsync ordering, WAL retention, idempotency, identity never re-minted), fail-closed paths, Windows vs POSIX, bounded memory/CPU; (b) check-weakening (deleted/loosened assertions, skips, nolint/nomagic, lowered thresholds, regenerated goldens, widened timeouts, tests bent to buggy output) and legitimacy of every criterion change; (c) docs consistent with behaviour, generated docs via generators; (d) commit hygiene (conventional subjects, Refs footer, no attribution trailers); (e) was the whole task done, or parts silently dropped?'

const results = await pipeline(
  WS,
  (w) => agent(`${COMMON(w)}\n\n${w.task}`, { label: `impl:${w.ws}`, phase: 'Implement', schema: RESULT }),
  async (impl, w) => {
    if (!impl) return { w, impl: null, review: null }
    const review = await agent(`You are an independent, adversarial reviewer for Qompack V6 close-out wave-2 workstream "${w.ws}" (${w.cid}). Worktree ${ROOT}/qompack-cx-w2-${w.ws}, branch closeout/w2-${w.ws}, base ${BASE}. The task was:\n---\n${w.task}\n---\nImplementer result: ${JSON.stringify(impl)}\nReview \`git -C ${ROOT}/qompack-cx-w2-${w.ws} log ${BASE}..HEAD\` and the full diff. READ-ONLY: do not edit, commit, stash or reset. You may run focused tests (never ./...; never kill processes you did not start; the machine is loaded — re-run a timing failure alone before believing it). No real claude sessions.\n${LENS}\nReturn findings with severity, file:line, evidence and a concrete fix; if sound, verdict "sound" and an empty list.`,
      { label: `review:${w.ws}`, phase: 'Review', schema: FINDINGS, effort: 'high' })
    return { w, impl, review }
  },
  async (r) => {
    if (!r.impl) return { ws: r.w.ws, impl: null, review: null, final: null }
    const actionable = (r.review ? r.review.findings : []).filter((f) => f.severity !== 'nit')
    if (actionable.length === 0) return { ws: r.w.ws, impl: r.impl, review: r.review, final: r.impl, fixRan: false }
    const final = await agent(`${COMMON(r.w)}\n\nYou are the FIX seat for this workstream (the implementer has finished). Its task was:\n---\n${r.w.task}\n---\nIndependent reviewer findings:\n${JSON.stringify(actionable, null, 1)}\nVerify each independently; fix the correct ones (failing test first where applicable) and re-run focused tests; rebut wrong ones with evidence. Blockers/majors must be resolved or rebutted. Return the final state with a "Review resolution" section (finding -> action/rebuttal) in your summary.`,
      { label: `fix:${r.w.ws}`, phase: 'Fix', schema: RESULT })
    return { ws: r.w.ws, impl: r.impl, review: r.review, final, fixRan: true }
  },
)
return results
