export const meta = {
  name: 'v6-closeout-wave13',
  description: 'Wave 13 close-out: live-lane defects (ledger, intent, restore, pins/checkpoint, diagnostics, MCP responses); reviewed, fixed and verified',
  phases: [
    { title: 'Implement', detail: 'six workstreams off closeout/integration 84d2512' },
    { title: 'Review', detail: 'independent adversarial review' },
    { title: 'Fix', detail: 'resolve confirmed findings' },
    { title: 'Verify', detail: 'check the fix seat resolved every non-nit finding' },
  ],
}

const ROOT = 'C:/Users/Quant/Documents/Programming/Projects'
const BASE = '84d2512'
const SCRATCH = 'C:/Users/Quant/AppData/Local/Temp/claude/C--Users-Quant-Documents-Programming-Projects-qompack/9c57653d-e5ff-4791-8ab4-ad49457994c1/scratchpad/w13'

const COMMON = (w) => `You are one of the parallel workstreams (six seats: ledger, intent, restore, pinsckpt, diag, mcpresp; daytime) closing out the Qompack V6 verification (Qompack is a Go Claude Code plugin: hooks -> resident daemon -> content-addressed store under .qompack/, an MCP retrieval server, slash commands). Coordinator ledger (read it; do NOT edit it): ${ROOT}/qompack-v6/plans/V6-CLOSEOUT-CHECKLIST.md — owner decisions D1-D38 and the coordinator defaults are there. Earlier workstream reports are committed on your base under plans/sdd/V6-closeout/<ws>/report.md (wave 1: ingest, e2e, config, hostperm, rollover, perfstore, perfobs, eval, linux, packaging, rehydrate-cap; wave 2b: w2-*; wave 3/4: w3-startroute, w3-paths, w3-e2ereds, w3-eval3, w4-syncs, w4-e2eflakes; wave 5: w5-coldstart, w5-home, w5-winfiles, w5-helpers, w5-dirsync, w5-deps; wave 6: w6-borrow, w6-config, w6-ckptsync, w6-gcserial, w6-linuxrows; wave 7: w7-spawnclaim, w7-layout, w7-sp08d3, w7-docs, w7b-selftest, w7b-checkpoint; wave 8: w8-sp08d3fix, w8-stagerace, w8b-polish) — read the ones relevant to your task first.

YOUR WORKTREE: ${ROOT}/qompack-cx-w13-${w.ws} on branch closeout/w13-${w.ws}, cut from closeout/integration @ ${BASE} (every earlier wave merged). The Bash tool resets cwd between calls: prefix every command with \`cd ${ROOT}/qompack-cx-w13-${w.ws} &&\` or use absolute paths. Never edit other worktrees. Never push, tag, merge, rebase or reset other branches, change git config/hooks, or SendMessage anyone. Your scratch files go under ${SCRATCH}/${w.ws}/ (create it); never delete anything else in that scratchpad.

Hard rules (owner directives, non-negotiable):
- Never weaken a check: no t.Skip, no //nolint, no //nomagic:allow added to silence something, no lowered threshold/budget, no golden regenerated to match broken output, no deleted or loosened assertion, no widened timeout that hides a defect. Criterion changes only with a written rationale in your returned report.
- Root cause first; failing regression test first; then fix.
- New budget/bound numbers are the owner's: implement them behind a named constant with a derivation comment, and list each one (value, derivation, what breaks if it is wrong) under needs_owner; the coordinator gets approval before merging.
- Commits: conventional \`type(scope): subject\` (lowercase scope, subject <=64 chars, no trailing period), body lines <=100 chars, \`Refs: V6-VERIFY, ${w.cid}\` footer on feat/fix, NO attribution trailers (no Co-Authored-By, Signed-off-by, Claude-Session, "Generated with", robot emoji) — the commit-msg hook rejects them. Small focused commits. Evidence logs may be committed under plans/sdd/V6-closeout/w13-${w.ws}/runs/.
- \`go run ./tools/devtool fmt\`/\`fmt-check\`, \`go vet\` on touched packages (Windows and GOOS=linux); \`go test ./test/docs\` and gen-*-docs --check when docs/generated inputs change. Use \`go run ./tools/devtool lint --only=golangci-lint,nomagic,importgraph,testdeps,bindeps,sleepcheck,docmarkers,runpatterns\`: never the stubskips sub-check (it runs a whole-tree go test).
- Tests: FOCUSED runs plus each touched package once in full; never ./... or devtool test/test-race (four other workstreams run tests on this machine and in the Linux container at the same time, so the machine is loaded: re-run any wall-clock failure alone before believing it, and say so). Never let a pipe mask go test's exit code.
- Every \`go test -run\` pattern you quote in your report must match a real test name exactly (the runpatterns lint checks committed reports); name temporary diagnostics as such.
- Processes: never kill a process you did not start. If you must stop your own processes, match on YOUR worktree path or your own scratch subdirectory.
- Linux: container \`qompack-v6-linux-verification\`; the committed script plans/sdd/V6-closeout/linux/linux-nonroot-gate.sh runs an exact commit non-root with -race (see its header; use --prefix cx-w13-${w.ws}; pass --repo and --out as Windows-style C:/ paths, a POSIX /c/ path is refused); never reuse or delete other /work dirs.
- CPU: the owner uses this laptop interactively. Any load generator you start must be bounded with \`timeout\` to at most 20 minutes per run and at most 8 busy processes (of 22 cores), and you must stop it when the measurement ends; never leave one running. Stop your own background diagnostics before you finish.
- Never create, read or modify the real ~/.qompack or ~/.claude in tests; use a fake HOME/USERPROFILE. Real Claude Code sessions are NOT allowed.
- The harness refuses report files from subagents: do NOT write report.md. Return the full report (root causes with evidence, what changed, exact commands + results, criterion changes, open items, owner decisions) in your returned summary; the coordinator commits it.`

const MACHINE = `MACHINE LIMITS FOR THIS SEAT (override the general rules): Phase 3 gates run on this laptop now and memory is tight. The Linux container is STOPPED on purpose: do NOT start it and do not run the Linux gate script; the coordinator runs Linux verification later. On Windows use \`-p 2\`, no load generators. The Phase 3 chain logs to C:/Users/Quant/Documents/Programming/Projects/qompack-v6/plans/sdd/V6-closeout/phase3/chain-2.log: while that file has a "win-timing start" line with no later "win-timing exit" line, an ISOLATED timing gate is running and you must not run anything load-bearing (no hot-path row, no test/integration package, no -race, no benchmark) until it ends; do code reading and cheap deterministic unit tests meanwhile. Run at most one load-bearing test at a time.`

const EV = `EVIDENCE: the Phase 4 live lane ran real Claude Code 2.1.280 sessions on the frozen candidate 3 (d5598eb4) with the packaged bundle. Its report is plans/sdd/V6-closeout/live/report.md in your worktree (evidence dirs beside it under plans/sdd/V6-closeout/live/uat/, c4/, recovery/). Read the rows named below and their evidence files before touching code. Coordinator decision D45 (ledger) says these are fixed before 0.3.0.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and six seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, and do NOT run the hot-path rows (TestIntegration_HotPath*, TestV3_HotPath*) or whole test/integration / test/e2e packages; run only the focused rows you add or touch plus the touched packages in full once. The Linux container is STOPPED: do not start it. Real Claude Code sessions are NOT allowed: reproduce each live finding with a deterministic test (a real daemon/store/hook process in a temp project is fine) that is RED before the fix. The coordinator re-runs the live rows on the fixed candidate.
Other seats in this wave (do not fix their items; if your root cause turns out to be theirs, say so and stop): ledger (elimination ledger, MCP self-record turns, timeline), intent (rehydration intent/corrections/fork), restore (backup/restore/fsck segments/cross-version), pinsckpt (pins view, checkpoint pointers), diag (sentinel scan, status/doctor diagnostics), mcpresp (MCP response bounds/selectors/messages, UAT docs).`

const WS = []

WS.push({ ws: 'ledger', cid: 'C4.2/C4.4', effort: 'xhigh', reviewEffort: 'high', task: `TASK — the elimination ledger and MCP self-record attribution.
${EV}
(1) install part D1 / F-UAT01-2 (fsck exits 1 after any session with an MCP call): the MCP server's own tool_use record (tool mcp__qompack__<tool>, id qompack-mcp:...) is indexed at turn 0 after hook records of later turns; fsck index.tool_use flags 'reports turn 0 after turn N; turns are monotone'. Evidence uat/UAT-01/cli/x-fsck-json, store/index_tool_use.jsonl; uat/UAT-12/cli/51-52; UAT-02 c42-counts.json. Fix at the source: the self-record must carry the session and turn it belongs to (the daemon knows the live session's current turn), or, if the design says MCP records are outside the turn sequence, fsck must say so explicitly — decide from 00-ARCHITECTURE/Qompack.md and justify. Existing stores already holding turn-0 MCP records must not fail fsck forever: handle them compatibly.
(2) retrieval D1: the elimination ledger is opened lazily on the daemon's first compaction (internal/cli/daemon.go installMCPTools -> liveLedger; internal/daemon/rehydrate_service.go, wire_checkpoint.go), so before a compaction and after any daemon restart record_eliminated and already_tried answer {"found":false,"available":false,"reason":"elimination ledger not present in this build"} — a body outside already_tried's documented states. Open it when the daemon serves the project (or on first MCP use), so both tools work from the first turn; when it genuinely cannot open, answer the documented state unavailable with degraded true.
(3) retrieval D2: session-scoped eliminations are stored with "session":"" because the ledger is opened with no session, so negknow visible() shows them to later sessions. Record the calling session (the MCP server knows its session from the host, or the daemon's live session binding) and make visibility honour it.
(4) retrieval D3: already_tried keeps answering active in the session that changed a dependency; RefreshStaleness runs only at ledger open, startup/resume, or idle work after 120 s. Make an already_tried answer reflect dependency changes captured so far (refresh on read or on capture of a dependency's new version, whichever is cheaper and correct).
(5) retrieval D5: checkpoints sealed in such daemons carry decisions [] and eliminated [] even after an active elimination (possibly because MCP-origin records carry turn 0 and checkpoint/decisions.go fromEliminations skips turns before the cut). Prove the cause and fix it so /qompack:why can answer for that session; also the why evidence_withheld 'the capture has no usable path provenance' for an MCP-origin record: say whether that is correct and fix if not.
(6) retrieval D8: timeline in a live session returns one open segment (turns 0-0, 0 tokens) after 12 turns and accepts from > to (refuse from > to as a tool error).
Update docs/mcp-tools.md / docs/user-guide.md where the shipped behaviour changes. Scope: internal/negknow, internal/mcp, internal/cli daemon wiring, internal/daemon (ledger wiring, turn attribution), internal/checkpoint decisions, internal/store fsck tool_use check, their tests.` })

WS.push({ ws: 'intent', cid: 'C4.3', effort: 'xhigh', reviewEffort: 'high', task: `TASK — rehydration of the user's intent.
${EV}
(1) F-UAT04-1: the rehydrator injects only the first 8,192 bytes of a 17,774-char first prompt, cut mid-word ('reconciliat'), under 'Original user intent (verbatim from L0 capture — never summarized)'; no OVERFLOW/tier-1 entry or pointer, the state file says truncated:false, and a spurious intent_mismatch drop is logged LOUD at every compaction. The checkpoint and the L0 capture hold all of it. Evidence uat/UAT-04/injected-block-first.txt, store/, notes.txt. D5 (whole records) and UAT-05's 'record cut mid-record' criterion forbid this. Find the 8 KiB cut (a capture/read bound?) and the mismatch check; fix so the original prompt is injected whole when it fits the section budget, and when it does not, it is dropped as a whole record with a named overflow entry and a pointer (expand by hash) — never cut mid-record — and truncated/overflow state is truthful. No spurious intent_mismatch.
(2) F-UAT05-1 / F-UAT06-2: an explicit user correction ('actually, use X instead of Y') never reaches user_intent.evolution in any checkpoint or block, so rehydration re-injects only the superseded requirement (uat/UAT-05/run1-checkpoint-0001.json, uat/UAT-06/section2-in-order.txt). Find how evolution is supposed to be populated (Qompack.md / 00-ARCHITECTURE: user_intent.evolution, the prompt records) and why it stays empty on real sessions; fix so later user prompts that amend the task are carried in order after the original, within the section budget (whole records), so the current authority is visible.
(3) F-UAT06-1: after \`claude --resume <id> --fork-session\`, section 2's 'verbatim original intent' is the fork's own first prompt and the checkpoint's true original is overridden as an intent_mismatch (uat/UAT-06/block3-C-fork-compact.txt, diff-block2-vs-fork-block3.txt). A fork continues the parent's task: keep the parent's original intent (the fork's first prompt is an evolution entry), and label provenance truthfully.
Tests: golden/fixture tests over real prompt records (long prompt, corrections, fork chain) RED before the fix. Keep the SP08-D3 host-order rules (D35/D38) intact. Scope: internal/rehydrate, internal/checkpoint intent assembly, internal/observer prompt capture if the cut is there, their tests; docs where behaviour is described.` })

WS.push({ ws: 'restore', cid: 'C1.7/C4.8', effort: 'xhigh', reviewEffort: 'high', task: `TASK — backup/restore after ordinary use, and fsck truthfulness.
${EV}
(1) F-UAT03-2 (= F-UAT02-4): after a CLEAN idle exit, index/segments.jsonl records segment N encoded into a checkpoint seq (0002) that is never written; fsck index.segments fails and a backup taken after it restores with integrity FAILED (uat/UAT-03/cli/s5-fsck-json, probe/12-backup-restore; UAT-02). Find the idle-work path that records the encode before (or without) publishing the checkpoint; fix the ordering so the index never names an unpublished checkpoint (publish first, or record only after publish), and make fsck/restore treat an existing store that already has such a dangling claim compatibly (a named, recoverable condition, not integrity FAILED), with a regression test driving a real idle exit.
(2) F-C49-2: backup create/verify pass but restore fails 'restored tool reference root ... does not resolve' when an MCP ephemeral record's root was garbage-collected (c4/C4.9/cli/c-00-backup-restore.*); fsck treats the same reference as an ok note with a gc tombstone. Make restore's integrity agree with fsck: a reference a GC tombstone accounts for is not a restore failure; and make verify and restore judge the same thing.
(3) install D3 (cross-version): the candidate treats the previous build's UserPromptSubmit capture sidecars as unpublished ('stage 1 only, no reference joined'): fsck captures/publication fail, backup restore of a pre-upgrade backup exits 1, and the first post-upgrade daemon start logs LOUD unpublished_captures=4 (uat/UAT-12/cli/30,32,33,27,51; store/logs_LOUD.log). The live lane used dev build 301a8e9; the release that matters is the public v0.2.0 tag. Establish whether a store written by v0.2.0 has the same sidecar shape (read the v0.2.0 code: git show v0.2.0:<path>) and make the candidate read every sidecar shape a released build wrote as published when its reference exists (never re-mint identity). Test with a fixture store written by the v0.2.0 code path (build v0.2.0 into a temp dir if needed, or a committed minimal fixture).
(4) Low: every \`backup restore --json\` response carries the note 'checkpoint-chain and delivery-seal integrity are NOT covered — run packaged fsck --seal-check' while the same response says the full dual-reader seal check passed and docs/backup.md says restore runs it: make the note truthful.
(5) F-UAT03-4: a store copied with a stale run/daemon.lock from another path never starts a daemon, and the spawned daemon exits 0 with no log line. At minimum log a named reason; if the lock's recorded project path differs from this project, treat it as stale per the existing lock rules (do not weaken D27's lock semantics).
(6) F-C49-3: the missing-object reason wrongly says 'damaged object preserved' — make it say missing.
Update docs/backup.md and docs/troubleshooting.md. Scope: internal/store (fsck, restore, maintenance, gc interplay), internal/daemon idle work/segment encode ordering, internal/cli backup, their tests.` })

WS.push({ ws: 'pinsckpt', cid: 'C4.3', effort: 'high', reviewEffort: 'high', task: `TASK — pins and checkpoint pointers.
${EV}
(1) F-UAT05-2: a /qompack:pin made while the daemon runs is written to pins/invariants.jsonl but not to the pins/invariants.json view (fsck 'the view is stale'); the next PreCompact checkpoint and rehydration block omit it with dropped [] and degraded false; it appears only after a daemon restart (uat/UAT-05/cli/run1-fsck-json, run1-injected-block.txt). Find who owns the view (CLI pin vs daemon) and make a pin made while the daemon runs reach the view and the very next checkpoint/block; if a pin cannot be included, it must be a named drop, never silent.
(2) F-UAT03-1: PreCompact checkpoints carry empty encoded_segments, pointers.files and pointers.tools after captured reads (uat/UAT-03 evidence). Determine from the design whether these must be populated at PreCompact on a real session, find why they are empty, and fix; if empty is correct at that point, show it from the spec and say what the live test should have expected.
Scope: internal/pins (or wherever pins live), internal/cli pin command, internal/daemon checkpoint assembly, internal/checkpoint pointers, their tests; docs/commands.md if the pin behaviour text changes.` })

WS.push({ ws: 'diag', cid: 'C4.2/C4.5', effort: 'high', reviewEffort: 'high', task: `TASK — the §12.1 sentinel scan and the diagnostics users read.
${EV}
(1) retrieval D4 (HIGH): the §12.1 sentinel scan reads only the last 256 KiB of the transcript (internal/daemon/handlers.go sentinelScanTailBytes). One large first-turn tool result (a 363 KB Read) pushed the SessionStart probe sentinel (at byte ~800) out of the scanned tail, both chances missed, the monitor degraded the session to passive, and SessionStart:compact injected no rehydration (uat/UAT-11 sessionstart-hook-responses.json, sentinel-offsets.json, LOUD.log). Fix so an ordinary large tool result cannot defeat the probe: e.g. remember the sentinel's offset once found, or scan from the start of the file up to a bound, or scan forward from the last known offset — choose the simplest correct design with bounded I/O and justify it; regression test with a transcript whose sentinel sits before a >256 KiB entry.
(2) install D4 / retrieval D7 / C45-1: \`qompack status\` reports contract assertions FAILING in healthy sessions: mcp.server_registered 'initialize-not-received' while the host connected the server and it served calls, and transcript.readable 'transcript_path does not exist' because the host creates the transcript after SessionStart:startup in -p mode. Fix the assertions so a healthy session reads healthy (e.g. mcp.server_registered satisfied by any MCP initialize or served call this daemon saw; transcript.readable pending, not failing, until the host has written it, failing only if it never appears) while real failures still fail.
(3) install D5: doctor captures.unpublished reads degraded ('5 gaps across 7 sidecars') on a candidate-only store while fsck captures/publication pass. Make them agree (one definition), with a test.
(4) Small diagnostics: status prints 'daemon: status refused: ' with an empty reason when no daemon is up (F-UAT03-3, F-C49-1, D9); status prints p95/p99 above max (106.50 vs 99.00 ms; percentile from buckets vs exact max: clamp to max or report bucket bounds honestly); the day log records nothing about a terminated daemon or a spool replay at the next start (add one Info line each); maintenance and MCP retrieval refuse for ~90 s after a daemon is terminated (F-UAT05-4, F-C49-4): find why (stale lock/lease timeout?) and either shorten safely or make the refusal message say how long and why.
(5) The abandoned-session detector ends a live session silent past idleExitSeconds: document it in docs/troubleshooting.md (default 1800 s).
Scope: internal/daemon (handlers sentinel, contract monitor), internal/commands status/doctor, internal/store doctor rows, their tests; docs/troubleshooting.md.` })

WS.push({ ws: 'mcpresp', cid: 'C4.4/C4.10', effort: 'high', reviewEffort: 'high', task: `TASK — MCP response bounds, selectors, messages, and the UAT doc fixes the live audit asked for.
${EV}
(1) install D2: runtime.mcp.maxResponseBytes (262,144) caps the content span, not the response: expand and re_read with full:true return 263,559 / 263,567 bytes of text in 266,291 / 266,318-byte JSON-RPC lines (uat/UAT-12/cli/20-mcp-probe.json). Make the bound hold for what the tool returns (the serialized result text, JSON-escaping included), with a continuation (next_span) when content is cut, and a test with escape-heavy content.
(2) install D6 / F-UAT02-1: expand/re_read responses carry no fidelity or coverage field, though docs/user-guide.md and UAT-12 say fidelity and coverage qualify them. Either add them to the result the model sees (preferred if the data exists; the model cannot see result._meta) or correct the docs; justify.
(3) retrieval D6: recall's \`path:<glob>\` is not a glob (internal/store/search.go matches equality, suffix, substring); \`tool:Read\` returns nothing because the selector takes display names (FileRead). Make \`path:\` accept globs (path.Match semantics on slash paths, keeping the existing exact/suffix match for plain strings) and \`tool:\` accept host tool names as well as display names; docs updated.
(4) retrieval D9 / C4.7 F1-F2: an empty MCP recall query is answered (the CLI refuses it: refuse it in MCP as a tool error too); already_tried with an empty target or approach answers absent (refuse as a tool error); the never-stored-hash expand miss says 'complete content provenance could not be established' without saying what was searched (say it); in mode off the MCP recall error is 'the qompack daemon returned an empty result' (say Qompack is switched off by runtime.mode) and \`qompack mcp\` writes .gitignore, logs/ and state/mcp.json into a mode-off project (write nothing in mode off).
(5) C45-2: docs/commands.md: when a slash command's \`qompack\` exits non-zero the host shows only its own 'Shell command failed' line; say so (e.g. /qompack:eval in a user project).
(6) docs/uat.md (the live audit's findings, report.md 'Audit findings'): the intro still says no scenario has been executed — update it to say the agent-executed live lane (D3) ran on candidate 3 and which rows are re-run after fixes; UAT-03 and UAT-06 Result blocks must name the non-default idle-exit override (QOMPACK_RUNTIME__DAEMON__IDLEEXITSECONDS=120) and that UAT-02 reproduced F-UAT02-4 at the default; UAT-02's headline must say the non-exact-fidelity capability was unverified on this host; UAT-12 must add (c) the binary file decoded as text by the host before Qompack saw it. Do NOT change any expectation text or verdict beyond these. Also UAT-01 step 4 (expects 0.1.0 at plugin/.claude-plugin/plugin.json; the bundle ships 0.3.0 at .claude-plugin/plugin.json) and step 8 ('retired' vs self-test not-yet-implemented): fix the expectation only if the doc is simply stale versus shipped, and say why; the recovery C1.7 notes (plans/sdd/V6-closeout/live/recovery/C1.7/notes.txt) must be restated as 'rehearsed on a Read-only, checkpoint-free store', citing F-UAT03-2, F-C49-2 and the cross-version defect as open at that time.
Scope: internal/mcp (response assembly, selectors), internal/store/search.go, internal/cli mcp startup in mode off, docs (mcp-tools.md, user-guide.md, commands.md, uat.md), the C1.7 notes file.` })

const RESULT = { type: 'object', properties: {
  status: { type: 'string', enum: ['done', 'partial', 'blocked'] }, head: { type: 'string' },
  commits: { type: 'array', items: { type: 'string' } }, root_cause: { type: 'string' }, summary: { type: 'string' },
  tests: { type: 'array', items: { type: 'object', properties: { command: { type: 'string' }, result: { type: 'string' } }, required: ['command', 'result'] } },
  criterion_changes: { type: 'array', items: { type: 'string' } }, open_issues: { type: 'array', items: { type: 'string' } },
  needs_owner: { type: 'array', items: { type: 'string' } },
}, required: ['status', 'head', 'commits', 'summary', 'tests', 'open_issues', 'needs_owner'] }
const FINDINGS = { type: 'object', properties: {
  verdict: { type: 'string', enum: ['sound', 'needs-fixes', 'unsound'] },
  findings: { type: 'array', items: { type: 'object', properties: {
    severity: { type: 'string', enum: ['blocker', 'major', 'minor', 'nit'] }, location: { type: 'string' },
    issue: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' },
  }, required: ['severity', 'location', 'issue', 'evidence', 'fix'] } },
}, required: ['verdict', 'findings'] }

const LENS = 'Lenses: (a) root cause proven and fixed at the source; correctness incl. concurrency (races, deadlocks, lock order, goroutine leaks), durability/crash semantics (fsync ordering, WAL retention, idempotency, identity never re-minted), fail-closed paths, Windows vs POSIX, bounded memory/CPU; (b) check-weakening (deleted/loosened assertions, skips, nolint/nomagic, lowered thresholds, regenerated goldens, widened timeouts, tests bent to buggy output) and legitimacy of every criterion change; (c) every new bound/budget number is named, derived, and listed for the owner; (d) docs consistent with behaviour, generated docs via generators; (e) commit hygiene (conventional subjects, Refs footer, no attribution trailers); (f) was the whole task done, or parts silently dropped?'

const results = await pipeline(
  WS,
  (w) => agent(`${COMMON(w)}\n\n${w.task}`, { label: `impl:${w.ws}`, phase: 'Implement', schema: RESULT, effort: w.effort }),
  async (impl, w) => {
    if (!impl) return { w, impl: null, review: null }
    const review = await agent(`You are an independent, adversarial reviewer for Qompack V6 close-out wave-13 workstream "${w.ws}" (${w.cid}). Worktree ${ROOT}/qompack-cx-w13-${w.ws}, branch closeout/w13-${w.ws}, base ${BASE}. The task was:\n---\n${w.task}\n---\nImplementer result: ${JSON.stringify(impl)}\nReview \`git -C ${ROOT}/qompack-cx-w13-${w.ws} log ${BASE}..HEAD\` and the full diff \`git diff ${BASE} HEAD\`. READ-ONLY: do not edit, commit, stash or reset. You may run focused tests (never ./...; never kill processes you did not start; the machine is loaded — re-run a timing failure alone before believing it). No real claude sessions; never touch the real ~/.qompack or ~/.claude.\n${LENS}\nReturn findings with severity, file:line, evidence and a concrete fix; if sound, verdict "sound" and an empty list.`,
      { label: `review:${w.ws}`, phase: 'Review', schema: FINDINGS, effort: w.reviewEffort })
    return { w, impl, review }
  },
  async (r) => {
    if (!r.impl) return { w: r.w, ws: r.w.ws, impl: null, review: null, final: null }
    const actionable = (r.review ? r.review.findings : []).filter((f) => f.severity !== 'nit')
    if (actionable.length === 0) return { w: r.w, ws: r.w.ws, impl: r.impl, review: r.review, final: r.impl, fixRan: false, actionable }
    const final = await agent(`${COMMON(r.w)}\n\nYou are the FIX seat for this workstream (the implementer has finished). Its task was:\n---\n${r.w.task}\n---\nIndependent reviewer findings:\n${JSON.stringify(actionable, null, 1)}\nVerify each independently; fix the correct ones (failing test first where applicable) and re-run focused tests; rebut wrong ones with evidence. Blockers/majors must be resolved or rebutted. Return the final state with a "Review resolution" section (finding -> action/rebuttal) in your summary, and carry forward every needs_owner item still open (the implementer's were: ${JSON.stringify(r.impl.needs_owner || [])}).`,
      { label: `fix:${r.w.ws}`, phase: 'Fix', schema: RESULT, effort: r.w.effort })
    return { w: r.w, ws: r.w.ws, impl: r.impl, review: r.review, final, fixRan: true, actionable }
  },
  async (r) => {
    if (!r.fixRan || !r.final) return { ws: r.ws, impl: r.impl, review: r.review, final: r.final, fixRan: !!r.fixRan, verify: null }
    const verify = await agent(`You are an independent verifier for Qompack V6 close-out wave-13 workstream "${r.ws}". Worktree ${ROOT}/qompack-cx-w13-${r.ws}, branch closeout/w13-${r.ws}. A reviewer raised these findings:\n${JSON.stringify(r.actionable, null, 1)}\nThe fix seat's result: ${JSON.stringify(r.final)}\nFor EACH finding decide whether it is now resolved correctly or rebutted soundly, by reading the code at HEAD and the fix commits (\`git -C ${ROOT}/qompack-cx-w13-${r.ws} log ${r.impl.head}..HEAD\`), and check the fix commits introduced no new defect or check-weakening. READ-ONLY: do not edit, commit, stash or reset; focused tests allowed (never ./...; never kill processes you did not start; never touch the real ~/.qompack or ~/.claude). Return as findings ONLY what is still wrong (unresolved, badly rebutted, or newly introduced), with severity, file:line, evidence and fix; verdict "sound" with an empty list if everything is resolved.`,
      { label: `verify:${r.ws}`, phase: 'Verify', schema: FINDINGS, effort: r.w.reviewEffort })
    return { ws: r.ws, impl: r.impl, review: r.review, final: r.final, fixRan: true, verify }
  },
)
return results
