export const meta = {
  name: 'v6-closeout-wave16',
  description: 'Wave 16 close-out: candidate 5 e2e rows, PreCompact after client spools, release hygiene, hosted CI reds (D53); reviewed, fixed and verified',
  phases: [
    { title: 'Implement', detail: 'four workstreams off closeout/integration af60666b' },
    { title: 'Review', detail: 'independent adversarial review' },
    { title: 'Fix', detail: 'resolve confirmed findings' },
    { title: 'Verify', detail: 'check the fix seat resolved every non-nit finding' },
  ],
}

const ROOT = 'C:/Users/Quant/Documents/Programming/Projects'
const BASE = 'af60666b'
const SCRATCH = 'C:/Users/Quant/AppData/Local/Temp/claude/C--Users-Quant-Documents-Programming-Projects-qompack/9c57653d-e5ff-4791-8ab4-ad49457994c1/scratchpad/w16'

const COMMON = (w) => `You are one of the parallel workstreams (wave 16: e2erows, spoolseal, relhyg, ci) closing out the Qompack V6 verification (Qompack is a Go Claude Code plugin: hooks -> resident daemon -> content-addressed store under .qompack/, an MCP retrieval server, slash commands). Coordinator ledger (read it; do NOT edit it): ${ROOT}/qompack-v6/plans/V6-CLOSEOUT-CHECKLIST.md — owner decisions D1-D49 and the coordinator defaults are there. Earlier workstream reports are committed on your base under plans/sdd/V6-closeout/<ws>/report.md (wave 1: ingest, e2e, config, hostperm, rollover, perfstore, perfobs, eval, linux, packaging, rehydrate-cap; wave 2b: w2-*; wave 3/4: w3-startroute, w3-paths, w3-e2ereds, w3-eval3, w4-syncs, w4-e2eflakes; wave 5: w5-coldstart, w5-home, w5-winfiles, w5-helpers, w5-dirsync, w5-deps; wave 6: w6-borrow, w6-config, w6-ckptsync, w6-gcserial, w6-linuxrows; wave 7: w7-spawnclaim, w7-layout, w7-sp08d3, w7-docs, w7b-selftest, w7b-checkpoint; wave 8: w8-sp08d3fix, w8-stagerace, w8b-polish) — read the ones relevant to your task first.

YOUR WORKTREE: ${ROOT}/qompack-cx-w16-${w.ws} on branch closeout/w16-${w.ws}, cut from closeout/integration @ ${BASE} (every earlier wave merged). The Bash tool resets cwd between calls: prefix every command with \`cd ${ROOT}/qompack-cx-w16-${w.ws} &&\` or use absolute paths. Never edit other worktrees. Never push, tag, merge, rebase or reset other branches, change git config/hooks, or SendMessage anyone. Your scratch files go under ${SCRATCH}/${w.ws}/ (create it); never delete anything else in that scratchpad.

Hard rules (owner directives, non-negotiable):
- Never weaken a check: no t.Skip, no //nolint, no //nomagic:allow added to silence something, no lowered threshold/budget, no golden regenerated to match broken output, no deleted or loosened assertion, no widened timeout that hides a defect. Criterion changes only with a written rationale in your returned report.
- Root cause first; failing regression test first; then fix.
- New budget/bound numbers are the owner's: implement them behind a named constant with a derivation comment, and list each one (value, derivation, what breaks if it is wrong) under needs_owner; the coordinator gets approval before merging.
- Commits: conventional \`type(scope): subject\` (lowercase scope, subject <=64 chars, no trailing period), body lines <=100 chars, \`Refs: V6-VERIFY, ${w.cid}\` footer on feat/fix, NO attribution trailers (no Co-Authored-By, Signed-off-by, Claude-Session, "Generated with", robot emoji) — the commit-msg hook rejects them. Small focused commits. Evidence logs may be committed under plans/sdd/V6-closeout/w16-${w.ws}/runs/.
- \`go run ./tools/devtool fmt\`/\`fmt-check\`, \`go vet\` on touched packages (Windows and GOOS=linux); \`go test ./test/docs\` and gen-*-docs --check when docs/generated inputs change. Use \`go run ./tools/devtool lint --only=golangci-lint,nomagic,importgraph,testdeps,bindeps,sleepcheck,docmarkers,runpatterns\`: never the stubskips sub-check (it runs a whole-tree go test).
- Tests: FOCUSED runs plus each touched package once in full; never ./... or devtool test/test-race (four other workstreams run tests on this machine and in the Linux container at the same time, so the machine is loaded: re-run any wall-clock failure alone before believing it, and say so). Never let a pipe mask go test's exit code.
- Every \`go test -run\` pattern you quote in your report must match a real test name exactly (the runpatterns lint checks committed reports); name temporary diagnostics as such.
- Processes: never kill a process you did not start. If you must stop your own processes, match on YOUR worktree path or your own scratch subdirectory.
- Linux: container \`qompack-v6-linux-verification\`; the committed script plans/sdd/V6-closeout/linux/linux-nonroot-gate.sh runs an exact commit non-root with -race (see its header; use --prefix cx-w16-${w.ws}; pass --repo and --out as Windows-style C:/ paths, a POSIX /c/ path is refused); never reuse or delete other /work dirs.
- CPU: the owner uses this laptop interactively. Any load generator you start must be bounded with \`timeout\` to at most 20 minutes per run and at most 8 busy processes (of 22 cores), and you must stop it when the measurement ends; never leave one running. Stop your own background diagnostics before you finish.
- Never create, read or modify the real ~/.qompack or ~/.claude in tests; use a fake HOME/USERPROFILE. Real Claude Code sessions are NOT allowed.
- The harness refuses report files from subagents: do NOT write report.md. Return the full report (root causes with evidence, what changed, exact commands + results, criterion changes, open items, owner decisions) in your returned summary; the coordinator commits it.`

const MACHINE = `MACHINE LIMITS FOR THIS SEAT (override the general rules): Phase 3 gates run on this laptop now and memory is tight. The Linux container is STOPPED on purpose: do NOT start it and do not run the Linux gate script; the coordinator runs Linux verification later. On Windows use \`-p 2\`, no load generators. The Phase 3 chain logs to C:/Users/Quant/Documents/Programming/Projects/qompack-v6/plans/sdd/V6-closeout/phase3/chain-2.log: while that file has a "win-timing start" line with no later "win-timing exit" line, an ISOLATED timing gate is running and you must not run anything load-bearing (no hot-path row, no test/integration package, no -race, no benchmark) until it ends; do code reading and cheap deterministic unit tests meanwhile. Run at most one load-bearing test at a time.`

const EV = `EVIDENCE: the Phase 4 live lane ran real Claude Code 2.1.280 sessions on the frozen candidate 3 (d5598eb4) with the packaged bundle. Its report is plans/sdd/V6-closeout/live/report.md in your worktree (evidence dirs beside it under plans/sdd/V6-closeout/live/uat/, c4/, recovery/). Read the rows named below and their evidence files before touching code. Coordinator decision D45 (ledger) says these are fixed before 0.3.0.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and six seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, and do NOT run the hot-path rows (TestIntegration_HotPath*, TestV3_HotPath*) or whole test/integration / test/e2e packages; run only the focused rows you add or touch plus the touched packages in full once. The Linux container is STOPPED: do not start it. Real Claude Code sessions are NOT allowed: reproduce each live finding with a deterministic test (a real daemon/store/hook process in a temp project is fine) that is RED before the fix. The coordinator re-runs the live rows on the fixed candidate.
Other seats in this wave (do not fix their items; if your root cause turns out to be theirs, say so and stop): ledger (elimination ledger, MCP self-record turns, timeline), intent (rehydration intent/corrections/fork), restore (backup/restore/fsck segments/cross-version), pinsckpt (pins view, checkpoint pointers), diag (sentinel scan, status/doctor diagnostics), mcpresp (MCP response bounds/selectors/messages, UAT docs).`

const LIM = `MACHINE LIMITS FOR THIS SEAT (override the general rules): three seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, and do NOT run the hot-path rows (TestIntegration_HotPath*, TestV3_HotPath*) or whole test/integration / test/e2e packages; run the focused rows you add or touch and the touched packages in full once. The Linux container is STOPPED: do not start it. No real Claude Code sessions: reproduce with deterministic tests that are RED before the fix. Read coordinator decision D46 in the ledger. Other seats: observer, decisions, safecut.`

const LIM15_UNUSED = `EVIDENCE: the live re-run on candidate 4 (9f6a2fad, decision D47) ran real Claude Code sessions with the frozen bundle. Its evidence is committed on your base under plans/sdd/V6-closeout/live/rerun-c4/<row>/ and the Result blocks in docs/uat.md; the findings named below come from there. Coordinator decision D49 in the ledger says every one is fixed before 0.3.0 and fixes each disposition: read D45, D46 and D49 first.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and four seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, and do NOT run the hot-path rows (TestIntegration_HotPath*, TestV3_HotPath*) or whole test/integration / test/e2e packages; run the focused rows you add or touch and the touched packages in full once. The Linux container is STOPPED: do not start it. No real Claude Code sessions: reproduce each finding with a deterministic test (a real daemon/store/hook process in a temp project is fine) that is RED before the fix.
Other seats: rehydrate (fallback visibility, evolution admission, eviction order), ledger (stale bloom, advance_frontier, decisions across checkpoints, fork inheritance), services (config reload, recall k, publication accounting, fsck index.files), docs. Do not fix their items; if your root cause is theirs, say so and stop.`

const LIM15A_UNUSED = `EVIDENCE: the candidate 4 live re-run's audit (plans/sdd/V6-closeout/live/report-c4.md, section "Independent audit") and its evidence under plans/sdd/V6-closeout/live/rerun-c4/ are on your base. Coordinator decision D50 in the ledger fixes the dispositions: read D45, D46, D49 and D50 first.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and six seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, and do NOT run the hot-path rows (TestIntegration_HotPath*, TestV3_HotPath*) or whole test/integration / test/e2e packages; run the focused rows you add or touch and the touched packages in full once. The Linux container is STOPPED: do not start it. No real Claude Code sessions: reproduce with deterministic tests that are RED before the fix.
Other seats running now: wave 15 rehydrate (internal/rehydrate), ledger (internal/negknow, checkpoint decisions), services (daemon config reload, mcp recall in handlers.go, store publication accounting, fsck index.files), docs; and paging / snapshot in this wave. Do not fix their items or edit their files beyond what your fix needs; if your root cause is theirs, say so and stop.`

const LIM15B_UNUSED = `EVIDENCE: the candidate 4 live re-run's audit (plans/sdd/V6-closeout/live/report-c4.md, section "Independent audit") and its evidence under plans/sdd/V6-closeout/live/rerun-c4/ are on your base, with wave 15 (docs, ledger) and wave 15a (paging, snapshot) merged. Coordinator decision D50 in the ledger fixes the dispositions: read D46, D49 and D50 first.
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and other seats run at once. Use \`-p 2\`, no load generators, no hot-path rows, no whole test/integration or test/e2e packages. The Linux container is STOPPED: do not start it. No real Claude Code sessions.
Other seats running now: wave 15 rehydrate (internal/rehydrate) and services (daemon reload, mcp recall, store publication accounting, fsck). Do not edit their files.`

const LIM15C = `Coordinator decisions D49 and D51 in the ledger govern this task: read them. The wave 15 services report is on your base: plans/sdd/V6-closeout/w15-services/report.md (its needs_owner and open issues are the source of this task).
MACHINE LIMITS FOR THIS SEAT (override the general rules): the owner is using this laptop and another seat runs. Use \`-p 2\`, no load generators except the bounded measurement below, no hot-path rows, no whole test/integration or test/e2e. The Linux container is STOPPED: do not start it. No real Claude Code sessions.
Other seat running now: wave 15 rehydrate (internal/rehydrate). Do not edit its files.`

const LIM16 = `Coordinator decision D53 in the ledger governs this wave: read it, with D45, D46, D49 and D50. The independent audit it disposes is plans/sdd/V6-closeout/audit/goal-metrics-audit.md on verify/v6 (read it at ${ROOT}/qompack-v6/plans/sdd/V6-closeout/audit/goal-metrics-audit.md). Candidate 5's overnight evidence is under ${ROOT}/qompack-v6/plans/sdd/V6-closeout/phase3/c5/ (p3-win-e2e-timing.log, linux/cx-p3-p3-linux-e2e-timing-*/, quiet/).
MACHINE LIMITS FOR THIS SEAT (override the general rules): DAYTIME, the owner is using this laptop and other seats run at once. Use \`-p 2\`, no load generators, no -race on whole packages, and do NOT run the hot-path rows (TestIntegration_HotPath*, TestV3_HotPath*) or whole test/integration / test/e2e packages; run the focused rows you add or touch (by exact name) and each touched package in full once. The Linux container is STOPPED: do not start it; the coordinator runs Linux verification and the whole e2e package at night. No real Claude Code sessions.
Other seats in this wave: e2erows (the three e2e rows and the store benchmark HOME leak), spoolseal (PreCompact after client spools, spool-submode wording, slow-disk docs), relhyg (bundle notices, descriptions, marketplace trigger, recall self-record prefix), ci (hosted CI reds: os/exec allow-list, macOS zombie liveness and socket paths, Q1 non-reference disk declaration, cover's TestE2EHookRoundTrip). Do not fix their items or edit their files beyond what your fix needs; if your root cause is theirs, say so and stop.`

const WS = []

WS.push({ ws: 'e2erows', cid: 'C3.4', effort: 'high', reviewEffort: 'high', task: `TASK — candidate 5's three failing e2e rows and the store benchmark HOME leak (D53(a)).
${LIM16}
Each row fails identically on Windows and Linux (phase3/c5/p3-win-e2e-timing.log lines 1-6 and 150-182). Decide each one as a stale criterion or a product defect from evidence, never by preference, and write the rationale for every criterion change in your report. A criterion change must still fail on the regression the row exists to catch: show that, for each one, by temporarily breaking the product and naming the result as a temporary diagnostic.
(1) TestDaemonIdleRunsSchedulerWork (test/e2e/scheduler_idle_test.go:186-198) requires sched counter "sources unavailable" > 0 because "a daemon that has never compacted has no ledger". D49 made "no ledger yet is not an advance_frontier error", and wave 15 ledger changed when the ledger opens (read plans/sdd/V6-closeout/w15-ledger/report.md). Find what the shipped daemon now does on an idle pass with no ledger and assert exactly that, so a regression that unwires the advancer or turns the no-ledger case back into an error still fails. Check its comment's claims (eager open, sketches/tried.bloom, which tests guard it) against the code and correct them.
(2) TestV5_ObserveToStatusRoundTrip/daemon_down_falls_back_to_persisted_snapshot: "B-A from disk: p99" expected 147456 µs, got 141000. e2e7e480 made status clamp every percentile to the snapshot's max (internal/commands/statuscollect.go:452-470). The helper x1v5RequireLatencyEquals still compares raw quantiles: apply the same clamp, keeping the "same distribution" check exact otherwise.
(3) TestV5_ObserveToStatusRoundTrip/live: two status reads of the same state differ only in the TS of hook.additional_context_delivered (1790821924508 vs ...539). The live row is right: a contract result that status or doctor refreshes from state/history.json (wave 15a snapshot, plans/sdd/V6-closeout/w15a-snapshot/report.md) must carry the time of the observation it was derived from, never the read time, so two reads of unchanged state are equal. Fix the product with a failing unit test first; the e2e row must then pass unchanged.
(4) TestV5_ThrashWarningVisibleInStatusAndCheckpoint/sequitur_warning_is_warning_only_and_once_per_rule (test/e2e/v5_x10_test.go:430-452): the arm echoes the delivered warning back as a user prompt, and since D45/D46 every user prompt reaches user_intent.evolution verbatim, so the sealed checkpoint carries the warning text as that prompt. Verbatim user prompts are a guarantee (never strip or rewrite a user's words). Narrow the assertion to what the row protects: Qompack never puts its own warning on a durable surface. The checkpoint may contain the warning text only as evolution entries that are exactly an echoed prompt, and nowhere else: not in any other field, and not attached to the prompt the warning was delivered with. Keep the elimination-record checks.
(5) The store benchmark binary exits 1 after PASS in quiet C5.2 rounds 2-4 on Windows (phase3/c5/quiet/c52-win/c52-win-r2-candidate-store-1s.log and the r3/r4 logs): "pathstest: HOME is ...\\1661447237\\001\\home at the end of the run, not the isolated home". A benchmark leaves HOME changed (b.Setenv in internal/store/bench_test.go benchStore and BenchmarkOpenStore_50kRoots, or something else). Find the leak, fix it (test code only), and prove it with the same invocation as quiet.sh's c52 store step: -test.run '^$', the same -test.bench pattern, -test.benchtime 100ms, -test.count 3. Check every other package quiet.sh benchmarks for the same pattern.
Scope: test/e2e/scheduler_idle_test.go, test/e2e/v5_x01_test.go, test/e2e/v5_x10_test.go, the contract snapshot refresh code (internal/commands and/or internal/contract), internal/store benchmark code and whatever (5) points to. Run each e2e row you touch by exact name with -count=1 (each alone; they start daemons), and the packages you change in full once.` })

WS.push({ ws: 'spoolseal', cid: 'C4.3', effort: 'high', reviewEffort: 'high', task: `TASK — a compaction never misses this session's spooled captures, and slow-disk spool submode stops looking broken (D53(c)).
${LIM16}
Background: on a disk whose fsync is slower than runtime.budgets.l0IngestMs (Linux default 15 ms; the Docker Desktop/WSL2 container measures B-B p50 ~37 ms), each hook waits at most the ACK deadline and spools a copy, and after three consecutive 512-sample breach windows the daemon moves to spool submode for the rest of the session (internal/daemon/budget.go:95-124, handlers.go:451-463; D39, D41, D44). Nothing is lost (phase3/c5/quiet/c51-linux/c51-linux.log: 3590 deferred, 0 lost). The audit (section 2.2) found two problems.
(1) Possible context gap: the PreCompact route seals without replaying the session's client spools (internal/daemon/handlers.go:1171-1230, wire_checkpoint.go:145-196); spooled captures reach the store about two watcher intervals later (spool_watch.go:44-53). Verify this first with a failing test: a compaction while this session's newest tool results sit only in a client spool, deferred or in spool submode, must seal a checkpoint and a rehydration that account for them. Fix: before sealing, PreCompact replays this session's client-spooled captures (the C1.13 session-end path does the same for SessionEnd; reuse it), bounded inside PreCompact's existing budget (B-E, the 20 s manifest timeout, compactAnswerBudget; no new number unless derived from these and named). A capture still unreplayed when the bound expires is named in the checkpoint's drop report and the payload's section 7, never silently missing. Prove that a healthy session (nothing spooled) pays nothing measurable.
(2) Spool submode must not make a healthy session look broken (D45, D41's precedent). Find every user-facing surface the transition reaches: the WARN and LOUD lines, status, doctor, the SessionStart degrade banner and the contract mode. Make the wording say what happened, that nothing is lost, what ends it, and how to tune it:
  - what happened: durable writes on this disk took longer than runtime.budgets.l0IngestMs, so hooks hand captures to the spool, which the daemon replays;
  - what ends it: a new session or the daemon's idle exit (there is no stop command);
  - how to tune it: runtime.hotPath.budgetMs, runtime.budgets.l0IngestMs and the ACK deadline key, named exactly as config-reference.md names them.
  If status or doctor reports FAILING, or the banner calls the session degraded, purely because of spool submode, make it informational but still visible. Machine-readable fields stay stable or change additively. No default number changes.
(3) docs/troubleshooting.md: a slow-disk entry (WSL2, containers, network or encrypted filesystems): the symptom, that it is expected and loses nothing, and the tuning keys. Correct any page that attributes spool submode only to a "heavily loaded" machine or names a stop command.
Scope: internal/daemon (PreCompact route, spool replay, budget/breach surfaces), internal/commands (status/doctor wording), internal/checkpoint or internal/rehydrate only for the drop entry, docs. Run the daemon rows you add or touch by name and the touched packages in full once.` })

WS.push({ ws: 'relhyg', cid: 'C7.5', effort: 'medium', reviewEffort: 'high', task: `TASK — release hygiene for a public plugin (D53(e), audit F2, F4, F8).
${LIM16}
(1) LICENSE and notices in every bundle (F4): devtool bundle (tools/devtool) and .goreleaser.yaml must ship the repo's LICENSE and THIRD_PARTY_NOTICES.md in every target's bundle and zip. THIRD_PARTY_NOTICES.md wrongly says the Go standard library is not redistributed (around lines 40-46 and 843-844): the Go runtime and standard library are compiled into every binary, so add Go's licence text (BSD-3-Clause, from the Go distribution's LICENSE) and correct the statement. Check that every statically linked module's licence is present (go-winio, klauspost/compress, golang.org/x/sys, any other in go.mod's build list for the shipped binary). Update the bundle tests, plugin-validate expectations and packaging/README.md's file list. Reproducibility must hold: two bundle builds of one target stay byte-identical (run it for windows/amd64 and linux/amd64).
(2) Accurate descriptions (F8): plugin/.claude-plugin/plugin.json's description, internal/pluginmanifest/manifest.go and tools/devtool/marketplace.go say "Cache-aware, retrieval-backed context compaction". Qompack does not compact, and the cache state is passed as unknown. Write one accurate sentence: Qompack keeps a local record of the session and restores the important parts after Claude Code compacts its context, with tools to recall anything left out. Use it everywhere it appears, regenerate generated files, and update tests and goldens to the new text (this is a text change, not a weakened check). The /qompack:pin command text says pins are "never summarized away". Pins are re-injected after a compaction within the 9,500-character cap, and nothing shields them from the summarizer: reword it to say that.
(3) .github/workflows/marketplace.yml fires only on release 'published' and skips pre-releases. Promoting a pre-release fires 'released', so the documented 'pre-release first, then promote' route would never open the marketplace pull request. Make it run exactly once for a full release, whether published directly or promoted from a pre-release, and never for a pre-release. Update docs/release.md, and add a test or lint row if the repo tests workflow files (test/release).
(4) Recall's self-record test (internal/mcp/recall_rank.go:9-22) assumes the host names tools mcp__plugin_qompack_qompack__<tool>. A release install comes from a marketplace entry named qompack-<os>-<arch>; the probe plans/sdd/V6-closeout/packaging/evidence/c7.5-marketplace/entry-name-probe.txt shows the host lists it as qompack-windows-amd64@qompack, and the tool namespace for such an entry has never been observed. Match mcp__plugin_<any entry segment>_qompack__<a Qompack retrieval tool> so both spellings rank last. Another plugin's tool, or a non-retrieval tool with a similar name, must not match: require the server segment and a known tool name. Add tests for both spellings and the negatives. Find any other code or doc that hard-codes the plugin_qompack_qompack prefix or the /qompack: command namespace, and list it in your report. Do not change docs that state the namespace: the candidate 6 live lane observes it (D53(f)).
Scope: tools/devtool (bundle, marketplace), .goreleaser.yaml, THIRD_PARTY_NOTICES.md, packaging/, plugin/, internal/pluginmanifest, internal/mcp/recall_rank.go, .github/workflows/marketplace.yml, docs/release.md, their tests.` })

WS.push({ ws: 'ci', cid: 'C7.2', effort: 'high', reviewEffort: 'high', task: `TASK — make hosted CI (C7.2) green honestly on all three OSes (D53(e), (h)).
${LIM16}
verify/v6 was pushed and ci.yml ran on candidate 5's code: run 36816905394 (https://github.com/AidanHT/qompack/actions/runs/36816905394). Read each failed job's log with \`gh run view 36816905394 --json jobs\` and \`gh api repos/AidanHT/qompack/actions/jobs/<id>/logs\` (read-only; never re-run, cancel or push). The e2e rows TestDaemonIdleRunsSchedulerWork, TestV5_ObserveToStatusRoundTrip and TestV5_ThrashWarningVisibleInStatusAndCheckpoint belong to the e2erows seat. TestCarriedDefects_WaveReportRequiresResolution (five perf rows) belongs to the coordinator's C2.8 dispositions. Everything else red is yours:
(1) security: the os/exec allow-list step fails on internal/paths/pathstest, which runs \`go env\` (a9f276e7, b763d728) to pin toolchain paths before isolating HOME. pathstest is test support like internal/testutil, which the list already allows. Add it with a comment saying why, and make the step also prove that no non-test package imports pathstest or testutil. A product package with os/exec must still fail.
(2) macOS, zombie liveness: TestShutdownDaemonUntilGone_ReadsTheHolderBeforeEachShutdown and TestShutdownDaemonUntilGone_WaitsForEveryLockHolderToExit (internal/testutil), and TestE2EShutdownIfReachable_WaitsForASpawnStillInFlight and TestE2EShutdownIfReachable_WaitsForEveryLockHolderToExit (test/e2e), see "still running" for 20 s. The process is then "reaped 121µs after the return": it is the test's own exited but unreaped child, and the liveness probe counts a zombie as alive on darwin. Fix the probe so an exited zombie counts as gone on every POSIX platform; read how Linux does it today first. Keep the guarantee these helpers exist for: never return while a live daemon still writes into the tree. Check that the product's own lock liveness (internal/daemon lock and pid checks) has no darwin zombie hole. Its daemons are detached and reaped by launchd, but confirm it and say so.
(3) macOS, socket paths: TestBackupCLI_VerifyJudgesWhatRestoreJudges (internal/cli) fails with "ipc address exceeds sun_path limit". The test's TMPDIR is a long t.TempDir() under /var/folders/..., so even the short fallback exceeds 100 bytes. TestReadBoundedObject_RefusesASocketLeaf (internal/store) fails the same way: "bind: invalid argument" for a socket under t.TempDir(). Give these fixtures a short directory on darwin (for example under /tmp, removed by t.Cleanup), and find every other test that binds a Unix socket under t.TempDir(). Confirm with a unit test of ipc.resolveFor that a typical macOS TMPDIR (/var/folders/<2>/<30>/T/) resolves within sunPathMax. If any real-user case can exceed it, report it; do not change product behaviour for it.
(4) Q1, hosted fsync-bound rows: bench-gate (ubuntu-latest B-B p50 0.58 ms but p99 41 ms; windows-latest p50 45 ms), timing (windows-latest TestIntegration_HotPathWarmWithRealResidentState) and any hosted X11 failure (test-e2e) fail on the hosted runners' fsync tail (memory of Q1: hosted figures never become constants, and hosted runners are not co-loaded, so QOMPACK_UNDER_COLOAD must NOT be used). Add one explicit declaration that a run is on a non-reference disk, for example QOMPACK_NONREFERENCE_DISK=1 or a bench-hotpath flag; follow the codebase's naming:
  - it is honoured only when GITHUB_ACTIONS=true;
  - under it, the fsync-bound wall rows (B-A, B-B and B-E's wall row) and the spool-submode transition are reported, not gated, with the reason named in the output and the JSON;
  - B-E_cpu, the delivery-ledger identity, 0 lost, the census and every structural check stay gated exactly as now;
  - ci.yml sets it in bench-gate, the timing job and test-e2e on every hosted OS, with a comment citing Q1 and D53.
  Add a guard test that the declaration is ignored outside GitHub Actions and never set by quiet.sh, phase3.sh or overnight.sh. The local isolated D28 rows and quiet C5.1 stay gated as today.
(5) cover (ubuntu-latest): TestE2EHookRoundTrip failed under coverage instrumentation ("Condition never satisfied" at test/e2e/daemon_e2e_test.go:273). Find the root cause: an instrumentation-slowed wait, or a real race. Fix it accordingly; never widen a timeout that hides a defect.
(6) lint-windows fails only stubskips: inside its whole-tree run the test/e2e binary was killed past -timeout=30m on windows-latest, so its skips were never inspected (the hosted e2e package alone takes about 25 min there, X11 390 s). Fix how stubskips runs e2e so the tree is fully inspected, without dropping any package and without the timeout hiding a hang. (7) test (windows-latest), job 110223848442, has two reds beyond the carried-defect guard. (a) test/fault: about 20 rows (TestFault_Lifecycle/*, TestFault_HookStdinUnusable/*, TestFault_DaemonKilledMidIngest, TestFault_CheckpointDropsAnUnresolvablePointer, TestFault_CheckpointResolvabilityIsBlindToADeletedObject and others) print PASS with their audit, and the same subtest then fails with 'fault: writing <t.TempDir()>\...\<row>.json: The system cannot find the path specified'. Writing the artifact apparently races or outlives the TempDir cleanup; check whether the job runs the package twice or the cleanup order is wrong. Find the cause, and run test/fault on Windows locally (-p 2) to see whether it reproduces here; the c5 pre-freeze check never ran test/fault. (b) TestEnsureLayout_WriteAtomicFailureIsPropagated (internal/paths/layout_test.go:107): 'An error is expected but got nil' on the hosted runner. Its fault injection probably relies on a permission the runner's elevated account bypasses; make the injection deterministic without weakening what the row proves. Fix any further red on any OS that is none of the above and not another seat's, or report it with its cause. Check whether ci.yml's EXPECTED_FAILING_ROWS mechanism needs the carried-defect rows until the coordinator dispositions them; do not add them, say what the coordinator must do.
You cannot run hosted CI; prove each fix locally where the platform allows (GOOS=darwin vet/build for darwin code, Windows and the darwin-equivalent logic in unit tests) and say exactly what only the next hosted run can confirm.
Scope: .github/workflows/ci.yml, internal/testutil, test/e2e shutdown helpers, the darwin-affected test fixtures, internal/ipc tests, test/bench/hotpath and tools/devtool bench-hotpath (the declaration), test/integration and test/e2e hot-path rows' gating reads, test/guards for the new guard.` })

const RESULT = { type: 'object', properties: {
  status: { type: 'string', enum: ['done', 'partial', 'blocked'] }, head: { type: 'string' },
  commits: { type: 'array', items: { type: 'string' } }, root_cause: { type: 'string' }, summary: { type: 'string' },
  tests: { type: 'array', items: { type: 'object', properties: { command: { type: 'string' }, result: { type: 'string' } }, required: ['command', 'result'] } },
  criterion_changes: { type: 'array', items: { type: 'string' } }, open_issues: { type: 'array', items: { type: 'string' } },
  needs_owner: { type: 'array', items: { type: 'string' } },
}, required: ['status', 'head', 'commits', 'summary', 'tests', 'open_issues', 'needs_owner'] }
const FINDINGS = { type: 'object', properties: {
  verdict: { type: 'string', enum: ['sound', 'needs-fixes', 'unsound'] },
  findings: { type: 'array', items: { type: 'object', properties: {
    severity: { type: 'string', enum: ['blocker', 'major', 'minor', 'nit'] }, location: { type: 'string' },
    issue: { type: 'string' }, evidence: { type: 'string' }, fix: { type: 'string' },
  }, required: ['severity', 'location', 'issue', 'evidence', 'fix'] } },
}, required: ['verdict', 'findings'] }

const LENS = 'Lenses: (a) root cause proven and fixed at the source; correctness incl. concurrency (races, deadlocks, lock order, goroutine leaks), durability/crash semantics (fsync ordering, WAL retention, idempotency, identity never re-minted), fail-closed paths, Windows vs POSIX, bounded memory/CPU; (b) check-weakening (deleted/loosened assertions, skips, nolint/nomagic, lowered thresholds, regenerated goldens, widened timeouts, tests bent to buggy output) and legitimacy of every criterion change; (c) every new bound/budget number is named, derived, and listed for the owner; (d) docs consistent with behaviour, generated docs via generators; (e) commit hygiene (conventional subjects, Refs footer, no attribution trailers); (f) was the whole task done, or parts silently dropped?'

const results = await pipeline(
  WS,
  (w) => agent(`${COMMON(w)}\n\n${w.task}`, { label: `impl:${w.ws}`, phase: 'Implement', schema: RESULT, effort: w.effort }),
  async (impl, w) => {
    if (!impl) return { w, impl: null, review: null }
    const review = await agent(`You are an independent, adversarial reviewer for Qompack V6 close-out wave-16 workstream "${w.ws}" (${w.cid}). Worktree ${ROOT}/qompack-cx-w16-${w.ws}, branch closeout/w16-${w.ws}, base ${BASE}. The task was:\n---\n${w.task}\n---\nImplementer result: ${JSON.stringify(impl)}\nReview \`git -C ${ROOT}/qompack-cx-w16-${w.ws} log ${BASE}..HEAD\` and the full diff \`git diff ${BASE} HEAD\`. READ-ONLY: do not edit, commit, stash or reset. You may run focused tests (never ./...; never kill processes you did not start; the machine is loaded — re-run a timing failure alone before believing it). No real claude sessions; never touch the real ~/.qompack or ~/.claude.\n${LENS}\nReturn findings with severity, file:line, evidence and a concrete fix; if sound, verdict "sound" and an empty list.`,
      { label: `review:${w.ws}`, phase: 'Review', schema: FINDINGS, effort: w.reviewEffort })
    return { w, impl, review }
  },
  async (r) => {
    if (!r.impl) return { w: r.w, ws: r.w.ws, impl: null, review: null, final: null }
    const actionable = (r.review ? r.review.findings : []).filter((f) => f.severity !== 'nit')
    if (actionable.length === 0) return { w: r.w, ws: r.w.ws, impl: r.impl, review: r.review, final: r.impl, fixRan: false, actionable }
    const final = await agent(`${COMMON(r.w)}\n\nYou are the FIX seat for this workstream (the implementer has finished). Its task was:\n---\n${r.w.task}\n---\nIndependent reviewer findings:\n${JSON.stringify(actionable, null, 1)}\nVerify each independently; fix the correct ones (failing test first where applicable) and re-run focused tests; rebut wrong ones with evidence. Blockers/majors must be resolved or rebutted. Return the final state with a "Review resolution" section (finding -> action/rebuttal) in your summary, and carry forward every needs_owner item still open (the implementer's were: ${JSON.stringify(r.impl.needs_owner || [])}).`,
      { label: `fix:${r.w.ws}`, phase: 'Fix', schema: RESULT, effort: r.w.effort })
    return { w: r.w, ws: r.w.ws, impl: r.impl, review: r.review, final, fixRan: true, actionable }
  },
  async (r) => {
    if (!r.fixRan || !r.final) return { ws: r.ws, impl: r.impl, review: r.review, final: r.final, fixRan: !!r.fixRan, verify: null }
    const verify = await agent(`You are an independent verifier for Qompack V6 close-out wave-16 workstream "${r.ws}". Worktree ${ROOT}/qompack-cx-w16-${r.ws}, branch closeout/w16-${r.ws}. A reviewer raised these findings:\n${JSON.stringify(r.actionable, null, 1)}\nThe fix seat's result: ${JSON.stringify(r.final)}\nFor EACH finding decide whether it is now resolved correctly or rebutted soundly, by reading the code at HEAD and the fix commits (\`git -C ${ROOT}/qompack-cx-w16-${r.ws} log ${r.impl.head}..HEAD\`), and check the fix commits introduced no new defect or check-weakening. READ-ONLY: do not edit, commit, stash or reset; focused tests allowed (never ./...; never kill processes you did not start; never touch the real ~/.qompack or ~/.claude). Return as findings ONLY what is still wrong (unresolved, badly rebutted, or newly introduced), with severity, file:line, evidence and fix; verdict "sound" with an empty list if everything is resolved.`,
      { label: `verify:${r.ws}`, phase: 'Verify', schema: FINDINGS, effort: r.w.reviewEffort })
    return { ws: r.ws, impl: r.impl, review: r.review, final: r.final, fixRan: true, verify }
  },
)
return results
