package sketchtest

import (
	"crypto/sha256"
	"testing"

	"github.com/qompack/qompack/internal/sketch"
	"github.com/stretchr/testify/require"
)

// mhChunkSize is the size, in bytes, of each pseudo-random "chunk" mhFixture concatenates.
// mhPermutations and mhShingleSize are the MinHashOptions the suite probes and tests with.
const (
	mhChunkSize    = 500
	mhPermutations = 128
	mhShingleSize  = 8
)

// mhJaccardTolerance is the exact tolerance 00-ARCHITECTURE.md §15's behaviour table specifies
// ("MinHash Jaccard within 0.1 of exact on known sets"): an independent test-spec constant, not a
// duplicate of any config default.
const mhJaccardTolerance = 0.1 //nomagic:allow §15 behaviour-table tolerance, not a config default

// mhChunk returns a deterministic, seed-derived pseudo-random byte blob, generated by repeatedly
// hashing a counter (gosec G404 forbids math/rand outside test files; crypto/sha256 is used here
// only as a convenient deterministic byte-stream generator, not for any security property).
func mhChunk(seed byte) []byte {
	out := make([]byte, 0, mhChunkSize+sha256.Size)
	block := [5]byte{seed, 0, 0, 0, 0}
	var counter uint32
	for len(out) < mhChunkSize {
		block[1] = byte(counter)
		block[2] = byte(counter >> 8)
		block[3] = byte(counter >> 16)
		block[4] = byte(counter >> 24)
		h := sha256.Sum256(block[:])
		out = append(out, h[:]...)
		counter++
	}
	return out[:mhChunkSize]
}

// mhConcat concatenates mhChunk(seed) for every seed in seeds.
func mhConcat(seeds []byte) []byte {
	var out []byte
	for _, s := range seeds {
		out = append(out, mhChunk(s)...)
	}
	return out
}

// RunMinHashSuite is the conformance suite for the package-level sketch.MinHash function and the
// Signature it returns. Unlike every other suite in this package, MinHash has no constructible
// type behind it, so the suite takes the function itself rather than a factory.
func RunMinHashSuite(t *testing.T, name string, minHash func(data []byte, o sketch.MinHashOptions) sketch.Signature) {
	t.Helper()
	opts := sketch.MinHashOptions{Enabled: true, Permutations: mhPermutations, ShingleSize: mhShingleSize}

	t.Run(name+"/shape", func(t *testing.T) {
		sig := minHash([]byte("shape probe"), opts)
		// MinHash, Jaccard, IsNearDup and MarshalBinary all have no error return except
		// MarshalBinary/UnmarshalBinary; any Signature MinHash produces, including the zero
		// value, is shape-valid.
		_ = sig.Jaccard(sig)
		_ = sig.IsNearDup(sig, mhJaccardTolerance)

		_, err := sig.MarshalBinary()
		requireKnownError(t, err)
		var sig2 sketch.Signature
		requireKnownError(t, sig2.UnmarshalBinary(nil))
	})

	if skipIfStubMinHash(t, minHash) {
		return
	}

	t.Run(name+"/behaviour", func(t *testing.T) {
		t.Run("jaccard_within_tolerance_of_exact", func(t *testing.T) {
			runJaccardWithinToleranceCase(t, minHash)
		})
	})
}

// isStubMinHash reports whether minHash is still a stub. MinHash has no error return (§5.7), so —
// like chunk, symbols, redact and grammar's suites — this cannot check core.IsNotImplemented and
// instead relies on Rule 1's documented stub contract directly: the SP-01 stub always returns the
// zero Signature (Mins == nil), and any real k-permutation implementation asked for
// mhPermutations permutations over non-empty data must return exactly that many minimum hashes.
func isStubMinHash(t *testing.T, minHash func(data []byte, o sketch.MinHashOptions) sketch.Signature) bool {
	t.Helper()
	opts := sketch.MinHashOptions{Enabled: true, Permutations: mhPermutations, ShingleSize: mhShingleSize}
	sig := minHash(mhChunk(0), opts)
	return len(sig.Mins) == 0
}

// skipIfStubMinHash calls t.Skip with the exact Rule W-1 message when minHash is still a stub,
// and reports whether it did.
func skipIfStubMinHash(t *testing.T, minHash func(data []byte, o sketch.MinHashOptions) sketch.Signature) bool {
	t.Helper()
	if isStubMinHash(t, minHash) {
		t.Skip(ruleW1SkipMsg)
		return true
	}
	return false
}

// runJaccardWithinToleranceCase builds two byte strings out of a shared pool of 9 distinct,
// large, pseudo-random chunks: A is chunks {0..5}, B is chunks {3..8}, so they share exactly 3
// chunks out of a 9-chunk union — a known, approximate set Jaccard of 3/9 = 1/3. Because each
// chunk is far larger than mhShingleSize and internally non-repetitive, the true shingle-level
// Jaccard of A and B is very close to that chunk-level ratio (the only discrepancy comes from the
// handful of shingles straddling a chunk boundary), so this fixture does not depend on knowing
// MinHash's exact shingling convention (byte-level vs. token-level) — only that shingles are
// local, which any reasonable w-shingling scheme satisfies.
func runJaccardWithinToleranceCase(t *testing.T, minHash func(data []byte, o sketch.MinHashOptions) sketch.Signature) {
	t.Helper()
	opts := sketch.MinHashOptions{Enabled: true, Permutations: mhPermutations, ShingleSize: mhShingleSize}

	a := minHash(mhConcat([]byte{0, 1, 2, 3, 4, 5}), opts)
	b := minHash(mhConcat([]byte{3, 4, 5, 6, 7, 8}), opts)

	const shared, union = 3.0, 9.0
	exact := shared / union

	got := a.Jaccard(b)
	require.InDelta(t, exact, got, mhJaccardTolerance,
		"MinHash Jaccard (%v) must be within %v of the exact set Jaccard (%v)", got, mhJaccardTolerance, exact)
}
